<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>R workflow</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d4be639c637f3db3c684c66cefad7e0c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body>

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="lecture-01.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">R workflow</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>[conflicted] Will prefer haven::is.labelled over any other package.
[conflicted] Will prefer dplyr::filter over any other package.
[conflicted] Will prefer dplyr::summarise over any other package.</code></pre>
</div>
</div>
<section id="agenda" class="level1" data-menu-title="Agenda" data-background-image="images/calendar.png" data-background-size="100px" data-background-repeat="repeat">
<h1 data-menu-title="Agenda" data-background-image="images/calendar.png" data-background-size="100px" data-background-repeat="repeat">Agenda</h1>
<ul>
<li>R &amp; RStudio Workflow</li>
<li>Quarto</li>
<li>Getting Started</li>
</ul>
</section>
<section id="learning-objectives" class="level1">
<h1>Learning objectives</h1>
<p>By the end of the lecture, you will be able to …</p>
<ul>
<li>setup a workflow using R and RStudio<br>
</li>
<li>familiarize yourself with a dataset using R and RStudio<br>
</li>
<li>create a reproducible report using Quarto<br>
</li>
</ul>
</section>
<section id="r-rstudio-tour" class="level1 theme-section page-columns page-full">
<h1 class="theme-section">R &amp; RStudio Tour</h1>
<section id="tour-rstudio-panes" class="level2" data-background-image="images/watch.png" data-background-size="100px" data-background-repeat="repeat">
<h2 data-background-image="images/watch.png" data-background-size="100px" data-background-repeat="repeat" class="anchored" data-anchor-id="tour-rstudio-panes">Tour: RStudio Panes</h2>
<p><br></p>
<div style="color: #18BC9C; font-size: 300%; font-family: 'Shadows Into Light'">
<p>Sit back and enjoy the show!</p>
</div>
<div class="notes">
<ul>
<li>open new R script<br>
</li>
<li>Environment (data values, functions)</li>
<li>Plots, Help, Viewer</li>
<li>Console – typing</li>
</ul>
</div>
</section>
<section id="mini-task" class="level2 smaller page-columns page-full" data-menu-title="R-scripts (&amp; Quarto)">
<h2 class="smaller anchored" data-menu-title="R-scripts (&amp; Quarto)" data-anchor-id="mini-task">Mini-task</h2>
<div class="task">
<p><i class="fa-solid fa-check-double" aria-label="check-double"></i> Open a new R Script.</p>
</div>
<p>Click the dropdown arrow next to the “<span style="color: #3498DB">New File icon</span>,” and then “<span style="color: #3498DB">R script</span>”.</p>
<p><video src="videos/01/R-script.mp4" class="img-fluid" style="width:65.0%" controls=""><a href="videos/01/R-script.mp4">Video</a></video></p>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Alternatively, hold down “Ctrl” + “Shift” + “N.”</p>
</div></div><div class="notes">
<p>An R-script is a file that will contain the documentation of the code of what you tell R to do.</p>
</div>
</section>
<section id="mini-tasks" class="level2 sparse-slide">
<h2 class="sparse-slide anchored" data-anchor-id="mini-tasks">Mini-tasks</h2>
<div class="task">
<p><i class="fa-solid fa-check-double" aria-label="check-double"></i> Type <code>2 + 2</code> in the Console. Then push <code>Enter</code>.</p>
</div>
<p><br></p>
<p>. . .</p>
<div class="task">
<p><i class="fa-solid fa-check-double" aria-label="check-double"></i> Type <code>2 + 2</code> in the R Script Then click <code>Run</code>.</p>
</div>
<div class="notes">
<p>What’s the difference between the console and a script file?</p>
</div>
</section>
<section id="documentation" class="level2">
<h2 class="anchored" data-anchor-id="documentation">Documentation</h2>
<div class="r-stack">
<p><img src="images/01/documentation.png" class="img-fluid"></p>
<p><img src="images/01/pound.png" class="fragment img-fluid" data-fragment-index="1"></p>
</div>
<div class="notes">
<p>In .R scripts and Quarto, you can document your code. Err on the side of over documentation. Your future self will thank you. In .R scripts, the way to make a comment rather than a command, is to put a pound sign in front of the text.</p>
</div>
</section>
<section id="mini-task-1" class="level2 sparse-slide">
<h2 class="sparse-slide anchored" data-anchor-id="mini-task-1">Mini-task</h2>
<div class="task">
<p><i class="fa-solid fa-check-double" aria-label="check-double"></i> Add a comment above your <code>2 + 2</code> code in your R script. Then click <code>Run</code>.</p>
</div>
</section>
<section id="tour-recap-panes" class="level2">
<h2 class="anchored" data-anchor-id="tour-recap-panes">Tour recap: Panes</h2>
<div class="r-stack">
<div style="font-size: 80%">
<p>There are four key regions or “panes” in the interface:</p>
<ol type="1">
<li><p><a href="https://docs.posit.co/ide/user/ide/guide/ui/ui-panes.html#source" target="_blank"><strong>Source pane:</strong></a> where you can edit and save R scripts or author computational documents like Quarto and R Markdown.</p></li>
<li><p><a href="https://docs.posit.co/ide/user/ide/guide/ui/ui-panes.html#console" target="_blank"><strong>Console pane:</strong></a> is used to write short interactive R commands.</p></li>
<li><p><a href="https://docs.posit.co/ide/user/ide/guide/ui/ui-panes.html#environment-pane" target="_blank"><strong>Environment pane:</strong></a> displays temporary R objects created during that R session.</p></li>
<li><p><a href="https://docs.posit.co/ide/user/ide/guide/ui/ui-panes.html#output-pane" target="_blank"><strong>Output pane:</strong></a> displays the plots, tables, or HTML outputs of executed code along with files saved to disk.</p></li>
</ol>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-hat-wizard" aria-label="hat-wizard"></i> Heads Up!
</div>
</div>
<div class="callout-body-container callout-body">
<p>The top-left panel (source pane) and can be launched by opening any editable file in RStudio.</p>
</div>
</div>
</div>
<p><img src="images/01/panes.png" class="fragment img-fluid" data-fragment-index="1"></p>
</div>
<div class="notes">
<p>Console pane: best for exploring.<br>
Source pane: best for documenting.</p>
</div>
</section>
<section id="rstudio-projects" class="level2 sparese-slide">
<h2 class="sparese-slide anchored" data-anchor-id="rstudio-projects">RStudio projects</h2>
<p>Create a <strong>RStudio project</strong> for each data analysis project.</p>
<p>It supports an organized and reproducible workflow, cleanly separated from all other projects that you are working on. Everything you need in one place:</p>
<div style="font-size: 80%">
<ul>
<li>local data files to load into RStudio.</li>
<li>scripts to edit or run in bits or as a whole.</li>
<li>Save your outputs (plots and cleaned data).</li>
</ul>
</div>
<div class="notes">
<p>Source: <a href="https://docs.posit.co/ide/user/ide/get-started/#hello-rstudio-projects" class="uri" target="_blank">https://docs.posit.co/ide/user/ide/get-started/#hello-rstudio-projects</a></p>
</div>
</section>
<section id="file-types" class="level2 sparse-slide">
<h2 class="sparse-slide anchored" data-anchor-id="file-types">File types</h2>
<p>There are many file types, but these are key to an R &amp; RStudio workflow (and likely new to you):</p>
<div style="font-size: 70%">
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th>Extension</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>.Rproj</td>
<td>RStudio project file (keeps project settings).</td>
</tr>
<tr class="even">
<td>.R</td>
<td>R scripts store a sequence of R commands (code) that can be run all at once or line by line.</td>
</tr>
<tr class="odd">
<td>.qmd</td>
<td>Quarto Markdown creates reproducible documents that contain a combination of text, code, and output.</td>
</tr>
<tr class="even">
<td>.Rdata (or sometimes .rda)</td>
<td>These store and load R objects—like data frames.</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="mini-task-2" class="level2 smaller" data-menu-title="Create a RStudio Project">
<h2 class="smaller anchored" data-menu-title="Create a RStudio Project" data-anchor-id="mini-task-2">Mini-task</h2>
<div class="task">
<p><i class="fa-solid fa-check-double" aria-label="check-double"></i> Create a new project in RStudio.</p>
</div>
<div class="incremental">
<ul class="incremental">
<li><p>Click: <span style="color: #3498DB">File &gt; New Project</span>.</p></li>
<li><p>In the New Project wizard that pops up, select: <span style="color: #3498DB">New Directory, then New Project</span>.</p></li>
<li><p>Name the project “<span style="color: #f39c12">SOC6302</span>”</p></li>
<li><p>Click <span style="color: #3498DB">Browse</span> and save the project anywhere <strong>except</strong> your downloads folder.</p></li>
<li><p>Click: <span style="color: #3498DB">Create Project</span>.</p></li>
<li><p>This will launch you into a new RStudio Project inside a new folder called “SOC6302”.</p></li>
</ul>
</div>
</section>
<section id="mini-task-3" class="level2 smaller" data-menu-title="Blank slate">
<h2 class="smaller anchored" data-menu-title="Blank slate" data-anchor-id="mini-task-3">Mini-task</h2>
<div class="task">
<p><i class="fa-solid fa-check-double" aria-label="check-double"></i> Clear the memory at every restart of RStudio.</p>
</div>
<div class="r-stack">
<div style="font-size: 80%">
<p>Turn off theautomatic saving of your workspace and .Rdata files with you quit RStudio. This is important for reproducibility, debugging, and avoiding littering your computer with unnecessary files.</p>
<p><strong>Set this via:</strong></p>
<ol type="1">
<li><span style="color: #3498DB">Tools &gt; Global Options</span>.</li>
<li><span style="color: #3498DB">Uncheck “Restore .RData into Workspace at Startup”</span>.</li>
<li>Choose “<span style="color: #3498DB">Never</span>” on the “Save workspace to .RData on exit”.</li>
<li>Click “<span style="color: #3498DB">Apply</span>” and “<span style="color: #3498DB">OK</span>”.</li>
</ol>
</div>
<p><img src="images/01/blank-slate.png" class="fragment img-fluid" style="width:45.0%" data-fragment-index="1"></p>
</div>
</section>
</section>
<section id="quarto" class="level1 theme-section page-columns page-full">
<h1 class="theme-section">Quarto</h1>
<section id="quarto-1" class="level2">
<h2 class="anchored" data-anchor-id="quarto-1">Quarto</h2>
<p>The tool you’ll use to create reproducible computational documents. Every piece of assignment you hand in will be a Quarto document.</p>
<ul>
<li>Fully reproducible reports</li>
<li>R code + narrative</li>
</ul>
<div class="notes">
<p>You are likely familiar with word processors like MS Word or Google Docs. We will not be using these in this class. Instead, the words you would write in such a document, as well as your R code, will go into a Quarto document. You will <em>render</em> the document (more on what this means later) to get a document out that has your words, code, and the output of that code. Everything in one place, beautifully formatted!</p>
</div>
</section>
<section id="slide28-id" class="level2" data-menu-title="RScript vs Quarto">
<h2 data-menu-title="RScript vs Quarto" class="anchored" data-anchor-id="slide28-id"></h2>
<div class="columns">
<div class="column" style="width:50%;">
<section id="rscript" class="level3">
<h3 class="anchored" data-anchor-id="rscript"><span style="color: #18BC9C;">RScript</span></h3>
<ul>
<li><p>great for learning, exploring and tinkering.</p></li>
<li><p>rerun it without attention to formatting or markdown.</p></li>
</ul>
</section>
</div><div class="column" style="width:50%;">
<section id="quarto-2" class="level3">
<h3 class="anchored" data-anchor-id="quarto-2"><span style="color: #18BC9C;">Quarto</span></h3>
<ul>
<li><p>great for communicating analysis and results</p></li>
<li><p>combines narrative explanation with code output (results).</p></li>
</ul>
</section>
</div>
</div>
</section>
<section id="tour-quarto" class="level2" data-background-image="images/watch.png" data-background-size="100px" data-background-repeat="repeat">
<h2 data-background-image="images/watch.png" data-background-size="100px" data-background-repeat="repeat" class="anchored" data-anchor-id="tour-quarto">Tour: Quarto</h2>
<p><br></p>
<div style="color: #18BC9C; font-size: 300%; font-family: 'Shadows Into Light'">
<p>Sit back and enjoy the show!</p>
</div>
<div class="notes">
<ul>
<li>Use code-along-02 as an example</li>
<li>YAML Ain’t Markup Language</li>
<li>code chunk (+ code comments)</li>
<li>code chunk options</li>
<li>narrative (heading levels)</li>
<li>run (line vs code chunk)</li>
<li>run cells above</li>
<li>source and visual</li>
<li>render</li>
</ul>
</div>
</section>
<section id="tour-recap-quarto" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="tour-recap-quarto">Tour recap: Quarto</h2>
<p><img src="images/01/quarto.png" class="img-fluid"></p>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Source: <a href="https://sta199-f24.github.io/slides/01-meet-the-toolkit-slides.html#/tour-recap-quarto" target="_blank">Dr.&nbsp;Mine Çetinkaya-Rundel</a></p>
</div></div></section>
<section id="tour-recap-quarto-code-chunks" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="tour-recap-quarto-code-chunks">Tour recap: Quarto Code-chunks</h2>
<p><img src="images/01/code-chunks.png" class="img-fluid"></p>
<div style="font-size: 55%">
<ul>
<li><strong>chunk labels</strong> are helpful for describing what the code is doing, for jumping between code cells in the editor, and for troubleshooting</li>
<li><code>message: false</code> hides any messages emitted by the code in your rendered document</li>
</ul>
</div>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Source: <a href="https://sta199-f24.github.io/slides/03-grammar-of-data-transformation-slides.html#/recap-code-cells-aka-code-chunks" target="_blank">Dr.&nbsp;Mine Çetinkaya-Rundel</a></p>
</div></div></section>
<section id="how-will-we-use-quarto" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="how-will-we-use-quarto">How will we use Quarto?</h2>
<ul>
<li>Every <strong>code-along</strong> and <strong>milestone</strong> will be a Quarto document</li>
<li>The scaffolding will decrease over the course</li>
<li>You will create and submit a Quarto document for your <strong>research project</strong></li>
</ul>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p><a href="https://quarto.org/docs/get-started/hello/rstudio.html" target="_blank">Tutorial: Hello, Quarto</a></p>
</div></div></section>
</section>
<section id="your-first-code-along" class="level1" data-menu-title="Code-along 01" data-background-image="images/terminal.png">
<h1 data-menu-title="Code-along 01" data-background-image="images/terminal.png">Your first code-along</h1>
<p><br></p>
<p><a href="https://app.filen.io/#/d/f1fa8fe2-cde9-4849-b294-334627cf095c%234YKTVkuZnb6Jw4BaqKMPhl3EvEMYTU6R" target="_blank"><i class="fa-solid fa-download" aria-label="download"></i> Download code-along-01.qmd</a></p>
<section id="mini-task-4" class="level2 sparse-slide">
<h2 class="sparse-slide anchored" data-anchor-id="mini-task-4">Mini-task</h2>
<div class="task">
<p><i class="fa-solid fa-check-double" aria-label="check-double"></i> Save this code-along in your newly created project folder.</p>
</div>
<p><br></p>
<p>There’s no command in the R console to save scripts or Quarto files— you use the editor’s <span style="color: #3498DB">File</span> &gt; <span style="color: #3498DB">Save As</span> or Ctrl+S.</p>
</section>
</section>
<section id="getting-started" class="level1 theme-section">
<h1 class="theme-section">Getting Started</h1>
<section id="comprehensive-r-archive-network-cran" class="level2 sparse-slide">
<h2 class="sparse-slide anchored" data-anchor-id="comprehensive-r-archive-network-cran">Comprehensive R Archive Network (CRAN)</h2>
<p>CRAN is like an App Store for R. It hosts R packages, documentation, and source code contributed by users worldwide. It is mediated (e.g., quality controlled), making it incredibly reliable.</p>
</section>
<section id="packages" class="level2">
<h2 class="anchored" data-anchor-id="packages">Packages</h2>
<p>R comes with basic tools, but <strong>packages</strong> extend the capabilities of base R (what you already installed). An R package is like a toolbox: a collection of functions, data, and documentation that help you do specific tasks using R.</p>
<p><br></p>
<div style="font-size: 70%">
<p><strong>You’ll install each package (1X per system):</strong></p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' is in use and will not be installed</code></pre>
</div>
</div>
<p><br></p>
<div style="font-size: 70%">
<p><strong>You’ll load each package (every time you use it):</strong></p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="notes">
<p>What’s the difference between installing and loading a package? Why is this annoying workflow a “feature”?</p>
</div>
</section>
<section id="mini-task-5" class="level2" data-menu-title="Install `tidyverse()`">
<h2 data-menu-title="Install `tidyverse()`" class="anchored" data-anchor-id="mini-task-5">Mini-task</h2>
<div class="task">
<p><i class="fa-solid fa-check-double" aria-label="check-double"></i> Install the <code>tidyverse()</code> package, available on CRAN.</p>
</div>
<p><br></p>
<div style="font-size: 80%">
<p><span style="color: #18BC9C; font-family: 'Shadows Into Light'"><strong>Run the code chunk in your code-along.</strong></span></p>
<p><em>OR:</em> Copy and paste the code into your <span style="color: #F39C12;">Console pane</span>. Then hit “Enter”.</p>
</div>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="mini-tasks-1" class="level2" data-menu-title="Install `tinytex()`">
<h2 data-menu-title="Install `tinytex()`" class="anchored" data-anchor-id="mini-tasks-1">Mini-tasks</h2>
<div class="task">
<p><i class="fa-solid fa-check-double" aria-label="check-double"></i> Install the <code>tinytex()</code> package, available on CRAN.</p>
</div>
<p><br></p>
<div style="font-size: 80%">
<p><span style="color: #18BC9C; font-family: 'Shadows Into Light'"><strong>Run the code chunk in your code-along.</strong></span></p>
<p><em>OR:</em> Copy and paste the code into your <span style="color: #F39C12;">Console pane</span>. Then hit “Enter”.</p>
</div>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">'tinytex'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<p>. . .</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>tinytex<span class="sc">::</span><span class="fu">install_tinytex</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="mini-tasks-2" class="level2" data-menu-title="Install `gssr()` and `gssrdoc()`">
<h2 data-menu-title="Install `gssr()` and `gssrdoc()`" class="anchored" data-anchor-id="mini-tasks-2">Mini-tasks</h2>
<div class="task">
<p><i class="fa-solid fa-check-double" aria-label="check-double"></i> Install the <code>gssr()</code> package, NOT on CRAN.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install 'gssr' from 'ropensci' universe</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">'gssr'</span>, <span class="at">repos =</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">'https://kjhealy.r-universe.dev'</span>, <span class="st">'https://cloud.r-project.org'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<p>. . .</p>
<div class="task">
<p><i class="fa-solid fa-check-double" aria-label="check-double"></i> Install the <code>gssrdoc()</code> package, NOT on CRAN.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install 'gssrdoc' from 'ropensci' universe</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">'gssrdoc'</span>, <span class="at">repos =</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">'https://kjhealy.r-universe.dev'</span>, <span class="st">'https://cloud.r-project.org'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-the-packages" class="level2 sparse-slide">
<h2 class="sparse-slide anchored" data-anchor-id="load-the-packages">Load the packages</h2>
<div style="color: #18BC9C; font-size: 80%; font-family: 'Shadows Into Light'">
<p><strong>Run the code chunk in your code-along.</strong></p>
</div>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># for data wrangling</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gssr) <span class="co"># U.S. General Social Survey data</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gssrdoc) <span class="co"># GSS documentation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="environment" class="level2">
<h2 class="anchored" data-anchor-id="environment">Environment</h2>
<div style="color: #18BC9C; font-size: 80%; font-family: 'Shadows Into Light'">
<p><strong>Run the code chunk in your code-along.</strong></p>
</div>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># software documentation</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.5.1 (2025-06-13 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 26100)

Matrix products: default
  LAPACK version 3.12.1

locale:
[1] LC_COLLATE=English_Canada.utf8  LC_CTYPE=English_Canada.utf8   
[3] LC_MONETARY=English_Canada.utf8 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.utf8    

time zone: America/Toronto
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] gssrdoc_0.7.0      conflicted_1.2.0   summarytools_1.1.4 flextable_0.9.9   
 [5] kableExtra_1.4.0   labelled_2.14.1    haven_2.5.5        gssr_0.7          
 [9] lubridate_1.9.4    forcats_1.0.0      stringr_1.5.1      dplyr_1.1.4       
[13] purrr_1.1.0        readr_2.1.5        tidyr_1.3.1        tibble_3.3.0      
[17] ggplot2_3.5.2      tidyverse_2.0.0   

loaded via a namespace (and not attached):
 [1] gtable_0.3.6            xfun_0.52               htmlwidgets_1.6.4      
 [4] tzdb_0.5.0              vctrs_0.6.5             tools_4.5.1            
 [7] generics_0.1.4          curl_6.4.0              pacman_0.5.1           
[10] pkgconfig_2.0.3         checkmate_2.3.2         data.table_1.17.8      
[13] pryr_0.1.6              RColorBrewer_1.1-3      uuid_1.2-1             
[16] lifecycle_1.0.4         compiler_4.5.1          farver_2.1.2           
[19] rapportools_1.2         textshaping_1.0.1       codetools_0.2-20       
[22] fontquiver_0.2.1        fontLiberation_0.1.0    htmltools_0.5.8.1      
[25] yaml_2.3.10             pillar_1.11.0           MASS_7.3-65            
[28] openssl_2.3.3           cachem_1.1.0            magick_2.8.7           
[31] fontBitstreamVera_0.1.1 tidyselect_1.2.1        zip_2.3.3              
[34] digest_0.6.37           stringi_1.8.7           reshape2_1.4.4         
[37] pander_0.6.6            fastmap_1.2.0           grid_4.5.1             
[40] cli_3.6.5               magrittr_2.0.3          base64enc_0.1-3        
[43] withr_3.0.2             backports_1.5.0         gdtools_0.4.2          
[46] scales_1.4.0            timechange_0.3.0        rmarkdown_2.29         
[49] officer_0.6.10          matrixStats_1.5.0       askpass_1.2.1          
[52] ragg_1.4.0              hms_1.1.3               memoise_2.0.1          
[55] evaluate_1.0.4          knitr_1.50              tcltk_4.5.1            
[58] viridisLite_0.4.2       rlang_1.1.6             Rcpp_1.1.0             
[61] glue_1.8.0              xml2_1.3.8              svglite_2.2.1          
[64] rstudioapi_0.17.1       jsonlite_2.0.0          plyr_1.8.9             
[67] R6_2.6.1                systemfonts_1.2.3       fs_1.6.6               </code></pre>
</div>
</div>
</section>
<section id="meet-your-data" class="level2">
<h2 class="anchored" data-anchor-id="meet-your-data">Meet your data</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img src="images/01/meet.png" class="img-fluid"></p>
</div><div class="column" style="width:50%;">
<p>We’re going to use data from the <a href="https://gss.norc.org/us/en/gss/about-the-gss.html" target="_blank">U.S. General Social Survey (GSS)</a>.</p>
</div>
</div>
<div class="notes">
<p>Who know what the GSS is?</p>
</div>
</section>
<section id="load-some-data" class="level2">
<h2 class="anchored" data-anchor-id="load-some-data">Load some data</h2>
<div style="color: #18BC9C; font-size: 80%; font-family: 'Shadows Into Light'">
<p><strong>Run the code chunk in your code-along.</strong></p>
</div>
<div class="cell" data-output-location="fragment">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the data (will appear in your Global Environment pane)</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>gss24 <span class="ot">&lt;-</span> <span class="fu">gss_get_yr</span>(<span class="dv">2024</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Fetching: https://gss.norc.org/documents/stata/2024_stata.zip</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the data named gss24</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>gss24</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,309 × 639
   year       id wrkstat hrs1        hrs2        evwork      marital martype    
   &lt;dbl+l&gt; &lt;dbl&gt; &lt;dbl+l&gt; &lt;dbl+lbl&gt;   &lt;dbl+lbl&gt;   &lt;dbl+lbl&gt;   &lt;dbl+l&gt; &lt;dbl+lbl&gt;  
 1 2024        1 1 [wor…    43       NA(i) [iap] NA(i) [iap] 5 [nev… NA(i) [iap]
 2 2024        2 5 [ret… NA(i) [iap] NA(i) [iap]     1 [yes] 5 [nev… NA(i) [iap]
 3 2024        3 5 [ret… NA(i) [iap] NA(i) [iap]     1 [yes] 1 [mar…     1 [mar…
 4 2024        4 2 [wor…    20       NA(i) [iap] NA(i) [iap] 5 [nev… NA(i) [iap]
 5 2024        5 5 [ret… NA(i) [iap] NA(i) [iap]     1 [yes] 3 [div… NA(i) [iap]
 6 2024        6 4 [une… NA(i) [iap] NA(i) [iap] NA(i) [iap] 1 [mar…     1 [mar…
 7 2024        7 1 [wor…    80       NA(i) [iap] NA(i) [iap] 1 [mar…     1 [mar…
 8 2024        8 6 [in … NA(i) [iap] NA(i) [iap]     1 [yes] 3 [div… NA(i) [iap]
 9 2024        9 1 [wor…    50       NA(i) [iap] NA(i) [iap] 1 [mar… NA(i) [iap]
10 2024       10 4 [une… NA(i) [iap] NA(i) [iap] NA(i) [iap] 5 [nev… NA(i) [iap]
# ℹ 3,299 more rows
# ℹ 631 more variables: divorce &lt;dbl+lbl&gt;, widowed &lt;dbl+lbl&gt;,
#   spwrksta &lt;dbl+lbl&gt;, sphrs1 &lt;dbl+lbl&gt;, sphrs2 &lt;dbl+lbl&gt;, spevwork &lt;dbl+lbl&gt;,
#   cowrksta &lt;dbl+lbl&gt;, coevwork &lt;dbl+lbl&gt;, cohrs1 &lt;dbl+lbl&gt;, cohrs2 &lt;dbl+lbl&gt;,
#   sibs &lt;dbl+lbl&gt;, childs &lt;dbl+lbl&gt;, age &lt;dbl+lbl&gt;, educ &lt;dbl+lbl&gt;,
#   speduc &lt;dbl+lbl&gt;, coeduc &lt;dbl+lbl&gt;, codeg &lt;dbl+lbl&gt;, degree &lt;dbl+lbl&gt;,
#   padeg &lt;dbl+lbl&gt;, madeg &lt;dbl+lbl&gt;, spdeg &lt;dbl+lbl&gt;, sex &lt;dbl+lbl&gt;, …</code></pre>
</div>
</div>
<div class="notes">
<p>A “tibble” is another name for “tidy dataset,” meaning that the data is organized in structured, clear rows and columns. “(75,699 × 6,867)” means the dataset contains 75,699 rows and 6,867 columns. Commonly, in social sciences, rows are referred to as “observations” and columns as “variables.” In our case, there are 75,699 observations (e.g., respondents) and 6,867 variables.</p>
</div>
</section>
<section id="browse-dataframe" class="level2 sparse-slide">
<h2 class="sparse-slide anchored" data-anchor-id="browse-dataframe">Browse dataframe</h2>
<div class="task">
<p><i class="fa-solid fa-check-double" aria-label="check-double"></i> Open the <code>gss24</code> dataframe.</p>
</div>
<p>With your mouse, go to the environment panel (upper-right) and click on the <code>gss24</code> object. It opens in a tab on the source pane.</p>
<p><br></p>
<p>This is often a good idea to browse data to get a first feel for the data, but only if your dataset is relatively small.</p>
<div class="notes">
<p>Each row is an observation (person). Each column in a variable.</p>
</div>
</section>
<section id="section" class="level2" data-menu-title="Why use codebooks">
<h2 data-menu-title="Why use codebooks" class="anchored" data-anchor-id="section"></h2>
<p><img src="images/01/caution.png" class="img-fluid"></p>
<div class="notes">
<p>Author Naomi Wolf wrote a book about the treatment of homosexuality in 19th century England. She reported that it was punishable by death since “sodomy” charges were followed by “death recorded” in the judicial logs. However, “sodomy” referred to a host of other sexual offenses, and “death recorded” specifically means they weren’t killed because their death was recorded but not carried out.</p>
<p>Paul Dolan wrote a book about how marriage makes you miserable. A key part of his evidence was that in the American Time Use Survey, married people surveyed about their happiness when the spouse was present reported being happy, but when the spouse was absent they reported being unhappy. Covering up unhappiness in front of their spouse, truly miserable! But while Dolan read spouse present/absent as “spouse is in the room during questioning”, it actually meant “spouse together/separated.” He was comparing couples that were together vs. couples that were separating!</p>
</div>
</section>
<section id="variable-documentation" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="variable-documentation">Variable documentation</h2>
<p>The <a href="https://gss.norc.org/us/en/gss/get-documentation.html" target="_blank">GSS documentation</a> is available online in .pdf form.</p>
<p>Because we loaded the <code>gssrdoc</code> package, for information about a specific GSS variable:<br>
type <code>?varname</code> at the console.</p>
<p><br></p>
<p>In the output pane, the <code>Help</code> tab will show the variable documentation.</p>
<p><br></p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-hat-wizard" aria-label="hat-wizard"></i> Heads Up!
</div>
</div>
<div class="callout-body-container callout-body">
<p>Replace “varname” with the name of a variable.<br>
Example: <code>?meovrwrk</code></p>
</div>
</div>
</section>
<section id="variable-documentation-example" class="level2">
<h2 class="anchored" data-anchor-id="variable-documentation-example">Variable documentation example</h2>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning in readLines("images/01/meovrwrk.txt"): incomplete final line found on
'images/01/meovrwrk.txt'</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
meovrwrk {gssrdoc}  R Documentation
Men hurt family when focus on work too much
Description
meovrwrk

Details
Question 1297. And, do you agree or disagree: c. Family life often suffers because men concentrate too much on their work.

Overview
For further details see the official GSS documentation.

Counts by year:

year    iap agree   can't choose    disagree    neither agree nor disagree  no answer   strongly agree  strongly disagree   skipped on web  Total
1972    1613    -   -   -   -   -   -   -   -   1613
1973    1504    -   -   -   -   -   -   -   -   1504
1974    1484    -   -   -   -   -   -   -   -   1484
1975    1490    -   -   -   -   -   -   -   -   1490
1976    1499    -   -   -   -   -   -   -   -   1499
1977    1530    -   -   -   -   -   -   -   -   1530
1978    1532    -   -   -   -   -   -   -   -   1532
1980    1468    -   -   -   -   -   -   -   -   1468
1982    1860    -   -   -   -   -   -   -   -   1860
1983    1599    -   -   -   -   -   -   -   -   1599
1984    1473    -   -   -   -   -   -   -   -   1473
1985    1534    -   -   -   -   -   -   -   -   1534
1986    1470    -   -   -   -   -   -   -   -   1470
1987    1819    -   -   -   -   -   -   -   -   1819
1988    1481    -   -   -   -   -   -   -   -   1481
1989    1537    -   -   -   -   -   -   -   -   1537
1990    1372    -   -   -   -   -   -   -   -   1372
1991    1517    -   -   -   -   -   -   -   -   1517
1993    1606    -   -   -   -   -   -   -   -   1606
1994    1545    695 33  243 286 27  122 41  -   2992
1996    1444    825 16  198 169 1   230 21  -   2904
1998    2832    -   -   -   -   -   -   -   -   2832
2000    940 877 43  361 331 22  209 34  -   2817
2002    1857    415 6   264 108 -   99  16  -   2765
2004    1906    460 4   188 135 -   94  25  -   2812
2006    2518    945 14  477 304 1   208 43  -   4510
2008    694 653 12  310 161 -   143 50  -   2023
2010    614 662 6   388 192 3   122 57  -   2044
2012    672 558 11  382 170 -   130 51  -   1974
2014    863 702 7   479 234 1   176 76  -   2538
2016    979 819 9   536 257 -   171 96  -   2867
2018    789 644 11  475 220 2   134 73  -   2348
2021    1315    886 1   487 1001    -   202 138 2   4032
2022    1168    885 15  537 618 1   201 117 2   3544
2024    1126    787 19  481 611 -   195 89  1   3309
Total   50650   10813   207 5806    4797    58  2436    927 5   75699
Values
1 strongly agree

2 agree

3 neither agree nor disagree

4 disagree

5 strongly disagree

NA(d) can't choose

NA(i) iap

NA(j) I don't have a job

NA(m) dk, na, iap

NA(n) no answer

NA(p) not imputable

NA(r) refused

NA(s) skipped on web

NA(u) uncodeable

NA(x) not available in this release

NA(y) not available in this year

NA(z) see codebook

Source
General Social Survey https://gss.norc.org

[Package gssrdoc version 0.7.0 Index]</code></pre>
</div>
</div>
<div class="notes">
<p>Variable name: meovrwrk<br>
Variable label: Men hurt family when focus on work too much<br>
1994 was the first year of the survey.<br>
695 respondents agreed with the statement.<br>
iap – missing. Values: the numeric and response category key (1 = strongly agree)</p>
</div>
</section>
<section id="variables" class="level2">
<h2 class="anchored" data-anchor-id="variables">Variables</h2>
<p>You can access the variables (i.e., columns) using the <code>$</code> operator, as shown using the <code>table()</code> function. The variable names are case sensitive.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(gss24<span class="sc">$</span>meovrwrk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3   4   5 
195 787 611 481  89 </code></pre>
</div>
</div>
<div class="task">
<p><i class="fa-solid fa-lightbulb" aria-label="lightbulb"></i> 195 respondents were coded as <code>1</code> on this variable. What does that mean?</p>
</div>
</section>
<section id="mini-tasks-3" class="level2" data-menu-title="Variables: Practice">
<h2 data-menu-title="Variables: Practice" class="anchored" data-anchor-id="mini-tasks-3">Mini-tasks</h2>
<div class="task">
<p><i class="fa-solid fa-check-double" aria-label="check-double"></i> Change the code to show the variable <code>fefam</code>.</p>
</div>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace meovrwrk with fefam</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(gss24<span class="sc">$</span>meovrwrk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3   4   5 
195 787 611 481  89 </code></pre>
</div>
</div>
<p>. . .</p>
<div class="task">
<p><i class="fa-solid fa-check-double" aria-label="check-double"></i> add text to your code-along that interprets the results for the <code>2</code> value for <code>fefam</code>.</p>
</div>
</section>
<section id="quarto-render" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="quarto-render">Quarto: Render</h2>
<p>Finally, let’s <code>render</code> your code-along-01 and see the results!</p>
<p><img src="images/01/quarto.png" class="img-fluid" style="width:200.0%"></p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<i class="fa-solid fa-hat-wizard" aria-label="hat-wizard"></i> Heads Up!
</div>
</div>
<div class="callout-body-container callout-body">
<p>Click the down arrow next to <code>render</code> to choose whether to preview within RStudio’s Viewer Pane or in your browser.</p>
</div>
</div>
</section>
</section>
<section id="support" class="level1" data-background-image="images/file-video-solid.png" data-background-size="100px" data-background-repeat="repeat">
<h1 data-background-image="images/file-video-solid.png" data-background-size="100px" data-background-repeat="repeat">Support</h1>
<p>Some help videos and further explanation:</p>
<p><a href="https://youtu.be/opy-v0WAHXM" target="_blank">R - Intro RStudio Interface</a></p>
<p><a href="https://youtu.be/K9-zDmq737I" target="_blank">EasyR - Getting started with R the easy way</a></p>
<div class="notes">
<p>Milestone 01: Can’t complete until next week. Instead, work on the IPUMS section of MS01!</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>