---
title: "SOC6302 Punch List"
format: html
editor: visual
---

# Tutorials

## all:

-   change practice call to css workflow
-   change to use {.sparse-slide} for lectures 1-3
-   change pngs to table and ggplots where possible
-   integrate R code into tutorials
-   all have practice questions
-   consistent (not?) allow-retry for Learning Checks
-   update all examples where possible

## 01

**ADD for MAC Users**: Download and install this:
<https://www.xquartz.org/>

## 03

-   can't make allow_skip: false because exercise in `median` section
    doesn't evaluate as being completed.
-   milestone 01 includes gss_which_years. Did I teach that in lecture
    01 or 02?

## 04

-   add in R code exercises?
-   re-do many equations/tables/figures in R without png

## 06

-   Run crosstabs in R with updated data instead of .pngs

## 08

-   "Reporting significance" sub-section from Class 09
-   class 05 -- interpreting tables

# Lectures

-   add a 'variables' slide to lectures 01-04
-   move current callout tip workflow to css for clearer syntax
-   run all lectures through stylr for consistent grammar
-   make lightbulb part of task callout in scss

## 03

-   didn't make it through all the slides (stopped at slide 29) Okay in
    future probably. Maybe do "Think like a statistician" as a review in
    weeks 1 of 2 at the beginning of weeks 1 (for each Milestone set)?

-   remove slides 7 and 8 (`gss_which_years`)

-   fix checkpoint 07 (in Milestone 01) for consistency of which dataset
    (`gss24` or `gss_all`)

## 04

-   add `select()` to Data Management II because it's about changing
    dataframes, not variables.

# Memos

-   

# Other

-   where to put all the joke images from the labs?
