---
title: "SOC6302 Reading Schedule (F26)"
author: "Joanna R. Pepin"
---

# Week 01 - Introduction

Wheelan, Charles. 2014. “What’s the Point?” Pp. 1–14 in *Naked
Statistics: Stripping the Dread from the Data*. New York: W. W. Norton &
Company.

Gandy, Oscar H. Jr. 2008. “Being a Statistician Means Never Having to
Say You’re Certain.” Pp. 295–306 in *White Logic, White Methods: Racism
and Methodology*, edited by T. Zuberi and E. Bonilla-Silva. Lanham:
Rowman & Littlefield Publishers.

# Week 02 - Descriptive Statistics

Wheelan, Charles. 2014. “Descriptive Statistics: Who Was the Best
Baseball Player of All Time?” Pp. 15–35 in *Naked Statistics: Stripping
the Dread from the Data*. New York: W. W. Norton & Company.

Wickham, Hadley, Mine Cetinkaya-Rundel, and Garrett Grolemund. 2023.
“[Data Transformation](https://r4ds.hadley.nz/data-transform.html).” in
*R for Data Science: Import, Tidy, Transform, Visualize, and Model
Data*. Beijing Boston Farnham Sebastopol Tokyo: O’Reilly Media.

# Week 03 - Sampling

Wheelan, Charles. 2014. “The Central Limit Theorem.” Pp. 127–42 in
*Naked Statistics: Stripping the Dread from the Data*. New York: W. W.
Norton & Company.

# Week 04 - Uncertainty

Wheelan, Charles. 2014. “Inference: Why My Statistics Professor Thought
I Might Have Cheated.” Pp. 143–56 in *Naked Statistics: Stripping the
Dread from the Data.* New York: W. W. Norton & Company.

Wheelan, Charles. 2014. “Polling: How We Know That 64 Percent of
Americans Support the Death Penalty.” Pp. 169–79 in *Naked Statistics:
Stripping the Dread from the Data.* New York: W. W. Norton & Company.

# Week 05 - Associations

Cohen, Philip N. 2025. “Doing Description.” Pp. 43–79 in *Citizen
Scholar: Public Engagement for Social Scientists*. New York: Columbia
University Press.

Wasserstein, Ronald L., and Nicole A. Lazar. 2016. “The ASA’s Statement
on p-Values: Context, Process, and Purpose.” The American Statistician
70(2):129–33. doi:10.1080/00031305.2016.1154108.

# Week 06

No readings -- midterm exam

# Week 07 - Research Brief Workshop

WATCH: [ggplot for plots and graphs](https://www.youtube.com/watch?v=HPJn1CMvtmI)

WATCH: [Visualize your data using ggplot (skip the ad in the middle)](https://www.youtube.com/watch?v=rfR9Nrpfnyg&list=PLtL57Fdbwb_C6RS0JtBojTNOMVlgpeJkS&index=10)

# Week 08 - Presenting Data

Cairo, Alberto. 2019. “Charts That Lie by Being Poorly Designed.” Pp.
53–80 in *How Charts Lie: Getting Smarter about Visual Information*. New
York: W. W. Norton & Company.

Gagnon, Francis. 2021. “500,000 Dots Is Too Many.”
<https://chezvoila.com/blog/500k/>.

# Week 09 - Bivariate Regression

Wheelan, Charles. 2014. “Regression Analysis: The Miracle Elixir.” Pp. 185–211 in *Naked Statistics: Stripping the Dread from the Data*. New York: W. W. Norton & Company.  

# Week 10 - OLS Multiple Regression I

Allison, Paul D. 1999. “Chapter 1: What Is Multiple Regression.” Pp. 1–24 in *Multiple Regression: A Primer*. Thousand Oaks, Calif: Pine Forge Press.

# Week 11 - OLS Multiple Regression II

*TBD*

# Week 12 - Flash Presentations

No readings.
