---
title: "Intro to Data Analysis"
format: 
  revealjs:
    controls: true
    theme: [default, custom.scss]
    slide-number: c
revealjs-plugins:
  - quiz
embed-resources: true
filters:
    - openlinksinnewpage
editor: 
  markdown: 
    wrap: 72
---


```{r warning = FALSE, error = FALSE, message = FALSE}
# Loading libraries
library(tidyverse)
library(gghighlight)
library(webexercises)


# Define color palette
c_palette <- c("#3498DB",
               "#E74C3C",
               "#18BC9C",
               "#F39C12")

```

#  {data-menu-title="Agenda" background-image="images/calendar.png" background-size="100px" background-repeat="repeat"}

:::::: columns
::: {.column width="50%"}
<h3>Topics</h3>

-   Intro. to Data Analysis
-   Frequency??
:::

:::: {.column width="50%"}
<h3>Terms</h3>

::: {style="font-size: 80%; color: #3498DB"}
DESCRIPTIVE STATISTICS\
INFERENTIAL STATISTICS\
TIDY DATA\
VARIABLES NOMINAL\
ORDINAL\
INTERVAL-RATIO\
DICHOTOMOUS\
CODEBOOK
:::
::::
::::::

# Introduction to Data Analysis {.theme-section}

##  {#slide4-id data-menu-title="Descriptive vs Inferential"}  

::: callout-tip
## DESCRIPTIVE STATISTICS

Procedures that help us organize and describe data collected from a sample or population.
:::

<br>

::: callout-tip
## INFERENTIAL STATISTICS

Making underlying predictions or inferences about a population using observations and analyses from a sample.
:::


##  {#slide5-id data-menu-title="Practice"}

::: {style="font-size: 150%; color: #F39C12"}
{{< fa clipboard-question >}} PRACTICE
:::

<br>

## Quiz question goes here {.quiz-question background-image="images/clipboard-question.png" background-size="100px" background-repeat="repeat"}

- Option 1
- [Option 2 which is correct]{.correct}
- Option 3
- Option 4

