```{r data type, echo = FALSE, results = "hide"}

pacman::p_load(
  tidyverse,
  gssr, # load U.S. gss data
  gssrdoc, # load the gss codebook
  haven, # work with labeled data
  labelled, # use labels as values
  summarytools, # easy descriptive statistics
  knitr, # pretty tables
  kableExtra, # centered tables
  conflicted # declare primary packages
)

## Address important conflicts
conflict_prefer("is.labelled", "haven")
conflict_prefer("filter", "dplyr")
conflict_scout() # Identify the conflicts

## Load the gss dataset
gss24 <- gss_get_yr(2024) # 2024 survey respondents

```

Question
========
What is the result of the following code?

```{r output, eval = FALSE, results = "asis"}
#| message: false

gss24 |>  
  filter(age > 20) |> 
  select(age, childs)

```

Answerlist
----------

-   Only rows with `age` > 20 and columns `age` and `childs` are returned.

-   A new column is added to `gss24`

-   rows with `age` > 20 are removed

-   The original gss24 dataset is overwritten.

Meta-information
================
exname: skew 
extype: schoice 
exsolution: 1000 
exshuffle: 4
