```{r data type, echo = FALSE, results = "hide"}

pacman::p_load(
  tidyverse,
  gssr, # load U.S. gss data
  gssrdoc, # load the gss codebook
  haven, # work with labeled data
  labelled, # use labels as values
  summarytools, # easy descriptive statistics
  knitr, # pretty tables
  kableExtra, # centered tables
  conflicted # declare primary packages
)

## Address important conflicts
conflict_prefer("is.labelled", "haven")
conflict_prefer("filter", "dplyr")
conflict_scout() # Identify the conflicts

## Load the gss dataset
gss24 <- gss_get_yr(2024) # 2024 survey respondents

```

Question
========
A researcher summarized the `sibs` variable from the U.S. General Social Survey, a measure of how many brothers and sisters respondents had. Based on the summary table, the distribution appears to be:

```{r output, echo = FALSE, results = "asis", fig.pos='H'}
#| message: false

cat("\\begin{samepage}\n")
gss24 |>  
  drop_na(sibs) |> 
  dplyr::summarize(
    freq = n(), 
    median = round(median(sibs), digits = 2), 
    mean = round(mean(sibs), digits = 2),
    sd = round(sd(sibs), digits = 2)
    ) |>
  kable(format = "latex", booktabs = TRUE, longtable = FALSE) |>
  kable_styling(latex_options = c("hold_position"), position = "center")
cat("\\end{samepage}\n")

```

Answerlist
----------

-   negatively skewed

-   positively skewed

-   symmetrical

-   nominal

Meta-information
================
exname: skew 
extype: schoice 
exsolution: 1000 
exshuffle: 4
