---
title: "Milestone 03"
author: "FirstName LastName"
format: pdf # or replace 'pdf' with 'typst'
execute:
  error: true # change this to false when your assignment is complete.
---

# Environment

Update the YAML with your first and last name.

Load the packages.

```{r}
#| label: load
#| message: false

library(here)
library(tidyverse) 
library(haven) 
library(gssr)
library(gssrdoc)
library(summarytools)
```

Load the 2024 GSS data and the GSS panel data

```{r}
#| label: gss-data
#| message: false

# ADD YOUR CODE HERE TO LOAD THE GSS 2024 DATA 
gss22 <- gss_get_yr(2022)


```

You’ll be working with the following GSS variables:

-   `tvhours`: Hours spent watching TV per day
-   `hrs`: 
-   `sex`: Respondent’s gender


Is there a gender difference (`sex`) in agreement that men hurt the family when they focus on work too much?

```{r}
#| message: false
#| eval: false # change this!
#| label: tbl-cross-meovrwrk

my_data |>
  tbl_cross(
    row = meovrwrk,
    col = sex,
    percent = "column",
    missing = "no") |>
  add_p(source_note = TRUE)
```