<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Code-Along 01</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d4be639c637f3db3c684c66cefad7e0c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Code-Along 01</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="packages" class="level2">
<h2 class="anchored" data-anchor-id="packages">Packages</h2>
<p>We’ll use the following packages:</p>
<ul>
<li><code>here()</code> (relative file paths)</li>
<li><code>tidyverse()</code> (data wrangling)</li>
<li><code>gssr()</code> (U.S. General Social Survey data)</li>
<li><code>gssrdoc()</code> (GSS documentation)</li>
</ul>
</section>
<section id="install-here-and-tidyverse" class="level2">
<h2 class="anchored" data-anchor-id="install-here-and-tidyverse">Install <code>here()</code> and <code>tidyverse()</code></h2>
<p>Let’s first install the two packages that are available on CRAN.</p>
<p>Copy and paste the following code into your Console pane. Then hit enter.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"here"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, do the same to install the tidyverse package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="install-gssr-and-gssrdoc" class="level2">
<h2 class="anchored" data-anchor-id="install-gssr-and-gssrdoc">Install <code>gssr()</code> and <code>gssrdoc()</code></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install 'gssr' from 'ropensci' universe</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">'gssr'</span>, <span class="at">repos =</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">'https://kjhealy.r-universe.dev'</span>, <span class="st">'https://cloud.r-project.org'</span>))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Also recommended: install 'gssrdoc' as well</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">'gssrdoc'</span>, <span class="at">repos =</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="st">'https://kjhealy.r-universe.dev'</span>, <span class="st">'https://cloud.r-project.org'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-the-packages" class="level2">
<h2 class="anchored" data-anchor-id="load-the-packages">Load the packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at C:/Users/Joanna/Documents/GitHub/Stats for Sociologists</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gssr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Package loaded. To attach the GSS data, type data(gss_all) at the console.
For the panel data and documentation, type e.g. data(gss_panel08_long) and data(gss_panel_doc).
For help on a specific GSS variable, type ?varname at the console.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gssrdoc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="environment" class="level2">
<h2 class="anchored" data-anchor-id="environment">Environment</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># software documentation</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.5.1 (2025-06-13 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 26100)

Matrix products: default
  LAPACK version 3.12.1

locale:
[1] LC_COLLATE=English_Canada.utf8  LC_CTYPE=English_Canada.utf8   
[3] LC_MONETARY=English_Canada.utf8 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.utf8    

time zone: America/Toronto
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] gssrdoc_0.7.0   gssr_0.7        lubridate_1.9.4 forcats_1.0.0  
 [5] stringr_1.5.1   dplyr_1.1.4     purrr_1.0.4     readr_2.1.5    
 [9] tidyr_1.3.1     tibble_3.3.0    ggplot2_3.5.2   tidyverse_2.0.0
[13] here_1.0.1     

loaded via a namespace (and not attached):
 [1] gtable_0.3.6       jsonlite_2.0.0     compiler_4.5.1     tidyselect_1.2.1  
 [5] scales_1.4.0       yaml_2.3.10        fastmap_1.2.0      R6_2.6.1          
 [9] generics_0.1.4     curl_6.3.0         knitr_1.50         htmlwidgets_1.6.4 
[13] rprojroot_2.0.4    pillar_1.10.2      RColorBrewer_1.1-3 tzdb_0.5.0        
[17] rlang_1.1.6        stringi_1.8.7      xfun_0.52          fs_1.6.6          
[21] timechange_0.3.0   cli_3.6.5          withr_3.0.2        magrittr_2.0.3    
[25] digest_0.6.37      grid_4.5.1         rstudioapi_0.17.1  haven_2.5.5       
[29] hms_1.1.3          lifecycle_1.0.4    vctrs_0.6.5        evaluate_1.0.4    
[33] glue_1.8.0         farver_2.1.2       rmarkdown_2.29     tools_4.5.1       
[37] pkgconfig_2.0.3    htmltools_0.5.8.1 </code></pre>
</div>
</div>
</section>
<section id="project-structure" class="level2">
<h2 class="anchored" data-anchor-id="project-structure">Project structure</h2>
<p>Let’s set up your project structure using the <code>here()</code> package.</p>
<p>First, let’s establish our project directory.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set the file path to the root of the project</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">here</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "C:/Users/Joanna/Documents/GitHub/Stats for Sociologists"</code></pre>
</div>
</div>
<p>Next, we’ll create folders within our project using <code>here()</code> and <code>dir.create()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create base folders</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="fu">here</span>(<span class="st">"data"</span>), <span class="at">recursive =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in dir.create(here("data"), recursive = TRUE):
'C:\Users\Joanna\Documents\GitHub\Stats for Sociologists\data' already exists</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="fu">here</span>(<span class="st">"code-alongs"</span>), <span class="at">recursive =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in dir.create(here("code-alongs"), recursive = TRUE):
'C:\Users\Joanna\Documents\GitHub\Stats for Sociologists\code-alongs' already
exists</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="fu">here</span>(<span class="st">"milestones"</span>), <span class="at">recursive =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in dir.create(here("milestones"), recursive = TRUE):
'C:\Users\Joanna\Documents\GitHub\Stats for Sociologists\milestones' already
exists</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="fu">here</span>(<span class="st">"project"</span>), <span class="at">recursive =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in dir.create(here("project"), recursive = TRUE):
'C:\Users\Joanna\Documents\GitHub\Stats for Sociologists\project' already
exists</code></pre>
</div>
</div>
<p>Now, we’ll create sub-folders using <code>here()</code> and <code>dir.create()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create project sub-folders</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="fu">here</span>(<span class="st">"project"</span>, <span class="st">"data"</span>), <span class="at">recursive =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in dir.create(here("project", "data"), recursive = TRUE):
'C:\Users\Joanna\Documents\GitHub\Stats for Sociologists\project\data' already
exists</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="fu">here</span>(<span class="st">"project"</span>, <span class="st">"scripts"</span>), <span class="at">recursive =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in dir.create(here("project", "scripts"), recursive = TRUE):
'C:\Users\Joanna\Documents\GitHub\Stats for Sociologists\project\scripts'
already exists</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="fu">here</span>(<span class="st">"project"</span>, <span class="st">"outputs"</span>), <span class="at">recursive =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in dir.create(here("project", "outputs"), recursive = TRUE):
'C:\Users\Joanna\Documents\GitHub\Stats for Sociologists\project\outputs'
already exists</code></pre>
</div>
</div>
<p>Check your work by reporting a list of folders and or files in the R-project folders and sub-folder.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Your SOC6302 class folder</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">list.files</span>(<span class="at">path =</span> <span class="fu">here</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "_extensions"                  "_quarto-speaker.yml"         
 [3] "_quarto.yml"                  "code-alongs"                 
 [5] "data"                         "docs"                        
 [7] "labs"                         "lectures"                    
 [9] "milestones"                   "project"                     
[11] "SOC6302_readings.qmd"         "SOC6302_syllabus.qmd"        
[13] "Stats for Sociologists.Rproj"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Your "Project" sub-folder</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">list.files</span>(<span class="at">path =</span> <span class="fu">here</span>(<span class="st">"project"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data"    "outputs" "scripts"</code></pre>
</div>
</div>
</section>
<section id="save-code-along" class="level2">
<h2 class="anchored" data-anchor-id="save-code-along">Save code-along</h2>
<p>Save this code-along in your newly created “code-along” sub-folder.</p>
<p>There’s no command in the R console to save scripts or Quarto files — you use the editor’s <span style="color: #3498DB">File</span> &gt; <span style="color: #3498DB">Save As</span> or Ctrl+S.</p>
</section>
<section id="meet-your-data" class="level2">
<h2 class="anchored" data-anchor-id="meet-your-data">Meet your data</h2>
<p>We’re going to use data from the <a href="https://gss.norc.org/us/en/gss/about-the-gss.html">U.S. General Social Survey (GSS)</a>.</p>
<p>Let’s load your data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the data (will appear in your Global Environment pane)</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(gss_all)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the datatable which is automatically named gss_all</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>gss_all</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 75,699 × 6,867
   year         id wrkstat    hrs1        hrs2        evwork      occ   prestige
   &lt;dbl+lbl&gt; &lt;dbl&gt; &lt;dbl+lbl&gt;  &lt;dbl+lbl&gt;   &lt;dbl+lbl&gt;   &lt;dbl+lbl&gt;   &lt;dbl&gt; &lt;dbl+lb&gt;
 1 1972          1 1 [workin… NA(i) [iap] NA(i) [iap] NA(i) [iap] 205   50      
 2 1972          2 5 [retire… NA(i) [iap] NA(i) [iap]     1 [yes] 441   45      
 3 1972          3 2 [workin… NA(i) [iap] NA(i) [iap] NA(i) [iap] 270   44      
 4 1972          4 1 [workin… NA(i) [iap] NA(i) [iap] NA(i) [iap]   1   57      
 5 1972          5 7 [keepin… NA(i) [iap] NA(i) [iap]     1 [yes] 385   40      
 6 1972          6 1 [workin… NA(i) [iap] NA(i) [iap] NA(i) [iap] 281   49      
 7 1972          7 1 [workin… NA(i) [iap] NA(i) [iap] NA(i) [iap] 522   41      
 8 1972          8 1 [workin… NA(i) [iap] NA(i) [iap] NA(i) [iap] 314   36      
 9 1972          9 2 [workin… NA(i) [iap] NA(i) [iap] NA(i) [iap] 912   26      
10 1972         10 1 [workin… NA(i) [iap] NA(i) [iap] NA(i) [iap] 984   18      
# ℹ 75,689 more rows
# ℹ 6,859 more variables: wrkslf &lt;dbl+lbl&gt;, wrkgovt &lt;dbl+lbl&gt;,
#   commute &lt;dbl+lbl&gt;, industry &lt;dbl+lbl&gt;, occ80 &lt;dbl+lbl&gt;, prestg80 &lt;dbl+lbl&gt;,
#   indus80 &lt;dbl+lbl&gt;, indus07 &lt;dbl+lbl&gt;, occonet &lt;dbl+lbl&gt;, found &lt;dbl+lbl&gt;,
#   occ10 &lt;dbl+lbl&gt;, occindv &lt;dbl+lbl&gt;, occstatus &lt;dbl+lbl&gt;, occtag &lt;dbl+lbl&gt;,
#   prestg10 &lt;dbl+lbl&gt;, prestg105plus &lt;dbl+lbl&gt;, indus10 &lt;dbl+lbl&gt;,
#   indstatus &lt;dbl+lbl&gt;, indtag &lt;dbl+lbl&gt;, marital &lt;dbl+lbl&gt;, …</code></pre>
</div>
</div>
<p>A “tibble” is another name for “tidy dataset,” meaning that the data is organized in structured, clear rows and columns. “(75,699 × 6,867)” means the dataset contains 75,699 rows and 6,867 columns. Commonly, in social sciences, rows are referred to as “observations” and columns as “variables.” In our case, there are 75,699 observations (e.g., respondents) and 6,867 variables.</p>
<p>You can also load the GSS data for a specific survey year.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the data only for the 2024 survey respondents</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>gss24 <span class="ot">&lt;-</span> <span class="fu">gss_get_yr</span>(<span class="dv">2024</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Fetching: https://gss.norc.org/documents/stata/2024_stata.zip</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># look at the first 6 rows of the dataframe</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(gss24)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 639
  year        id wrkstat hrs1        hrs2        evwork      marital martype    
  &lt;dbl+lb&gt; &lt;dbl&gt; &lt;dbl+l&gt; &lt;dbl+lbl&gt;   &lt;dbl+lbl&gt;   &lt;dbl+lbl&gt;   &lt;dbl+l&gt; &lt;dbl+lbl&gt;  
1 2024         1 1 [wor…    43       NA(i) [iap] NA(i) [iap] 5 [nev… NA(i) [iap]
2 2024         2 5 [ret… NA(i) [iap] NA(i) [iap]     1 [yes] 5 [nev… NA(i) [iap]
3 2024         3 5 [ret… NA(i) [iap] NA(i) [iap]     1 [yes] 1 [mar…     1 [mar…
4 2024         4 2 [wor…    20       NA(i) [iap] NA(i) [iap] 5 [nev… NA(i) [iap]
5 2024         5 5 [ret… NA(i) [iap] NA(i) [iap]     1 [yes] 3 [div… NA(i) [iap]
6 2024         6 4 [une… NA(i) [iap] NA(i) [iap] NA(i) [iap] 1 [mar…     1 [mar…
# ℹ 631 more variables: divorce &lt;dbl+lbl&gt;, widowed &lt;dbl+lbl&gt;,
#   spwrksta &lt;dbl+lbl&gt;, sphrs1 &lt;dbl+lbl&gt;, sphrs2 &lt;dbl+lbl&gt;, spevwork &lt;dbl+lbl&gt;,
#   cowrksta &lt;dbl+lbl&gt;, coevwork &lt;dbl+lbl&gt;, cohrs1 &lt;dbl+lbl&gt;, cohrs2 &lt;dbl+lbl&gt;,
#   sibs &lt;dbl+lbl&gt;, childs &lt;dbl+lbl&gt;, age &lt;dbl+lbl&gt;, educ &lt;dbl+lbl&gt;,
#   speduc &lt;dbl+lbl&gt;, coeduc &lt;dbl+lbl&gt;, codeg &lt;dbl+lbl&gt;, degree &lt;dbl+lbl&gt;,
#   padeg &lt;dbl+lbl&gt;, madeg &lt;dbl+lbl&gt;, spdeg &lt;dbl+lbl&gt;, sex &lt;dbl+lbl&gt;,
#   race &lt;dbl+lbl&gt;, res16 &lt;dbl+lbl&gt;, reg16 &lt;dbl+lbl&gt;, mobile16 &lt;dbl+lbl&gt;, …</code></pre>
</div>
</div>
<p>With your mouse, go to the environment panel (upper-right) and click on the “gss24” object. It pops up and you can browse through it.</p>
<p>This is often a good idea to get a first feel for the data, but only if your dataset is relatively small.</p>
<p>The <a href="https://gss.norc.org/us/en/gss/get-documentation.html">GSS documentation</a> is available online in .pdf form.</p>
<p>The .pdfs will be useful for general overviews.</p>
<p>For specific variable information, it will be helpful to use the documentation you’ll load into RStudio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the codebook</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(gss_dict)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To see the variables available in the dataset, use the <code>names()</code> command. This command is best to use with smaller datasets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(gss_all)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   [1] "year"            "id"              "wrkstat"         "hrs1"           
   [5] "hrs2"            "evwork"          "occ"             "prestige"       
   [9] "wrkslf"          "wrkgovt"         "commute"         "industry"       
  [13] "occ80"           "prestg80"        "indus80"         "indus07"        
  [17] "occonet"         "found"           "occ10"           "occindv"        
  [21] "occstatus"       "occtag"          "prestg10"        "prestg105plus"  
  [25] "indus10"         "indstatus"       "indtag"          "marital"        
  [29] "martype"         "agewed"          "divorce"         "widowed"        
  [33] "spwrksta"        "sphrs1"          "sphrs2"          "spevwork"       
  [37] "cowrksta"        "cowrkslf"        "coevwork"        "cohrs1"         
  [41] "cohrs2"          "spocc"           "sppres"          "spwrkslf"       
  [45] "spind"           "spocc80"         "sppres80"        "spind80"        
  [49] "spocc10"         "spoccindv"       "spoccstatus"     "spocctag"       
  [53] "sppres10"        "sppres105plus"   "spind10"         "spindstatus"    
  [57] "spindtag"        "coocc10"         "coind10"         "paocc16"        
  [61] "papres16"        "pawrkslf"        "paind16"         "paocc80"        
  [65] "papres80"        "paind80"         "paocc10"         "paoccindv"      
  [69] "paoccstatus"     "paocctag"        "papres10"        "papres105plus"  
  [73] "paind10"         "paindstatus"     "paindtag"        "maocc80"        
  [77] "mapres80"        "mawrkslf"        "maind80"         "maocc10"        
  [81] "maoccindv"       "maoccstatus"     "maocctag"        "mapres10"       
  [85] "mapres105plus"   "maind10"         "maindstatus"     "maindtag"       
  [89] "sibs"            "childs"          "age"             "agekdbrn"       
  [93] "educ"            "paeduc"          "maeduc"          "speduc"         
  [97] "coeduc"          "codeg"           "degree"          "padeg"          
 [101] "madeg"           "spdeg"           "major1"          "major2"         
 [105] "dipged"          "spdipged"        "codipged"        "cosector"       
 [109] "whenhs"          "whencol"         "sector"          "eftotlt"        
 [113] "barate"          "gradtounder"     "voedcol"         "voednme1"       
 [117] "voedncol"        "voednme2"        "spsector"        "speftotlt"      
 [121] "spbarate"        "spgradtounder"   "cobarate"        "cogradtounder"  
 [125] "coeftotlt"       "sex"             "race"            "res16"          
 [129] "reg16"           "mobile16"        "family16"        "famdif16"       
 [133] "mawork"          "mawkbaby"        "mawkborn"        "mawk16"         
 [137] "mawrkgrw"        "incom16"         "born"            "parborn"        
 [141] "granborn"        "hompop"          "babies"          "preteen"        
 [145] "teens"           "adults"          "unrelat"         "earnrs"         
 [149] "income"          "rincome"         "income72"        "income77"       
 [153] "rincom77"        "income82"        "rincom82"        "income86"       
 [157] "rincom86"        "income91"        "rincom91"        "income98"       
 [161] "rincom98"        "income06"        "rincom06"        "income16"       
 [165] "rincom16"        "region"          "xnorcsiz"        "srcbelt"        
 [169] "size"            "dotdata"         "dotpeop"         "dotthng"        
 [173] "dotged"          "dotsvp"          "dotpres"         "spdotdat"       
 [177] "spdotpeo"        "spdotthn"        "spdotged"        "spdotsvp"       
 [181] "spdotpre"        "padotdat"        "padotpeo"        "padotthn"       
 [185] "padotged"        "padotsvp"        "padotpre"        "partyid"        
 [189] "vote68"          "pres68"          "if68who"         "vote72"         
 [193] "pres72"          "if72who"         "vote76"          "pres76"         
 [197] "if76who"         "vote80"          "pres80"          "if80who"        
 [201] "vote84"          "pres84"          "if84who"         "vote88"         
 [205] "pres88"          "if88who"         "vote92"          "pres92"         
 [209] "if92who"         "vote96"          "pres96"          "if96who"        
 [213] "vote00"          "pres00"          "if00who"         "vote04"         
 [217] "pres04"          "if04who"         "vote08"          "pres08"         
 [221] "if08who"         "vote12"          "pres12"          "if12who"        
 [225] "vote16"          "pres16"          "if16who"         "polviews"       
 [229] "polviewy"        "polviewx"        "natspac"         "natenvir"       
 [233] "natheal"         "natcity"         "natcrime"        "natdrug"        
 [237] "nateduc"         "natrace"         "natarms"         "nataid"         
 [241] "natfare"         "natroad"         "natsoc"          "natmass"        
 [245] "natpark"         "natchld"         "natsci"          "natenrgy"       
 [249] "natspacy"        "natenviy"        "nathealy"        "natcityy"       
 [253] "natcrimy"        "natdrugy"        "nateducy"        "natracey"       
 [257] "natarmsy"        "nataidy"         "natfarey"        "natspacz"       
 [261] "natenviz"        "nathealz"        "natcityz"        "natcrimz"       
 [265] "natdrugz"        "nateducz"        "natracez"        "natarmsz"       
 [269] "nataidz"         "natfarez"        "natroadz"        "natsocz"        
 [273] "natmassz"        "natparkz"        "equal1"          "equal2"         
 [277] "equal3"          "equal4"          "equal5"          "equal6"         
 [281] "equal7"          "equal8"          "usclass1"        "usclass2"       
 [285] "usclass3"        "usclass4"        "usclass5"        "usclass6"       
 [289] "usclass7"        "usclass8"        "educop"          "govcare"        
 [293] "eqwlth"          "eqwlthy"         "tax"             "spkath"         
 [297] "colath"          "libath"          "spksoc"          "colsoc"         
 [301] "libsoc"          "spkrac"          "colrac"          "librac"         
 [305] "spkcom"          "colcom"          "libcom"          "spkmil"         
 [309] "colmil"          "libmil"          "spkhomo"         "colhomo"        
 [313] "libhomo"         "spkmslm"         "colmslm"         "libmslm"        
 [317] "cappun2"         "cappun"          "capimp"          "capinfo"        
 [321] "capfirm"         "gunlaw"          "gunimp"          "guninfo"        
 [325] "gunfirm"         "courts"          "courtsy"         "crimimp"        
 [329] "criminfo"        "crimfirm"        "lawimp"          "lawinfo"        
 [333] "lawfirm"         "wirtap"          "grass"           "grassy"         
 [337] "relig"           "denom"           "other"           "othjew"         
 [341] "jew"             "jewaj"           "fund"            "attend"         
 [345] "maattend"        "paattend"        "spattend"        "reliten"        
 [349] "relitena"        "postlife"        "postlf1"         "postlf2"        
 [353] "postlf3"         "postlf4"         "postlf5"         "postlf6"        
 [357] "postlf7"         "postlf8"         "postlf9"         "postlf10"       
 [361] "likediff"        "mindbody"        "restact"         "palefull"       
 [365] "pray"            "dejavu"          "esp"             "visions"        
 [369] "spirits"         "grace"           "neargod"         "judge"          
 [373] "redeemer"        "lover"           "master"          "mother"         
 [377] "creator"         "father"          "spouse"          "friend"         
 [381] "king"            "liberatr"        "healer"          "mapa"           
 [385] "mastersp"        "judgeluv"        "frndking"        "crtrheal"       
 [389] "rdeemlib"        "popespks"        "relig16"         "denom16"        
 [393] "oth16"           "othjew16"        "jew16"           "jew16aj"        
 [397] "fund16"          "sprel"           "spden"           "spother"        
 [401] "spothjew"        "spjew"           "spjewaj"         "spfund"         
 [405] "sprel16"         "spden16"         "spoth16"         "spjew16"        
 [409] "spfund16"        "corel"           "coden"           "coother"        
 [413] "cojew"           "cofund"          "tithing"         "prayer"         
 [417] "prayery"         "prayerx"         "bible"           "bibley"         
 [421] "world1"          "world2"          "world3"          "world4"         
 [425] "world5"          "world6"          "world7"          "libtemp"        
 [429] "contemp"         "prottemp"        "cathtemp"        "jewtemp"        
 [433] "mslmtemp"        "fepriest"        "feclergy"        "relgrade"       
 [437] "racmar"          "racmar10"        "racdin"          "racpush"        
 [441] "racseg"          "racopen"         "raclive"         "racclos"        
 [445] "racdis"          "racinteg"        "racobjct"        "rachome"        
 [449] "racschol"        "racfew"          "rachaf"          "racmost"        
 [453] "busing"          "busing10"        "racpres"         "racjob"         
 [457] "racchurh"        "color"           "racname"         "rachisch"       
 [461] "racmix"          "racneigh"        "racnobuy"        "ractrust"       
 [465] "racparty"        "racocc"          "racinc"          "racopnow"       
 [469] "racopwil"        "racimp"          "racinfo"         "racfirm"        
 [473] "raccare"         "racthink"        "racwrite"        "racgive"        
 [477] "racjoin"         "affrmact"        "wrkwayup"        "blksimp"        
 [481] "closeblk"        "closewht"        "alienat1"        "alienat2"       
 [485] "alienat3"        "alienat4"        "alienat5"        "alienat6"       
 [489] "happy"           "hapmar"          "hapcohab"        "health"         
 [493] "life"            "helpful"         "fair"            "trust"          
 [497] "trusty"          "trust1"          "satcity"         "sathobby"       
 [501] "satfam"          "satfrnd"         "sathealt"        "confinan"       
 [505] "conbus"          "conclerg"        "coneduc"         "confed"         
 [509] "conlabor"        "conpress"        "conmedic"        "contv"          
 [513] "conjudge"        "consci"          "conlegis"        "conarmy"        
 [517] "confinay"        "conbusy"         "conclery"        "coneducy"       
 [521] "confedy"         "conlaboy"        "conpresy"        "conmediy"       
 [525] "contvy"          "conjudgy"        "consciy"         "conlegiy"       
 [529] "conarmyy"        "manners"         "success"         "honest"         
 [533] "clean"           "judgment"        "control"         "role"           
 [537] "amicable"        "obeys"           "responsi"        "consider"       
 [541] "interest"        "studious"        "mannersy"        "successy"       
 [545] "honesty"         "cleany"          "judgmeny"        "controly"       
 [549] "roley"           "amicably"        "obeysy"          "responsy"       
 [553] "considey"        "interesy"        "studiouy"        "mannersz"       
 [557] "successz"        "honestz"         "cleanz"          "judgmenz"       
 [561] "controlz"        "rolez"           "amicablz"        "obeysz"         
 [565] "responsz"        "considez"        "interesz"        "studiouz"       
 [569] "obey"            "popular"         "thnkself"        "workhard"       
 [573] "helpoth"         "chldsex"         "chldsex1"        "youngen"        
 [577] "socrel"          "socommun"        "socfrend"        "socbar"         
 [581] "socpars"         "socsibs"         "aged"            "agedpar"        
 [585] "agedchld"        "weekswrk"        "partfull"        "drink"          
 [589] "drunk"           "smoke"           "quitsmk"         "smokecig"       
 [593] "cigweek"         "evsmoke"         "anomia1"         "anomia2"        
 [597] "anomia3"         "anomia4"         "anomia5"         "anomia6"        
 [601] "anomia7"         "anomia8"         "anomia9"         "joblose"        
 [605] "jobfind"         "satjob"          "satjobhv"        "richwork"       
 [609] "jobinc"          "jobsec"          "jobhour"         "jobpromo"       
 [613] "jobmeans"        "jobkeep"         "jobpay"          "jobrise"        
 [617] "jobhonor"        "joboff"          "jobinter"        "jobindep"       
 [621] "jobresp"         "jobpeop"         "jobhelp"         "jobsoc"         
 [625] "jobaccmp"        "jobsafe"         "class"           "classy"         
 [629] "rank"            "rank10"          "satfin"          "finalter"       
 [633] "finrela"         "incneed"         "mininc"          "wksub"          
 [637] "wksubs"          "wksub1"          "wksubs1"         "wksup"          
 [641] "wksups"          "wksup1"          "wksups1"         "unemp"          
 [645] "govaid"          "getaid"          "union"           "union1"         
 [649] "getahead"        "parsol"          "kidssol"         "fehome"         
 [653] "fework"          "fepres"          "fepol"           "fepoly"         
 [657] "feimp"           "feinfo"          "fefirm"          "fecare"         
 [661] "fethink"         "fewrite"         "fegive"          "fejoin"         
 [665] "abdefect"        "abnomore"        "abhlth"          "abpoor"         
 [669] "abrape"          "absingle"        "abany"           "aborct"         
 [673] "abpro1"          "abpro2"          "abpro3"          "abcon1"         
 [677] "abcon2"          "abcon3"          "abimp"           "abinfo"         
 [681] "abfirm"          "abcare"          "chldidel"        "chldmore"       
 [685] "chldnum"         "chldsoon"        "pill"            "teenpill"       
 [689] "pillok"          "sexeduc"         "divlaw"          "divlawy"        
 [693] "spdue"           "sppaid"          "premarsx"        "teensex"        
 [697] "xmarsex"         "homosex"         "homochng"        "porninf"        
 [701] "pornmorl"        "pornrape"        "pornout"         "pornlaw"        
 [705] "xmovie"          "xmovie1"         "pornimp"         "porninfo"       
 [709] "pornfirm"        "spanking"        "letdie1"         "letdie2"        
 [713] "suicide1"        "suicide2"        "suicide3"        "suicide4"       
 [717] "suinum"          "suinum1"         "suirel1"         "suineg1"        
 [721] "suiclse1"        "suitime1"        "suimths1"        "suiyrs1"        
 [725] "suirel2"         "suineg2"         "suiclse2"        "suitime2"       
 [729] "suimths2"        "suiyrs2"         "strike"          "civright"       
 [733] "antiwar"         "prowar"          "school"          "hit"            
 [737] "hitage"          "hitnum"          "gun"             "gunage"         
 [741] "gunnum"          "hitok"           "hitmarch"        "hitdrunk"       
 [745] "hitchild"        "hitbeatr"        "hitrobbr"        "polhitok"       
 [749] "polabuse"        "polmurdr"        "polescap"        "polattak"       
 [753] "fear"            "fearhome"        "burglr"          "robbry"         
 [757] "owngun"          "pistol"          "shotgun"         "rifle"          
 [761] "rowngun"         "ticket"          "arrest"          "convictd"       
 [765] "lockedup"        "hunt"            "hunt1"           "huntothr"       
 [769] "news"            "tvhours"         "radiohrs"        "phone"          
 [773] "coop2"           "coop"            "comprend"        "form"           
 [777] "random"          "abspno"          "abhave1"         "abhave2"        
 [781] "abhave3"         "ablegal"         "fechld"          "fehelp"         
 [785] "fepresch"        "fefam"           "eraread"         "erameans"       
 [789] "era"             "eratell"         "erawhy1"         "erawhy2"        
 [793] "erawhy3"         "eraimp"          "erainfo"         "erafirm"        
 [797] "febear"          "feworkif"        "racsubs"         "racsubgv"       
 [801] "racmarel"        "racmarpr"        "racsups"         "racteach"       
 [805] "racavoid"        "racchng"         "racquit"         "racdif1"        
 [809] "racdif2"         "racdif3"         "racdif4"         "salfergt"       
 [813] "sallabor"        "salsatfn"        "salabort"        "salsci"         
 [817] "divorce5"        "divrel1"         "divrel4"         "unemp5"         
 [821] "unrel1"          "unrel4"          "hosdis5"         "hosrel1"        
 [825] "hosrel4"         "death5"          "death16"         "padeath"        
 [829] "madeath"         "chlddth"         "sibdeath"        "spdeath"        
 [833] "trauma1"         "trauma5"         "trarel1"         "trarel5"        
 [837] "tratot1"         "tratot5"         "defspdr"         "defspdfg"       
 [841] "hlpminr"         "hlpminfg"        "cutspdr"         "cutspdfg"       
 [845] "impfam"          "impwork"         "imprelax"        "impfrend"       
 [849] "impkin"          "impchurh"        "imppol"          "privacy"        
 [853] "civic"           "rushed"          "bored"           "stresswk"       
 [857] "pollgood"        "polltrue"        "feserve"         "meserve"        
 [861] "taxserve"        "milqual"         "milpay"          "fenumok"        
 [865] "hinumok"         "blnumok"         "hinumoky"        "blnumoky"       
 [869] "milvolok"        "fightair"        "mechanic"        "nurse"          
 [873] "typist"          "brass"           "fightlnd"        "transair"       
 [877] "gunner"          "fightsea"        "fefight"         "fedirty"        
 [881] "febrass"         "fehlpmil"        "draft"           "draftfe"        
 [885] "draftem"         "draftfem"        "draftcol"        "draftmar"       
 [889] "draftpar"        "draftgay"        "draftco"         "draftdef"       
 [893] "vetfam"          "vetfamnw"        "minmilop"        "femilop"        
 [897] "copunish"        "cojail"          "milokme"         "milokfe"        
 [901] "upgrade"         "jobtrain"        "nukewar"         "landwar"        
 [905] "morenuke"        "lessnuke"        "nonuke"          "guerilla"       
 [909] "vetaid"          "defwrkev"        "defwrknw"        "milwrkev"       
 [913] "milwrknw"        "resdefwk"        "obvote"          "obvol"          
 [917] "objury"          "ob911"           "obeng"           "obknow"         
 [921] "obmepax"         "obmewar"         "obfepax"         "obfewar"        
 [925] "helppoor"        "helpnot"         "helpsick"        "helpblk"        
 [929] "numgiven"        "eqclose"         "rclose1"         "rclose2"        
 [933] "rclose3"         "rclose4"         "rclose5"         "close12"        
 [937] "close13"         "close14"         "close15"         "close23"        
 [941] "close24"         "close25"         "close34"         "close35"        
 [945] "close45"         "sex1"            "sex2"            "sex3"           
 [949] "sex4"            "sex5"            "race1"           "race2"          
 [953] "race3"           "race4"           "race5"           "spouse1"        
 [957] "spouse2"         "spouse3"         "spouse4"         "spouse5"        
 [961] "parent1"         "parent2"         "parent3"         "parent4"        
 [965] "parent5"         "sibling1"        "sibling2"        "sibling3"       
 [969] "sibling4"        "sibling5"        "child1"          "child2"         
 [973] "child3"          "child4"          "child5"          "othfam1"        
 [977] "othfam2"         "othfam3"         "othfam4"         "othfam5"        
 [981] "cowork1"         "cowork2"         "cowork3"         "cowork4"        
 [985] "cowork5"         "memgrp1"         "memgrp2"         "memgrp3"        
 [989] "memgrp4"         "memgrp5"         "neighbr1"        "neighbr2"       
 [993] "neighbr3"        "neighbr4"        "neighbr5"        "friend1"        
 [997] "friend2"         "friend3"         "friend4"         "friend5"        
[1001] "advisor1"        "advisor2"        "advisor3"        "advisor4"       
[1005] "advisor5"        "other1"          "other2"          "other3"         
[1009] "other4"          "other5"          "talkto1"         "talkto2"        
[1013] "talkto3"         "talkto4"         "talkto5"         "known1"         
[1017] "known2"          "known3"          "known4"          "known5"         
[1021] "educ1"           "educ2"           "educ3"           "educ4"          
[1025] "educ5"           "age1"            "age2"            "age3"           
[1029] "age4"            "age5"            "relig1"          "relig2"         
[1033] "relig3"          "relig4"          "relig5"          "partyid1"       
[1037] "partyid2"        "partyid3"        "talkpol1"        "talkpol2"       
[1041] "talkpol3"        "talkpol"         "frndknow"        "memfrat"        
[1045] "memserv"         "memvet"          "mempolit"        "memunion"       
[1049] "memsport"        "memyouth"        "memschl"         "memhobby"       
[1053] "memgreek"        "memnat"          "memfarm"         "memlit"         
[1057] "memprof"         "memchurh"        "memother"        "memnum"         
[1061] "solfrat"         "solserv"         "solvet"          "solpolit"       
[1065] "solunion"        "solsport"        "solyouth"        "solschl"        
[1069] "solhobby"        "solgreek"        "solnat"          "solfarm"        
[1073] "sollit"          "solprof"         "solchurh"        "solother"       
[1077] "actfrat"         "actserv"         "actvet"          "actpolit"       
[1081] "actunion"        "actsport"        "actyouth"        "actschl"        
[1085] "acthobby"        "actgreek"        "actnat"          "actfarm"        
[1089] "actlit"          "actprof"         "actchurh"        "actother"       
[1093] "churhgrp"        "mostact"         "caregrp"         "servegrp"       
[1097] "leadgrp"         "givegrp"         "attndgrp"        "writegrp"       
[1101] "lobbygrp"        "loclived"        "loctrust"        "locinflu"       
[1105] "locprob"         "locgrp"          "loccare"         "intpol"         
[1109] "swayvote"        "workpol"         "polrally"        "loclobby"       
[1113] "locself"         "othlobby"        "othself"         "governor"       
[1117] "usrep"           "schlhead"        "fedtrust"        "locvote"        
[1121] "gavepol"         "blkinflu"        "blkgains"        "feinflu"        
[1125] "fegains"         "scisolve"        "scichng"         "scipry"         
[1129] "scimoral"        "switched"        "switch1"         "switch2"        
[1133] "switch3"         "switnum"         "switage1"        "switage2"       
[1137] "switwhy1"        "switwhy2"        "marelig"         "maden"          
[1141] "maoth"           "majew"           "mafund"          "parelig"        
[1145] "paden"           "paoth"           "pajew"           "pafund"         
[1149] "churhsch"        "sunsch16"        "grace16"         "join16"         
[1153] "lapsed"          "churhmem"        "churhact"        "tvrelig"        
[1157] "god"             "reborn"          "savesoul"        "saygrace"       
[1161] "readword"        "punsin"          "blkwhite"        "rotapple"       
[1165] "permoral"        "decbible"        "decoths"         "decchurh"       
[1169] "decself"         "gochurch"        "believe"         "follow"         
[1173] "goownway"        "myfaith"         "madatgod"        "doubts1"        
[1177] "doubts2"         "doubts3"         "doubts4"         "faith1"         
[1181] "faith2"          "faith3"          "faith4"          "frndcon1"       
[1185] "frndcon2"        "frndcon3"        "frndcon4"        "frndcon5"       
[1189] "frndrel1"        "frndrel2"        "frndrel3"        "frndrel4"       
[1193] "frndrel5"        "frndden1"        "frndden2"        "frndden3"       
[1197] "frndden4"        "frndden5"        "frndoth1"        "frndoth2"       
[1201] "frndoth3"        "frndoth4"        "frndoth5"        "frndfnd1"       
[1205] "frndfnd2"        "frndfnd3"        "frndfnd4"        "frndfnd5"       
[1209] "frndrac1"        "frndrac2"        "frndrac3"        "frndrac4"       
[1213] "frndrac5"        "friends"         "numfrend"        "numbwfrd"       
[1217] "bwfriend"        "godsells"        "godsport"        "givecong"       
[1221] "giverel"         "giveoth"         "givearts"        "relhrs1"        
[1225] "relhrs2"         "numcong"         "kid5up"          "pubsch"         
[1229] "homesch"         "cathsch"         "chrissch"        "denomsch"       
[1233] "relsch"          "privsch"         "othsch"          "shoprel"        
[1237] "shopmove"        "shopnum"         "othchrch"        "implives"       
[1241] "obeytch"         "preach"          "ferespct"        "sympcoun"       
[1245] "wrkyoung"        "worship"         "ownthing"        "talkback"       
[1249] "twoclass"        "openmind"        "whypoor1"        "whypoor2"       
[1253] "whypoor3"        "whypoor4"        "socdif1"         "socdif2"        
[1257] "socdif3"         "socdif4"         "wlthwhts"        "wlthjews"       
[1261] "wlthblks"        "wlthasns"        "wlthhsps"        "wlthso"         
[1265] "workwhts"        "workjews"        "workblks"        "workasns"       
[1269] "workhsps"        "workso"          "violwhts"        "violjews"       
[1273] "violblks"        "violasns"        "violhsps"        "violso"         
[1277] "intlwhts"        "intljews"        "intlblks"        "intlasns"       
[1281] "intlhsps"        "intlso"          "farewhts"        "farejews"       
[1285] "fareblks"        "fareasns"        "farehsps"        "fareso"         
[1289] "patrwhts"        "patrjews"        "patrblks"        "patrasns"       
[1293] "patrhsps"        "patrso"          "livejews"        "liveblks"       
[1297] "liveasns"        "livehsps"        "liveno"          "liveso"         
[1301] "livewhts"        "marjew"          "marblk"          "marasian"       
[1305] "marhisp"         "marno"           "marso"           "marwht"         
[1309] "workfare"        "lessfare"        "povzone"         "povschs"        
[1313] "povcol"          "blkzone"         "blkschs"         "blkcol"         
[1317] "racquota"        "influwht"        "influjew"        "influblk"       
[1321] "influasn"        "influhsp"        "influso"         "hspjobs"        
[1325] "blkjobs"         "asnjobs"         "hsphouse"        "blkhouse"       
[1329] "asnhouse"        "racwork"         "affact"          "discaff"        
[1333] "discwhy1"        "discwhy2"        "discwhy3"        "discwhy4"       
[1337] "discwhy5"        "discwhy6"        "genejob"         "genehire"       
[1341] "genecanx"        "genecany"        "genegets"        "profits1"       
[1345] "profits2"        "unpower"         "unprog"          "outofbiz"       
[1349] "merged"          "reorg"           "orgfin"          "wrkyears"       
[1353] "evunemp"         "numunemp"        "totunemp"        "empyears"       
[1357] "fndjob1"         "fndjob2"         "fndjob3"         "fndjob4"        
[1361] "fndjob5"         "fndjob6"         "fndjob7"         "fndjob8"        
[1365] "fndjob9"         "intltest"        "skiltest"        "drugtest"       
[1369] "physical"        "ltrsref"         "samejob"         "jobyears"       
[1373] "thisjob1"        "thisjob2"        "thisjob3"        "thisjob4"       
[1377] "thisjob5"        "thisjob6"        "thisjob7"        "promotng"       
[1381] "promoted"        "numpromo"        "imppromo"        "futpromo"       
[1385] "sexpromo"        "racpromo"        "advances"        "jobcntrl"       
[1389] "wrkindep"        "lottosay"        "idecide"         "automatn"       
[1393] "monitred"        "offsup"          "yousup"          "spwksup"        
[1397] "supothrs"        "levels"          "totsup"          "supduty1"       
[1401] "supduty2"        "supduty3"        "supduty4"        "supduty5"       
[1405] "supduty6"        "supduty7"        "othduty1"        "othduty2"       
[1409] "othduty3"        "othduty4"        "othduty5"        "othduty6"       
[1413] "othduty7"        "orgmoney"        "totmoney"        "youmoney"       
[1417] "jobjudge"        "quantity"        "quality"         "wrkwell"        
[1421] "wrkmuch"         "imatter"         "helporg"         "notloyal"       
[1425] "stayorg1"        "samevals"        "proudorg"        "stayorg2"       
[1429] "noticed"         "chngeorg"        "othpay"          "raiseall"       
[1433] "raisehrd"        "raisefav"        "fringe1"         "fringe2"        
[1437] "fringe3"         "fringe4"         "fringe5"         "fringe6"        
[1441] "fringe7"         "fringe8"         "fringe9"         "fringe10"       
[1445] "fringe11"        "jobvshme"        "unvote"          "unmanrel"       
[1449] "cowrkrel"        "schoolng"        "training"        "learning"       
[1453] "exptrain"        "wherewrk"        "findout"         "baseofop"       
[1457] "splocnum"        "standup"         "selfirst"        "richpoor"       
[1461] "opoutcme"        "united"          "obtohelp"        "lfegod"         
[1465] "lfegenes"        "lfesocty"        "lfehrdwk"        "lfechnce"       
[1469] "bigband"         "blugrass"        "country"         "blues"          
[1473] "musicals"        "classicl"        "folk"            "gospel"         
[1477] "jazz"            "latin"           "moodeasy"        "newage"         
[1481] "opera"           "rap"             "reggae"          "conrock"        
[1485] "oldies"          "hvymetal"        "attsprts"        "visitart"       
[1489] "makeart"         "autorace"        "camping"         "garden"         
[1493] "dance"           "gomusic"         "huntfish"        "perform"        
[1497] "dosports"        "seemovie"        "usevcr"          "plymusic"       
[1501] "tvshows"         "tvnews"          "tvpbs"           "judgeart"       
[1505] "trstprof"        "classics"        "grtbooks"        "modpaint"       
[1509] "english"         "pclit"           "excelart"        "hosthome"       
[1513] "frdcreat"        "frdcultr"        "frddynam"        "frdfun"         
[1517] "frdhonst"        "frdintel"        "frdresp"         "impfinan"       
[1521] "impmar"          "impkids"         "impgod"          "impthngs"       
[1525] "impcultr"        "impjob"          "impself"         "mostimp1"       
[1529] "mostimp2"        "mostimp3"        "mostimp4"        "colmajr1"       
[1533] "colmajr2"        "hsclass1"        "hsclass2"        "malive1"        
[1537] "mayrborn"        "mayrdied"        "palive1"         "payrborn"       
[1541] "payrdied"        "datesch"         "neverwk"         "occfirst"       
[1545] "presfrst"        "wrkslfst"        "indfirst"        "datefrst"       
[1549] "alike1"          "alike2"          "alike3"          "alike4"         
[1553] "alike5"          "alike6"          "alike7"          "alike8"         
[1557] "marnum"          "fstspyr"         "fstspedc"        "fstspdeg"       
[1561] "fstspped"        "fstspmed"        "agewedcr"        "spyrborn"       
[1565] "spmarnum"        "spfam16"         "sppaeduc"        "spmaeduc"       
[1569] "sphedocc"        "sphedpre"        "sphedslf"        "sphedind"       
[1573] "sphedocc10"      "sphedoccindv"    "sphedoccstatus"  "sphedocctag"    
[1577] "sphedind10"      "sphedindstatus"  "sphedindtag"     "sphedpre10"     
[1581] "sphedpre105plus" "spsibs"          "kdsex1"          "kdsex2"         
[1585] "kdsex3"          "kdsex4"          "kdsex5"          "kdsex6"         
[1589] "kdsex7"          "kdsex8"          "kdsex9"          "kdyrbrn1"       
[1593] "kdyrbrn2"        "kdyrbrn3"        "kdyrbrn4"        "kdyrbrn5"       
[1597] "kdyrbrn6"        "kdyrbrn7"        "kdyrbrn8"        "kdyrbrn9"       
[1601] "kdrel1"          "kdrel2"          "kdrel3"          "kdrel4"         
[1605] "kdrel5"          "kdrel6"          "kdrel7"          "kdrel8"         
[1609] "kdrel9"          "kdalive1"        "kdalive2"        "kdalive3"       
[1613] "kdalive4"        "kdalive5"        "kdalive6"        "kdalive7"       
[1617] "kdalive8"        "kdalive9"        "kdeduc1"         "kdeduc2"        
[1621] "kdeduc3"         "kdeduc4"         "kdeduc5"         "kdeduc6"        
[1625] "kdeduc7"         "kdeduc8"         "kdeduc9"         "kdpicked"       
[1629] "kdwork1"         "kdwork2"         "kdevwork"        "kdocc80"        
[1633] "kdpres80"        "kdwrkslf"        "kdind80"         "kdocc10"        
[1637] "kdoccindv"       "kdoccstatus"     "kdocctag"        "kdind10"        
[1641] "kdindstatus"     "kdindtag"        "kdpres10"        "kdpres105plus"  
[1645] "sbsex1"          "sbsex2"          "sbsex3"          "sbsex4"         
[1649] "sbsex5"          "sbsex6"          "sbsex7"          "sbsex8"         
[1653] "sbsex9"          "sbyrbrn1"        "sbyrbrn2"        "sbyrbrn3"       
[1657] "sbyrbrn4"        "sbyrbrn5"        "sbyrbrn6"        "sbyrbrn7"       
[1661] "sbyrbrn8"        "sbyrbrn9"        "sbrel1"          "sbrel2"         
[1665] "sbrel3"          "sbrel4"          "sbrel5"          "sbrel6"         
[1669] "sbrel7"          "sbrel8"          "sbrel9"          "sbalive1"       
[1673] "sbalive2"        "sbalive3"        "sbalive4"        "sbalive5"       
[1677] "sbalive6"        "sbalive7"        "sbalive8"        "sbalive9"       
[1681] "sbpicked"        "sbeduc"          "sbdeg"           "sbwork1"        
[1685] "sbwork2"         "sbevwork"        "sbocc80"         "sbpres80"       
[1689] "sbwrkslf"        "sbind80"         "sbocc10"         "sboccindv"      
[1693] "sboccstatus"     "sbocctag"        "sbind10"         "sbindstatus"    
[1697] "sbindtag"        "sbpres10"        "sbpres105plus"   "ethid"          
[1701] "amissue"         "ethissue"        "ethid1"          "amissue1"       
[1705] "ethissu1"        "amrank"          "amproud"         "meltpot"        
[1709] "gvtapart"        "gvtmelt"         "ethorgs"         "ethspkok"       
[1713] "ethspkno"        "symptblk"        "admirblk"        "bilinged"       
[1717] "engteach"        "engballt"        "engoffcl"        "letin"          
[1721] "hspasn10"        "immecon"         "immunemp"        "immunite"       
[1725] "immfare"         "undocwrk"        "undoccol"        "undockid"       
[1729] "immpush"         "immwrkup"        "colaff"          "colaffy"        
[1733] "discaffy"        "jobaff"          "owneth"          "congeth"        
[1737] "teacheth"        "schleth"         "ethhist"         "whoteach"       
[1741] "whtgovt"         "blkgovt"         "hspgovt"         "asngovt"        
[1745] "wlthimm"         "wlthundc"        "workimm"         "workundc"       
[1749] "obrespct"        "econpast"        "pastup"          "pastdown"       
[1753] "econfutr"        "futrup"          "futrdown"        "rdiscaff"       
[1757] "rimmdisc"        "romance"         "livewith"        "haprom"         
[1761] "willwed1"        "willwed2"        "hapgirls"        "hapboys"        
[1765] "fejobaff"        "tradmod"         "sharesep"        "emoteoth"       
[1769] "rhmewrk"         "sphmewrk"        "fairhwrk"        "earnmore"       
[1773] "famlife"         "worklife"        "balwkfam"        "refpromo"       
[1777] "refmorwk"        "refxhour"        "workless"        "noathome"       
[1781] "nonurse"         "nohmewrk"        "discaffm"        "discaffw"       
[1785] "flextime"        "parleave"        "menben"          "womenben"       
[1789] "chldben"         "allben"          "nooneben"        "menhrt"         
[1793] "womenhrt"        "chldhrt"         "allhrt"          "noonehrt"       
[1797] "feless1"         "feless2"         "feless3"         "fekids1"        
[1801] "fekids2"         "fekids3"         "fekids4"         "fekids5"        
[1805] "mebear"          "fehire"          "feminist"        "fenews"         
[1809] "hmemaker"        "wrkclass"        "manprof"         "men"            
[1813] "children"        "yourself"        "shakeblu"        "calm"           
[1817] "outraged"        "hapfeel"         "sad"             "ashamed"        
[1821] "excited"         "lonely"          "fearful"         "ovrjoyed"       
[1825] "worried"         "contentd"        "anxious"         "restless"       
[1829] "madat"           "atease"          "angry"           "embarrss"       
[1833] "proud"           "noplan"          "badbrks"         "mostluck"       
[1837] "litcntrl"        "showangr"        "showfeel"        "noemote"        
[1841] "notupset"        "beplesnt"        "notworry"        "angrywrk"       
[1845] "angryfam"        "angrygvt"        "angrywhy"        "angryev"        
[1849] "whnangry"        "madat1"          "madat2"          "madat3"         
[1853] "madat4"          "madat5"          "madat6"          "madat7"         
[1857] "madat8"          "madat9"          "madat10"         "madat11"        
[1861] "madat12"         "madat13"         "madat14"         "madat15"        
[1865] "madat16"         "madat17"         "madat18"         "madat19"        
[1869] "madat20"         "madat21"         "madat22"         "madat23"        
[1873] "howangry"        "angrlast"        "thnkangr"        "chnang1"        
[1877] "chnang2"         "chnang3"         "chnang4"         "chnang5"        
[1881] "chnang6"         "chnang7"         "chnang8"         "chnang9"        
[1885] "chnang10"        "chnang11"        "chnang12"        "chnang13"       
[1889] "chnang14"        "chnang15"        "chnang16"        "reactok"        
[1893] "othresp"         "selfresp"        "likeoth"         "amimp"          
[1897] "notam"           "usworry"         "ussat"           "usfrustr"       
[1901] "usenthus"        "usangry"         "ushopefl"        "usupset"        
[1905] "carprivt"        "relprivt"        "warrntyc"        "cardealr"       
[1909] "newused"         "typdealr"        "carbuya"         "carbuyb"        
[1913] "carbuyc"         "carbuyd"         "carbuye"         "carbuyf"        
[1917] "carbuyg"         "carbuy1"         "reldealr"        "satcar"         
[1921] "evbuyhme"        "homeyear"        "learnhme"        "newowned"       
[1925] "relhome"         "whosold"         "realtora"        "realtorb"       
[1929] "realtorc"        "realtord"        "realtore"        "realtorf"       
[1933] "realtor1"        "relagent"        "warrntyh"        "sathome"        
[1937] "lawyer"          "lawyera"         "lawyerb"         "lawyerc"        
[1941] "lawyerd"         "lawyere"         "lawyerf"         "lawyerg"        
[1945] "lawyer1"         "rellaw"          "satlawyr"        "fixhome"        
[1949] "fixera"          "fixerb"          "fixerc"          "fixerd"         
[1953] "fixere"          "fixerf"          "fixer1"          "relfixer"       
[1957] "satfixes"        "borrowed"        "wholoand"        "sellbed"        
[1961] "sellauto"        "sellhome"        "transoth"        "loaned"         
[1965] "loanedto"        "buybed"          "buyauto"         "buylaw"         
[1969] "buyfixes"        "buyhome"         "transrel"        "frnddeal"       
[1973] "frndawk"         "tablprce"        "organsb"         "organsw"        
[1977] "sellorgn"        "adoption"        "sellbaby"        "sellsex"        
[1981] "reqinfo"         "natrecon"        "tagsales"        "haggle"         
[1985] "wkfambiz"        "hrfambiz"        "fambiz"          "econsys"        
[1989] "famfinan"        "decauto"         "decbed"          "decgift"        
[1993] "layoffs"         "volhlth"         "voleduc"         "volrelig"       
[1997] "volhuman"        "volenvir"        "volpub"          "volrec"         
[2001] "volart"          "volwork"         "volpol"          "volyouth"       
[2005] "volfound"        "volintl"         "volinfrm"        "voloth"         
[2009] "monhlth"         "moneduc"         "monrelig"        "monhuman"       
[2013] "monenvir"        "monpub"          "monrec"          "monart"         
[2017] "monwork"         "monpol"          "monyouth"        "monfound"       
[2021] "monintl"         "moninfrm"        "monoth"          "hrshlth"        
[2025] "hrseduc"         "hrsrelig"        "hrshuman"        "hrsenvir"       
[2029] "hrspub"          "hrsrec"          "hrsart"          "hrswork"        
[2033] "hrspol"          "hrsyouth"        "hrsfound"        "hrsintl"        
[2037] "hrsinfrm"        "hrsoth"          "givhlth"         "giveduc"        
[2041] "givrelig"        "givhuman"        "givenvir"        "givpub"         
[2045] "givrec"          "givart"          "givwork"         "givpol"         
[2049] "givyouth"        "givfound"        "givintl"         "givinfrm"       
[2053] "givoth"          "tothlth"         "toteduc"         "totrelig"       
[2057] "tothuman"        "totenvir"        "totpub"          "totrec"         
[2061] "totart"          "totwork"         "totpol"          "totyouth"       
[2065] "totfound"        "totintl"         "totinfrm"        "tototh"         
[2069] "valhlth"         "valeduc"         "valrelig"        "valhuman"       
[2073] "valenvir"        "valpub"          "valrec"          "valart"         
[2077] "valwork"         "valpol"          "valyouth"        "valfound"       
[2081] "valintl"         "valinfrm"        "valoth"          "homeless"       
[2085] "needynei"        "needyrel"        "needyfrd"        "needyoth"       
[2089] "probfix1"        "probfix2"        "probfix3"        "probhlp1"       
[2093] "probhlp2"        "probhlp3"        "vigversn"        "seriousp"       
[2097] "charactr"        "imbalnce"        "wayraise"        "stresses"       
[2101] "genetics"        "godswill"        "upsdowns"        "breakdwn"       
[2105] "mentlill"        "physill"         "viglabel"        "dectreat"       
[2109] "decmoney"        "imprvown"        "imprvtrt"        "vignei"         
[2113] "vigsoc"          "vigfrnd"         "vigwork"         "viggrp"         
[2117] "vigmar"          "hurtoth"         "hurtself"        "tlkfam"         
[2121] "tlkclrgy"        "meddoc"          "mentldoc"        "mentloth"       
[2125] "sphealer"        "selfhelp"        "otcmed"          "rxmed"          
[2129] "mentlhos"        "dofirst"         "ortlkfm"         "ortlkclr"       
[2133] "ormeddoc"        "ormntldc"        "ormntlot"        "orhealer"       
[2137] "orslfhlp"        "orotcmed"        "orrxmed"         "ormntlhs"       
[2141] "mustdoc"         "mustmed"         "musthosp"        "dangrslf"       
[2145] "dangroth"        "medcare1"        "medcare2"        "spmentl"        
[2149] "govmentl"        "mntlas1"         "mntlas2"         "mntlimp1"       
[2153] "mntlimp2"        "mntlimp3"        "mntlsym1"        "mntlsym2"       
[2157] "mntlsym3"        "mntloth"         "brkdas1"         "brkdas2"        
[2161] "brkdimp1"        "brkdimp2"        "brkdimp3"        "brkdsym1"       
[2165] "brkdsym2"        "brkdsym3"        "brkdoth"         "knwmhosp"       
[2169] "relmhsp1"        "relmhsp2"        "relmhsp3"        "relmhsp4"       
[2173] "relmhsp5"        "relmhsp6"        "knwpatnt"        "evbrkdwn"       
[2177] "brkdwhy1"        "brkdwhy2"        "brkdwhy3"        "brkddo1"        
[2181] "brkddo2"         "brkddo3"         "brkdhlp1"        "brkdhlp2"       
[2185] "brkdhlp3"        "brkdtime"        "brkddur"         "evmhp"          
[2189] "mnilwhy1"        "mnilwhy2"        "mnilwhy3"        "mnildo1"        
[2193] "mnildo2"         "mnildo3"         "mnilhlp1"        "mnilhlp2"       
[2197] "mnilhlp3"        "mniltime"        "mnildur"         "knwmw1"         
[2201] "knwmw2"          "knwmw3"          "knwmw4"          "knwmw5"         
[2205] "mhp1r1"          "mhp1r2"          "mhp2r1"          "mhp2r2"         
[2209] "mhp3r1"          "mhp3r2"          "mhp4r1"          "mhp4r2"         
[2213] "mhp5r1"          "mhp5r2"          "closeto1"        "closeto2"       
[2217] "closeto3"        "closeto4"        "closeto5"        "seetalk1"       
[2221] "seetalk2"        "seetalk3"        "seetalk4"        "seetalk5"       
[2225] "mhtreat1"        "mhtreat2"        "mhtreat3"        "mhtreat4"       
[2229] "mhtreat5"        "myprobs1"        "myprobs2"        "myprobs3"       
[2233] "myprobs4"        "myprobs5"        "severe1"         "severe2"        
[2237] "severe3"         "severe4"         "severe5"         "dangoth1"       
[2241] "dangoth2"        "dangoth3"        "dangoth4"        "dangoth5"       
[2245] "dangslf1"        "dangslf2"        "dangslf3"        "dangslf4"       
[2249] "dangslf5"        "fammhneg"        "othmhneg"        "diagnosd"       
[2253] "mhtreatd"        "mcsds1"          "mcsds2"          "mcsds3"         
[2257] "mcsds4"          "mcsds5"          "mcsds6"          "mcsds7"         
[2261] "privpray"        "meditate"        "conghlp1"        "conghlp2"       
[2265] "conghrm1"        "conghrm2"        "cope1"           "cope2"          
[2269] "cope3"           "cope4"           "cope5"           "cope6"          
[2273] "godwatch"        "lesspain"        "rellife"         "forgive1"       
[2277] "forgive2"        "forgive3"        "feelgod"         "relcmfrt"       
[2281] "harmony"         "uniongod"        "godlove"         "beausprt"       
[2285] "nocheer"         "nervous"         "fidgety"         "hopeless"       
[2289] "effort"          "wrthless"        "lotr1"           "lotr2"          
[2293] "lotr3"           "lotr4"           "lotr5"           "lotr6"          
[2297] "hope1"           "hope2"           "hope3"           "hope4"          
[2301] "hope5"           "hope6"           "relpersn"        "sprtprsn"       
[2305] "relexp"          "natarts"         "artgod"          "artists"        
[2309] "irrelart"        "irreloff"        "aimofart"        "readfict"       
[2313] "popmusic"        "drama"           "relart"          "volarts"        
[2317] "natlart"         "stateart"        "localart"        "prfmnce"        
[2321] "artexbt"         "prfmmus"         "prfmdan"         "prfmthe"        
[2325] "prfmatt"         "prfmatt1"        "prfmatt2"        "prfmatt3"       
[2329] "prfmatt4"        "prfmatt5"        "prfmfree"        "prfmwhy1"       
[2333] "prfmwhy2"        "prfmwhy3"        "prfmwhy4"        "prfmwhy5"       
[2337] "prfmwhy6"        "prfmwhy7"        "prfmwhy8"        "prfmwhy9"       
[2341] "prfmwhy0"        "artatt"          "artatt1"         "artatt2"        
[2345] "artatt3"         "artatt4"         "artatt5"         "artfree"        
[2349] "artwhy1"         "artwhy2"         "artwhy3"         "artwhy4"        
[2353] "artwhy5"         "artwhy6"         "artwhy7"         "artwhy8"        
[2357] "artwhy9"         "nogo"            "nogo1"           "prfmcost"       
[2361] "prfmint"         "prfmtrvl"        "prfmgst"         "prfmtime"       
[2365] "prfmloc"         "prfmothr"        "prfmothr1"       "artcost"        
[2369] "artint"          "arttrvl"         "artgst"          "arttime"        
[2373] "artloc"          "artothr"         "prfmmostoth"     "artmostoth"     
[2377] "occyrs"          "occtrain"        "trainsch"        "typeorg"        
[2381] "wrkoth"          "othyrs"          "partorg"         "orgsize"        
[2385] "genderwk"        "locyrs"          "samework"        "siteyrs"        
[2389] "otjtrain"        "formltrn"        "formlfin"        "formldys"       
[2393] "formlhrs"        "doingtrn"        "doingfin"        "doingdys"       
[2397] "wojob"           "wojobyrs"        "numemp"          "howpaid"        
[2401] "hourly"          "daily"           "weekly"          "monthly"        
[2405] "yearly"          "trusting"        "seenmntl"        "psycmed1"       
[2409] "psycmed2"        "psycmed3"        "psycmed4"        "psycmed5"       
[2413] "psycmed6"        "psycmed7"        "usepsyc1"        "usepsyc2"       
[2417] "usepsyc3"        "usepsyc4"        "psyckid1"        "psyckid2"       
[2421] "psyckid3"        "psycdrct"        "psycfdoc"        "psycpsyc"       
[2425] "hlthinsr"        "doclist"         "anydoc"          "swithlth"       
[2429] "usedmntl"        "mntlcare"        "mntldif"         "mntldeny"       
[2433] "hmo1"            "hmo2"            "hmo3"            "hmo4"           
[2437] "hmo5"            "hmo6"            "hmo7"            "doc1"           
[2441] "doc2"            "doc3"            "doc4"            "doc5"           
[2445] "doc6"            "doc7"            "doc8"            "doc9"           
[2449] "doc10"           "doc11"           "doc12"           "doc13"          
[2453] "doc14"           "doc15"           "doc16"           "doc17"          
[2457] "doc18"           "doc19"           "doc20"           "prozac"         
[2461] "usedproz"        "knwnproz"        "prozfor1"        "prozfor2"       
[2465] "prozfor3"        "proz1"           "proz2"           "proz3"          
[2469] "proz4"           "proz5"           "proz6"           "proz7"          
[2473] "proz8"           "proz9"           "prozslf1"        "prozslf2"       
[2477] "prozslf3"        "prozslf4"        "prozkid1"        "prozkid2"       
[2481] "prozkid3"        "socsecrt"        "socsecfx"        "socsecnu"       
[2485] "terminal"        "termecon"        "termrel"         "termemot"       
[2489] "termpain"        "termpay"         "trustfam"        "trustdoc"       
[2493] "trustcrt"        "termvig"         "rightref"        "notreat"        
[2497] "instrctn"        "hospice"         "painmed"         "docsui"         
[2501] "famwhts"         "famblks"         "famjews"         "famhsps"        
[2505] "famasns"         "fairwhts"        "fairblks"        "fairjews"       
[2509] "fairhsps"        "fairasns"        "conteng"         "contitl"        
[2513] "contchn"         "contjew"         "contblk"         "contmex"        
[2517] "contvn"          "contcuba"        "contirsh"        "contpr"         
[2521] "contjpn"         "contmslm"        "othlang"         "othlang1"       
[2525] "othlang2"        "othbest"         "spklang"         "uselang"        
[2529] "getlang"         "parlang"         "granlang"        "langcom"        
[2533] "langwrk"         "engoff1"         "twolang"         "nobiling"       
[2537] "engunite"        "forlang1"        "engthrtn"        "engvote"        
[2541] "othhome"         "betrlang"        "spklangw"        "letinhsp"       
[2545] "letinasn"        "letineur"        "immcrmup"        "immnew"         
[2549] "immnojob"        "uswht"           "usblk"           "usjews"         
[2553] "ushisp"          "usasn"           "usamind"         "usmixed"        
[2557] "whtchng"         "blkchng"         "jewschng"        "hispchng"       
[2561] "asnchng"         "ethchng"         "comwht"          "comblk"         
[2565] "comjews"         "comhisp"         "comasn"          "comamind"       
[2569] "hispwork"        "knwwht"          "knwblk"          "knwjew"         
[2573] "knwhisp"         "knwasn"          "whtschl"         "whtcom"         
[2577] "whtrel"          "whtwrk"          "whtcls"          "blkschl"        
[2581] "blkcom"          "blkrel"          "blkwrk"          "blkcls"         
[2585] "jewsschl"        "jewscom"         "jewsrel"         "jewswrk"        
[2589] "jewscls"         "hispschl"        "hispcom"         "hisprel"        
[2593] "hispwrk"         "hispcls"         "asnschl"         "asncom"         
[2597] "asnrel"          "asnwrk"          "asncls"          "mostcom"        
[2601] "leastcom"        "neieth1"         "neieth2"         "neieth3"        
[2605] "neieth4"         "neieth5"         "neieth6"         "neieth7"        
[2609] "neieth8"         "neieth9"         "neieth10"        "neieth11"       
[2613] "neieth12"        "neieth13"        "neieth14"        "hswht"          
[2617] "hseth"           "compuse"         "webtv"           "webmob"         
[2621] "emailmin"        "emailhr"         "usewww"          "wwwhr"          
[2625] "wwwmin"          "chathr"          "chatmin"         "drctlink"       
[2629] "typeurl"         "srcheng"         "bookmark"        "catdrcty"       
[2633] "hyperlnk"        "emaillnk"        "fin30"           "schl30"         
[2637] "educ30"          "work30"          "news30"          "govt30"         
[2641] "pol30"           "travel30"        "sports30"        "music30"        
[2645] "art30"           "tvmov30"         "health30"        "relig30"        
[2649] "games30"         "humor30"         "porn30"          "person30"       
[2653] "sci30"           "hobby30"         "cook30"          "work12"         
[2657] "hmefin12"        "buyinf12"        "buyit12"         "invest12"       
[2661] "people12"        "health12"        "travel12"        "locate12"       
[2665] "game12"          "newjob12"        "chat12"          "polinf12"       
[2669] "econ12"          "abort12"         "moral12"         "foraff12"       
[2673] "racrel12"        "enviro12"        "polcam12"        "gun12"          
[2677] "taxes12"         "fe12"            "news12"          "polagree"       
[2681] "polneutl"        "poldsagr"        "petition"        "contact"        
[2685] "meeting"         "polnew"          "votefor"         "polchnge"       
[2689] "polforms"        "polconf"         "polalter"        "poltough"       
[2693] "artsmin"         "artshr"          "artschat"        "artsnew"        
[2697] "artschng"        "wwwmusic"        "musicinf"        "musicget"       
[2701] "musiclst"        "musicbuy"        "wwwclass"        "wwwcntry"       
[2705] "wwwgthic"        "wwwjazz"         "wwwoldie"        "wwwrap"         
[2709] "wwwrelig"        "wwwrock"         "wwwworld"        "musiclke"       
[2713] "musicdif"        "musicnew"        "wwwart"          "artmus1"        
[2717] "artmus2"         "artview"         "artinfo"         "artmus3"        
[2721] "wwwlit"          "litsite"         "litget"          "litauth"        
[2725] "litread"         "wwwpersn"        "wwwsp"           "wwwgfbf"        
[2729] "wwwcowrk"        "wwwbiz"          "wwwnei"          "wwwfrnd"        
[2733] "wwwvol"          "online"          "manual"          "callcomp"       
[2737] "askwork"         "askother"        "payother"        "doonown"        
[2741] "advsp"           "advchld"         "advpar"          "advsib"         
[2745] "advfam"          "advtchr"         "advstu"          "advsup"         
[2749] "advcowrk"        "advcfrnd"        "advofrnd"        "advlib"         
[2753] "srcheng1"        "srcheng2"        "download"        "upload"         
[2757] "cmpvirus"        "hlthinfo"        "hlthpapr"        "hlthmag1"       
[2761] "hlthmag2"        "hlthdoc"         "hlthfrel"        "hlthtv"         
[2765] "hlthwww"         "polinfo"         "polpapr"         "polmag1"        
[2769] "polmag2"         "poltv"           "polfrel"         "polcamp"        
[2773] "polwww"          "buyinfgn"        "investgn"        "travelgn"       
[2777] "peoplegn"        "gamegn"          "newjobgn"        "poldisgn"       
[2781] "polinfgn"        "perfrmgn"        "artgn"           "polcangn"       
[2785] "numcntct"        "inperson"        "byphone"         "letters"        
[2789] "meetings"        "byemail"         "comphome"        "usehome"        
[2793] "numhome"         "wwwhome"         "paywww"          "wwwline1"       
[2797] "wwwline2"        "ecomminh"        "ecomhrh"         "perminh"        
[2801] "perhrh"          "wrkminh"         "wrkhrh"          "emminh"         
[2805] "emhrh"           "wwwminh"         "wwwhrh"          "compwork"       
[2809] "jobminw"         "jobhrw"          "incminw"         "inchrw"         
[2813] "ecomminw"        "ecomhrw"         "perminw"         "perhrw"         
[2817] "emminw"          "emhrw"           "wwwminw"         "wwwhrw"         
[2821] "compoth"         "compschl"        "complib"         "compfri"        
[2825] "compelse"        "mostloc"         "ecommino"        "ecomhro"        
[2829] "permino"         "perhro"          "wrkmino"         "wrkhro"         
[2833] "emmino"          "emhro"           "wwwmino"         "wwwhro"         
[2837] "emsent"          "emsentp"         "emget"           "emgetp"         
[2841] "emwrkloc"        "emwrkawy"        "emfamloc"        "emfamoth"       
[2845] "emfri"           "emchurch"        "emgroups"        "intuse"         
[2849] "intstart"        "intmbile"        "intrecnt"        "fbaccess"       
[2853] "twitter"         "facebook"        "instagrm"        "linkedin"       
[2857] "snapchat"        "tumblr"          "whatsapp"        "googlesn"       
[2861] "pinterst"        "flickr"          "vine"            "clssmtes"       
[2865] "snsmoth1"        "snsmot2a"        "snsmot2b"        "snsmot2c"       
[2869] "snsmnew"         "snsmyear"        "snsmfrst"        "intwkdym"       
[2873] "intwkdyh"        "intwkenm"        "intwkenh"        "numprobs"       
[2877] "byemprob"        "intaccss"        "jobinfo"         "jobpaper"       
[2881] "jobpub"          "jobcowrk"        "jobcntct"        "jobfrnds"       
[2885] "jobplace"        "jobtvrad"        "jobonwww"        "emailyr"        
[2889] "webyr"           "webable"         "manbook"         "cussup"         
[2893] "tecsup"          "askwksch"        "askelse"         "payelse"        
[2897] "doself"          "processr"        "browser1"        "browser2"       
[2901] "browser3"        "advsrch"         "mp3"             "ezines"         
[2905] "prefsets"        "newsgrps"        "timekid1"        "timekid2"       
[2909] "timekid3"        "timekid4"        "sptmkid1"        "sptmkid2"       
[2913] "sptmkid3"        "sptmkid4"        "kdtmkid1"        "kdtmkid2"       
[2917] "kdtmkid3"        "kdtmkid4"        "knowkid1"        "knowkid2"       
[2921] "knowkid3"        "knowkid4"        "huclean"         "homeband"       
[2925] "freemns1"        "freemns2"        "freemns3"        "freeexp1"       
[2929] "freeexp2"        "freeexp3"        "howfree"         "rhowfree"       
[2933] "freenow"         "rfreenow"        "satdemoc"        "leftlone"       
[2937] "nogovt"          "inpeace"         "partpol"         "choice"         
[2941] "expunpop"        "freeprss"        "wlthpov"         "cntrlife"       
[2945] "modact"          "stairs"          "didlessp"        "limitedp"       
[2949] "didlesse"        "crelesse"        "pain"            "peaceful"       
[2953] "energy"          "downblue"        "socacts"         "treat1"         
[2957] "treat2"          "treat3"          "treat4"          "treat5"         
[2961] "treat6"          "treat7"          "treat8"          "treat9"         
[2965] "treat10"         "treat11"         "wait1"           "wait2"          
[2969] "wait3"           "wait4"           "wait5"           "wait6"          
[2973] "wait7"           "wait8"           "wait9"           "wait10"         
[2977] "wait11"          "downqol"         "downfam"         "downcure"       
[2981] "downrely"        "downfeel"        "painqol"         "painfam"        
[2985] "paincure"        "painrely"        "painfeel"        "emotqol"        
[2989] "emotfam"         "emotcure"        "emotrely"        "emotfeel"       
[2993] "ethimp"          "ethignor"        "ethnofit"        "ethtrads"       
[2997] "ethadapt"        "feelblks"        "feelasns"        "feelhsps"       
[3001] "feelwhts"        "ethsame"         "ethdiff"         "whtsdiff"       
[3005] "docvig"          "regdoc"          "regdocyr"        "docaskme"       
[3009] "docdecid"        "docrely"         "hlthplan"        "chosedoc"       
[3013] "insrlmts"        "diffcare"        "fininc"          "fininc1"        
[3017] "fininc2"         "fininc3"         "fininc4"         "belvedoc"       
[3021] "docinfo"         "docnomri"        "docsat"          "doccosts"       
[3025] "docswtch"        "insrchng"        "secopin"         "paidhow"        
[3029] "usualhrs"        "mosthrs"         "leasthrs"        "sethrs"         
[3033] "advsched"        "wrktype"         "yearsjob"        "waypaid"        
[3037] "wrksched"        "moredays"        "mustwork"        "chngtme"        
[3041] "wrkhome"         "whywkhme"        "famwkoff"        "wkvsfam"        
[3045] "famvswk"         "hrsrelax"        "secondwk"        "learnnew"       
[3049] "workfast"        "workdiff"        "lotofsay"        "wktopsat"       
[3053] "overwork"        "knowwhat"        "myskills"        "respect"        
[3057] "trustman"        "safetywk"        "safefrst"        "teamsafe"       
[3061] "safehlth"        "proudemp"        "prodctiv"        "wksmooth"       
[3065] "trdunion"        "partteam"        "wkdecide"        "setthngs"       
[3069] "toofewwk"        "promteok"        "opdevel"         "hlpequip"       
[3073] "haveinfo"        "wkfreedm"        "fringeok"        "supcares"       
[3077] "condemnd"        "promtefr"        "cowrkint"        "jobsecok"       
[3081] "suphelp"         "wrktime"         "cowrkhlp"        "trainops"       
[3085] "manvsemp"        "hvylift"         "handmove"        "wkpraise"       
[3089] "wkbonus"         "fairearn"        "rincblls"        "laidoff"        
[3093] "jobfind1"        "trynewjb"        "wkageism"        "wkracism"       
[3097] "wksexism"        "wkharsex"        "wkharoth"        "health1"        
[3101] "physhlth"        "mntlhlth"        "hlthdays"        "usedup"         
[3105] "backpain"        "painarms"        "hurtatwk"        "spvtrfair"      
[3109] "strredpg"        "phyeffrt"        "slpprblm"        "satjob1"        
[3113] "knowschd"        "usetech"         "stress12"        "hyperten"       
[3117] "arthrtis"        "diabetes"        "depress"         "weight"         
[3121] "height"          "ntwkhard"        "misswork"        "lifenow"        
[3125] "lifein5"         "cesd1"           "cesd2"           "cesd3"          
[3129] "cesd4"           "cesd5"           "disrspct"        "poorserv"       
[3133] "notsmart"        "afraidof"        "threaten"        "quallife"       
[3137] "hlthphys"        "hlthmntl"        "satsoc"          "actssoc"        
[3141] "physacts"        "emoprobs"        "fatigue"         "ratepain"       
[3145] "abfelegl"        "abmelegl"        "abmoral"         "abstate1"       
[3149] "abstate2"        "abhelp1"         "abhelp2"         "abhelp3"        
[3153] "abhelp4"         "abmedgov1"       "abmedgov2"       "abinspay"       
[3157] "natnotice"       "natviews"        "nataccess"       "nattime"        
[3161] "natsat"          "natrelax"        "natactive"       "natmeet"        
[3165] "nattimeok"       "natlack"         "numpets"         "whynopet"       
[3169] "petb4"           "dog"             "cat"             "smammal"        
[3173] "bird"            "fish"            "reptile"         "horse"          
[3177] "pig"             "goat"            "othpet"          "petplay"        
[3181] "petcmfrt"        "petfam"          "dogb4"           "catb4"          
[3185] "smammalb4"       "birdb4"          "fishb4"          "reptileb4"      
[3189] "horseb4"         "pigb4"           "goatb4"          "othpetb4"       
[3193] "petb4ply"        "petb4cmfrt"      "petb4fam"        "workfor"        
[3197] "workfor1"        "ownstock"        "stockval"        "stockops"       
[3201] "extrapay"        "compperf"        "deptperf"        "indperf"        
[3205] "extr2001"        "extr2017"        "extraval"        "extrayr"        
[3209] "yearval"         "seecowrk"        "cowrkhrd"        "talkemp"        
[3213] "talksup"         "donothng"        "lastwkmo"        "lastwkyr"       
[3217] "empathy1"        "empathy2"        "empathy3"        "empathy4"       
[3221] "empathy5"        "empathy6"        "empathy7"        "givblood"       
[3225] "givhmlss"        "retchnge"        "cutahead"        "volchrty"       
[3229] "givchrty"        "givseat"         "helpaway"        "carried"        
[3233] "directns"        "loanitem"        "selfless"        "accptoth"       
[3237] "othshelp"        "careself"        "peoptrbl"        "selffrst"       
[3241] "volmonth"        "valgiven"        "finind"          "finind1"        
[3245] "ownhh"           "ownhh1"          "eddone"          "eddone1"        
[3249] "ftwork"          "ftwork1"         "supfam"          "supfam1"        
[3253] "havchld"         "havchld1"        "getmar"          "getmar1"        
[3257] "boycott"         "signpet"         "protest"         "conoffcl"       
[3261] "givchng"         "hlpneedy"        "partthon"        "chldvig"        
[3265] "chldprb"         "chldprob"        "chldhlp"         "badchar"        
[3269] "chembal"         "stressfl"        "geneprob"        "raised"         
[3273] "violtv"          "discipln"        "allergic"        "bettrown"       
[3277] "imprvdis"        "imprveat"        "imprvmed"        "nextdoor"       
[3281] "spendeve"        "chldfrnd"        "chldsch"         "adfam"          
[3285] "adfammed"        "adtch"           "adtchmed"        "addoc"          
[3289] "addocmed"        "adcou"           "adcoumed"        "adpsy"          
[3293] "adpsymed"        "adhos"           "adhosmed"        "forcedoc"       
[3297] "forcemed"        "forcehos"        "grwingup"        "mntlill"        
[3301] "illphys"         "violpeop"        "violself"        "outsider"       
[3305] "sufadult"        "comknows"        "failure"         "ovrmedkd"       
[3309] "medkdneg"        "putsoff"         "trbllaw"         "medsavtx"       
[3313] "zombies"         "pryntfam"        "adhdknow"        "adhdknw"        
[3317] "adhdreal"        "adhdcon"         "adhdmed"         "mntlrel"        
[3321] "medsymps"        "medaddct"        "medweak"         "medunacc"       
[3325] "solveown"        "doc15a"          "doc16a"          "doc18a"         
[3329] "doc19a"          "doc20a"          "caninf1"         "caninf2"        
[3333] "caninf3"         "caninf4"         "caninf5"         "caninf6"        
[3337] "caninf7"         "caninf8"         "caninf9"         "caninf10"       
[3341] "caninf11"        "caninf12"        "caninf13"        "caninf14"       
[3345] "difstand"        "rptprobs"        "othcredt"        "putdown"        
[3349] "lackinfo"        "perspace"        "physharm"        "actupset"       
[3353] "shout"           "hotargus"        "reliedon"        "gdjobsec"       
[3357] "treatres"        "lookaway"        "skipwork"        "numemps"        
[3361] "wrkslffam"       "ignorwk"         "rumorwk"         "jokeswk"        
[3365] "eharaswk"        "rudewk"          "liedcwkr"        "denyrais"       
[3369] "wkbhvrs"         "wkrspns"         "natborn"         "bornhome"       
[3373] "travelus"        "immstats"        "rundrstd"        "robject"        
[3377] "genevig1"        "genevig2"        "genenvo1"        "genenvo2"       
[3381] "genenvo3"        "genenvo4"        "satself"         "afailure"       
[3385] "slfrspct"        "ofworth"         "nogood"          "optimist"       
[3389] "pessimst"        "notcount"        "moregood"        "owndoing"       
[3393] "geneexps"        "depndabl"        "sadblue"         "athletic"       
[3397] "kindpers"        "selfish"         "intrwght"        "agape1"         
[3401] "agape2"          "agape3"          "agape4"          "hgunlaw"        
[3405] "hguncrim"        "crimup"          "crimdown"        "numrelex"       
[3409] "agerelex"        "chngrel"         "numrborn"        "agerborn"       
[3413] "chngrbrn"        "entity"          "expchng1"        "expchng2"       
[3417] "expchng3"        "whychng1"        "whychng2"        "whychng3"       
[3421] "changed1"        "changed2"        "changed3"        "relalt1"        
[3425] "relalt2"         "relalt3"         "relalt4"         "relalt5"        
[3429] "relalt6"         "alloflfe"        "joylifts"        "relsprt1"       
[3433] "relsprt2"        "godhelp"         "godguide"        "godlvdir"       
[3437] "godlvoth"        "blessngs"        "closrgod"        "godclose"       
[3441] "idols"           "rosaries"        "notthink"        "evdrink"        
[3445] "drinkyr"         "drinkday"        "drink6up"        "drinkmax"       
[3449] "drink12"         "drink8"          "drink5"          "drink3"         
[3453] "drink1"          "drinkmin"        "churchtx"        "infrmgrp"       
[3457] "typfrat"         "typserv"         "typvet"          "typpolit"       
[3461] "typunion"        "typsport"        "typyouth"        "typschl"        
[3465] "typhobby"        "typgreek"        "typnat"          "typfarm"        
[3469] "typlit"          "typprof"         "typchurh"        "typother"       
[3473] "typinfrm"        "numfrat"         "numserv"         "numvet"         
[3477] "numpolit"        "numunion"        "numsport"        "numyouth"       
[3481] "numschl"         "numhobby"        "numgreek"        "numnat"         
[3485] "numfarm"         "numlit"          "numprof"         "numchurh"       
[3489] "numother"        "numinfrm"        "yrfrat1"         "yrfrat2"        
[3493] "yrfrat3"         "yrfrat4"         "yrserv1"         "yrserv2"        
[3497] "yrserv3"         "yrserv4"         "yrserv5"         "yrserv6"        
[3501] "yrserv7"         "yrserv8"         "yrvet1"          "yrvet2"         
[3505] "yrvet3"          "yrvet4"          "yrvet5"          "yrpolit1"       
[3509] "yrpolit2"        "yrpolit3"        "yrunion1"        "yrunion2"       
[3513] "yrunion3"        "yrunion4"        "yrsport1"        "yrsport2"       
[3517] "yrsport3"        "yrsport4"        "yrsport5"        "yrsport6"       
[3521] "yryouth1"        "yryouth2"        "yryouth3"        "yryouth4"       
[3525] "yryouth5"        "yrschl1"         "yrschl2"         "yrschl3"        
[3529] "yrschl4"         "yrhobby1"        "yrhobby2"        "yrhobby3"       
[3533] "yrgreek1"        "yrgreek2"        "yrgreek3"        "yrnat1"         
[3537] "yrnat2"          "yrnat3"          "yrfarm1"         "yrfarm2"        
[3541] "yrfarm3"         "yrlit1"          "yrlit2"          "yrlit3"         
[3545] "yrlit4"          "yrprof1"         "yrprof2"         "yrprof3"        
[3549] "yrprof4"         "yrprof5"         "yrprof6"         "yrchurh1"       
[3553] "yrchurh2"        "yrchurh3"        "yrchurh4"        "yrchurh5"       
[3557] "yrchurh6"        "yrother1"        "yrother2"        "yrother3"       
[3561] "yrother4"        "yrother5"        "yrinfrm1"        "yrinfrm2"       
[3565] "yrinfrm3"        "yrinfrm4"        "yrinfrm5"        "mtfrat1"        
[3569] "mtfrat2"         "mtfrat3"         "mtfrat4"         "mtserv1"        
[3573] "mtserv2"         "mtserv3"         "mtserv4"         "mtserv5"        
[3577] "mtserv6"         "mtserv7"         "mtserv8"         "mtvet1"         
[3581] "mtvet2"          "mtvet3"          "mtvet4"          "mtvet5"         
[3585] "mtpolit1"        "mtpolit2"        "mtpolit3"        "mtunion1"       
[3589] "mtunion2"        "mtunion3"        "mtunion4"        "mtsport1"       
[3593] "mtsport2"        "mtsport3"        "mtsport4"        "mtsport5"       
[3597] "mtsport6"        "mtyouth1"        "mtyouth2"        "mtyouth3"       
[3601] "mtyouth4"        "mtyouth5"        "mtschl1"         "mtschl2"        
[3605] "mtschl3"         "mtschl4"         "mthobby1"        "mthobby2"       
[3609] "mthobby3"        "mtgreek1"        "mtgreek2"        "mtgreek3"       
[3613] "mtnat1"          "mtnat2"          "mtnat3"          "mtfarm1"        
[3617] "mtfarm2"         "mtfarm3"         "mtlit1"          "mtlit2"         
[3621] "mtlit3"          "mtlit4"          "mtprof1"         "mtprof2"        
[3625] "mtprof3"         "mtprof4"         "mtprof5"         "mtprof6"        
[3629] "mtchurh1"        "mtchurh2"        "mtchurh3"        "mtchurh4"       
[3633] "mtchurh5"        "mtchurh6"        "mtother1"        "mtother2"       
[3637] "mtother3"        "mtother4"        "mtother5"        "mtinfrm1"       
[3641] "mtinfrm2"        "mtinfrm3"        "mtinfrm4"        "mtinfrm5"       
[3645] "grpboth1"        "grpboth2"        "grpboth3"        "grpboth4"       
[3649] "grpboth5"        "frstmet1"        "frstmet2"        "frstmet3"       
[3653] "frstmet4"        "frstmet5"        "yrskwn1"         "yrskwn2"        
[3657] "yrskwn3"         "yrskwn4"         "yrskwn5"         "relneg"         
[3661] "newsfrom"        "scifrom"         "seeksci"         "nextgen"        
[3665] "toofast"         "bettrlfe"        "advfront"        "scispec"        
[3669] "leadsci"         "whichsci"        "astrolgy"        "astrosci"       
[3673] "scibnfts"        "balpos"          "balneg"          "scistudy"       
[3677] "scitext"         "expdesgn"        "exptext"         "odds1"          
[3681] "odds2"           "hotcore"         "radioact"        "boyorgrl"       
[3685] "lasers"          "electron"        "viruses"         "bigbang"        
[3689] "bigbang1"        "bigbang2"        "condrift"        "evolved"        
[3693] "evolved1"        "evolved2"        "earthsun"        "solarrev"       
[3697] "tomatoes"        "intrhome"        "coldeg1"         "majorcol"       
[3701] "colsci"          "colscinm"        "hsmath"          "hsbio"          
[3705] "hschem"          "hsphys"          "gwsci"           "gwpol"          
[3709] "gwbiz"           "sciagrgw"        "sciinfgw"        "polinfgw"       
[3713] "bizinfgw"        "scibstgw"        "polbstgw"        "bizbstgw"       
[3717] "gasregs"         "scmed"           "screlig"         "scpol"          
[3721] "medagrsc"        "medinfsc"        "relinfsc"        "polinfsc"       
[3725] "medbstsc"        "relbstsc"        "polbstsc"        "scresrch"       
[3729] "txeco"           "txbiz"           "txpol"           "ecoagree"       
[3733] "ecoinftx"        "bizinftx"        "polinftx"        "ecobsttx"       
[3737] "bizbsttx"        "polbsttx"        "gmmed"           "gmpol"          
[3741] "gmbiz"           "medagrgm"        "medinfgm"        "polinfgm"       
[3745] "bizinfgm"        "medbstgm"        "polbstgm"        "bizbstgm"       
[3749] "eatgm"           "sciimp1"         "sciimp2"         "sciimp3"        
[3753] "sciimp4"         "sciimp5"         "sciimp6"         "sciimp7"        
[3757] "sciimp8"         "socsci"          "physcsci"        "histsci"        
[3761] "accntsci"        "biosci"          "econsci"         "medsci"         
[3765] "engnrsci"        "knwforgn"        "knwecon"         "knwsci"         
[3769] "knwgw"           "knwpolar"        "tvbears"         "tvinuit"        
[3773] "tvozone"         "tvmeltng"        "tvoil"           "polaryr1"       
[3777] "polaryr2"        "polaryr3"        "polaryr4"        "polaryr5"       
[3781] "polaryr6"        "polaryr7"        "polaryr8"        "icesheet"       
[3785] "nosun"           "inuit"           "huntbear"        "icecaps"        
[3789] "comorsci"        "extinct"         "sealevel"        "artseals"       
[3793] "penguins"        "inuitway"        "noicecap"        "caremost"       
[3797] "nanotech"        "nanoknw1"        "nanoknw2"        "nanowill"       
[3801] "nanoben"         "nanoharm"        "scimode"         "intintl"        
[3805] "intfarm"         "inteduc"         "intsci"          "intecon"        
[3809] "inttech"         "intmed"          "intspace"        "intenvir"       
[3813] "intmil"          "sciintro"        "visart"          "visnhist"       
[3817] "viszoo"          "vissci"          "vislib"          "scimath"        
[3821] "anscitst"        "maboygrl"        "h2olife"         "anheat"         
[3825] "lftplane"        "stormtxt"        "litmstxt"        "goldfish"       
[3829] "salth2o"         "erosion"         "genes"           "gills"          
[3833] "upbreath"        "daynight"        "weighing"        "seesand"        
[3837] "fishexp1"        "fishexp2"        "morempg"         "polnuke"        
[3841] "biznuke"         "engnuke"         "engagrnk"        "enhinfnk"       
[3845] "polinfnk"        "bizinfnk"        "engbstnk"        "polbstnk"       
[3849] "bizbstnk"        "nukeelec"        "cloning"         "scinews1"       
[3853] "scinews2"        "scinews3"        "newsfrmy"        "scifromy"       
[3857] "seeksciy"        "sciinfgo"        "scientda"        "scientsn"       
[3861] "scientr"         "scientdo"        "sciental"        "scientdn"       
[3865] "scientgo"        "scientfu"        "scienthe"        "scientod"       
[3869] "scientbe"        "scientre"        "scientwk"        "scientmo"       
[3873] "scientbr"        "engda"           "engson"          "engresp"        
[3877] "engdo"           "englone"         "engdgr"          "enggood"        
[3881] "engfun"          "engprob"         "engodd"          "engbtr"         
[3885] "engrel"          "engint"          "engearn"         "engbrng"        
[3889] "farming"         "journlsm"        "fireftng"        "marrcoun"       
[3893] "medtreat"        "architct"        "lawenfrc"        "engnring"       
[3897] "slsmnshp"        "cmprgmng"        "finlcoun"        "buyvalue"       
[3901] "ops2005"         "extr2005"        "compwage"        "talkteam"       
[3905] "numorg"          "empinput"        "slfmangd"        "emptrain"       
[3909] "wealth"          "esop"            "defpensn"        "trdestck"       
[3913] "buyesop"         "esopnot"         "company"         "viglab06"       
[3917] "mhtrtoth"        "mhothyou"        "mhothrel"        "seemhpub"       
[3921] "gesttalk"        "avoidmh"         "numknown"        "acqkevin"       
[3925] "acqkaren"        "acqshawn"        "acqbrnda"        "acqkeith"       
[3929] "acqrachl"        "acqmark"         "acqlinda"        "acqjose"        
[3933] "acqmaria"        "acqunemp"        "acqhome"         "acqprisn"       
[3937] "acqasian"        "acqblack"        "acqhisp"         "acqwhite"       
[3941] "acqgay"          "acqcohab"        "acqgoatt"        "acqnoatt"       
[3945] "acqlib"          "acqcon"          "acqcops"         "acqlaws"        
[3949] "acqsocs"         "acqjans"         "acqchild"        "acqelecs"       
[3953] "acqmils"         "acqfmmrk"        "acqfmlin"        "acqfmune"       
[3957] "acqfmhme"        "acqfmpri"        "acqfmasn"        "acqfmblk"       
[3961] "acqfmhsp"        "acqfmwht"        "acqfmgay"        "acqfmgo"        
[3965] "acqfmno"         "acqfmlib"        "acqfmcon"        "acqfmcoh"       
[3969] "acqnhmrk"        "acqnhlin"        "acqnhune"        "acqnhhme"       
[3973] "acqnhpri"        "acqnhasn"        "acqnhblk"        "acqnhhsp"       
[3977] "acqnhwht"        "acqnhgay"        "acqnhgo"         "acqnhno"        
[3981] "acqnhlib"        "acqnhcon"        "acqnhcoh"        "acqwkmrk"       
[3985] "acqwklin"        "acqwkune"        "acqwkhme"        "acqwkpri"       
[3989] "acqwkasn"        "acqwkblk"        "acqwkhsp"        "acqwkwht"       
[3993] "acqwkgay"        "acqwkgo"         "acqwkno"         "acqwklib"       
[3997] "acqwkcon"        "acqwkcoh"        "acqvamrk"        "acqvalin"       
[4001] "acqvaune"        "acqvahme"        "acqvapri"        "acqvaasn"       
[4005] "acqvablk"        "acqvahsp"        "acqvawht"        "acqvagay"       
[4009] "acqvago"         "acqvano"         "acqvalib"        "acqvacon"       
[4013] "acqvacoh"        "acqreps"         "acqdems"         "acqattnd"       
[4017] "acqmyrac"        "trtkevin"        "trtkaren"        "trtshawn"       
[4021] "trtbrnda"        "trtkeith"        "trtrachl"        "trtmark"        
[4025] "trtlinda"        "trtjose"         "trtmaria"        "trtcops"        
[4029] "trtlaws"         "trtsocs"         "trtjans"         "trtchild"       
[4033] "trtelecs"        "trtmils"         "trtunemp"        "trthome"        
[4037] "trtprisn"        "trtasian"        "trtblack"        "trthisp"        
[4041] "trtwhite"        "trtgay"          "trtcohab"        "trtgoatt"       
[4045] "trtnoatt"        "trtlib"          "trtcon"          "trtreps"        
[4049] "trtdems"         "trtattnd"        "trtmyrac"        "gunsales"       
[4053] "gunsdrug"        "semiguns"        "guns911"         "rifles50"       
[4057] "othguns"         "gunsdrnk"        "spnatdis"        "natdisin"       
[4061] "natdiscm"        "newsprnt"        "getaheay"        "disabld1"       
[4065] "disabld2"        "disabld3"        "disabld4"        "disabld5"       
[4069] "disabld6"        "disabld7"        "vigvermy"        "mhproblm"       
[4073] "mhdofam"         "mhdofrnd"        "mhdorel"         "mhdodoc"        
[4077] "mhdopsyc"        "mhdomhp"         "mhdoheal"        "mhdootc"        
[4081] "mhdorx"          "mhdohosp"        "mhdopray"        "mhdolife"       
[4085] "mhdoherb"        "mhdofrgt"        "mhdoactv"        "mhdogrp"        
[4089] "mhdodiet"        "mhdoexrc"        "mhdomove"        "mhdooth"        
[4093] "mhdonone"        "mhchrctr"        "mhbrain"         "mhraised"       
[4097] "mhstress"        "mhgenes"         "mhgod"           "mhluck"         
[4101] "mhupdown"        "mhillnss"        "mhphyscl"        "mhneihbr"       
[4105] "mhsocial"        "mhkdcare"        "mhfriend"        "mhwkwith"       
[4109] "mhwedrel"        "mhimpown"        "mhimptrt"        "mhdecslf"       
[4113] "mhmoney"         "mhoutsdr"        "mhlosefr"        "mhlessop"       
[4117] "mhuneasy"        "mhunsure"        "mhintl"          "mhnotpol"       
[4121] "mhhrdtlk"        "mhnokids"        "mhcreatv"        "mhnervs"        
[4125] "mhprdctv"        "mhfeelem"        "mhtrusty"        "mhaccptd"       
[4129] "mhhired"         "mhnotell"        "mhsecret"        "mhsupwrk"       
[4133] "mhnotch"         "mhhlpfam"        "mhhlpfrd"        "mhhlprel"       
[4137] "mhhlpgp"         "mhhlppsy"        "mhhlpmhp"        "mhgvtjob"       
[4141] "mhgvthlt"        "mhgvthme"        "mhgvtedc"        "mhgvtdis"       
[4145] "mhslfshm"        "mhfamshm"        "mhseedoc"        "mhmeds"         
[4149] "mhhsptrt"        "mhmnthsp"        "mhviooth"        "mhvioslf"       
[4153] "mhcause"         "mhtrtot2"        "mhdiagno"        "mhclsoth"       
[4157] "mhseroth"        "mhhlpoth"        "mhresoth"        "mhdisoth"       
[4161] "mhreloth"        "mhexpoth"        "mhtrtslf"        "mhseepub"       
[4165] "mhfright"        "mhsymp"          "startbiz"        "ownbiz"         
[4169] "numown"          "yearbiz"         "paidemps"        "bizgross"       
[4173] "bizshare"        "owninc"          "whybiz"          "numemps5"       
[4177] "spjrel16"        "spjoth16"        "majwoth"         "pajwoth"        
[4181] "bmitzvah"        "synmem"          "kd1relig"        "kd2relig"       
[4185] "kd3relig"        "kd4relig"        "kd5relig"        "kd6relig"       
[4189] "kd7relig"        "kd8relig"        "kd1jwoth"        "kd2jwoth"       
[4193] "kd3jwoth"        "kd4jwoth"        "kd5jwoth"        "done911a"       
[4197] "eff911a"         "done911b"        "eff911b"         "done911c"       
[4201] "eff911c"         "done911d"        "eff911d"         "done911e"       
[4205] "eff911e"         "done911f"        "eff911f"         "done911g"       
[4209] "eff911g"         "done911h"        "eff911h"         "done911i"       
[4213] "eff911i"         "done911j"        "eff911j"         "done911k"       
[4217] "eff911k"         "done911l"        "eff911l"         "done911m"       
[4221] "eff911m"         "done911n"        "eff911n"         "doneelse"       
[4225] "work3yrs"        "curempyr"        "paychnge"        "pastpay"        
[4229] "whyleave"        "whyjbct1"        "whyjbct2"        "losejb12"       
[4233] "whylose1"        "whylose2"        "whylose3"        "findnwjb"       
[4237] "moretrde"        "newjobs"         "lostjobs"        "wkcomptr"       
[4241] "wocomptr"        "autonojb"        "meetf2f1"        "meetf2f2"       
[4245] "intlcowk"        "lastyrwk"        "leavejb"         "whynojb1"       
[4249] "whynojb2"        "inclstjb"        "bornsp"          "agecmeus"       
[4253] "visa"            "typevisa"        "natdeg"          "emphlth"        
[4257] "emphplan"        "othplan"         "sexsex18"        "toldsmsx"       
[4261] "attractd"        "toldsxor"        "relgendr"        "marunion"       
[4265] "sexunion"        "evkid"           "adoptkid"        "kidlived"       
[4269] "kidresp"         "kidnow1"         "kidnow2"         "toldwork"       
[4273] "evlosejb"        "losejob5"        "evnegjob"        "negjob5"        
[4277] "evharjb"         "harjob5"         "evdwell"         "dwell5"         
[4281] "emphlth1"        "emphlth2"        "hlthcovr"        "hlthtype"       
[4285] "sppart"          "mykids"          "othkids"         "harsexjb"       
[4289] "harsexcl"        "ownclerg"        "numclerg"        "openrel1"       
[4293] "openrel2"        "openrel3"        "counsel1"        "counsel2"       
[4297] "counsel3"        "clrgmar1"        "clrgmar2"        "clrgmar3"       
[4301] "clrgsex1"        "clrgsex2"        "clrgsex3"        "clrggen1"       
[4305] "clrggen2"        "clrggen3"        "ongorel1"        "ongorel2"       
[4309] "ongorel3"        "hushrel1"        "hushrel2"        "hushrel3"       
[4313] "toldexp1"        "toldexp2"        "toldexp3"        "toldrel1"       
[4317] "toldrel2"        "toldrel3"        "knwclsex"        "clsclsex"       
[4321] "clrgmode"        "prespop"         "volactyr"        "volacty2"       
[4325] "polefy3"         "polefy11"        "polefy13"        "polefy15"       
[4329] "polefy16"        "polefy17"        "ratetone"        "pubdef"         
[4333] "pubecon"         "obeylaw"         "protest1"        "protest2"       
[4337] "protest3"        "protest4"        "protest5"        "protest6"       
[4341] "revspeak"        "revtch15"        "revpub"          "racspeak"       
[4345] "ractch15"        "racpub"          "crimtail"        "crimtap"        
[4349] "crimread"        "crimhold"        "mantail"         "mantap"         
[4353] "manread"         "manhold"         "verdict"         "databank"       
[4357] "progtax"         "eqincome"        "oprich"          "opprof"         
[4361] "opfamily"        "fecolop"         "fejobop"         "feinc"          
[4365] "fehlpbus"        "fehlpcol"        "fehlpjob"        "hsbasics"       
[4369] "hssexed"         "hsrespct"        "hslibart"        "hsjudge"        
[4373] "hsjobtr"         "hssci"           "hscaring"        "hsorder"        
[4377] "colop"           "aidneedy"        "aidsmart"        "aidavg"         
[4381] "kiddrugs"        "kidskips"        "kidout"          "kidneedy"       
[4385] "kidbeat"         "kidhlth"         "kidedpar"        "kidxfilm"       
[4389] "beltup"          "nosmoke"         "mustret"         "poleff1"        
[4393] "poleff2"         "poleff3"         "poleff4"         "poleff5"        
[4397] "poleff6"         "poleff7"         "poleff8"         "poleff9"        
[4401] "poleff10"        "setwage"         "setprice"        "cutgovt"        
[4405] "makejobs"        "lessreg"         "hlphitec"        "savejobs"       
[4409] "cuthours"        "spenviro"        "sphlth"          "sppolice"       
[4413] "spschool"        "sparms"          "spretire"        "spunemp"        
[4417] "sparts"          "inctax"          "bustax"          "infljobs"       
[4421] "laborpow"        "buspow"          "govtpow"         "ownpower"       
[4425] "ownmass"         "ownsteel"        "ownbanks"        "ownautos"       
[4429] "jobsall"         "pricecon"        "hlthcare"        "aidold"         
[4433] "aidindus"        "aidunemp"        "equalize"        "aidcol"         
[4437] "aidhouse"        "protstrs"        "revoltrs"        "racists"        
[4441] "unionsok"        "polint"          "rprtst1"         "rprtst3"        
[4445] "rprtst15"        "rprtst35"        "grnlaws"         "gendereq"       
[4449] "prvdhlth"        "prvdold"         "prvdschl"        "gvinflu1"       
[4453] "gvinflu2"        "polgbeco"        "poleff11"        "poleff12"       
[4457] "poleff13"        "poleff14"        "poleff15"        "poleff16"       
[4461] "poleff17"        "demworks"        "taxspend"        "taxpaid"        
[4465] "taxbylaw"        "brlawfl"         "brnotax"         "runpower"       
[4469] "runhosp"         "runbanks"        "cutdebt"         "helphlth"       
[4473] "helpold"         "helpsec"         "helpcrim"        "helpemp"        
[4477] "helpenv"         "cctv"            "emonitor"        "govtinfo"       
[4481] "givinfusa"       "givinffor"       "wotrial"         "tapphone"       
[4485] "stoprndm"        "fewtrsty"        "exploit"         "youinflu"       
[4489] "hlpinflu"        "polsfair"        "knowpols"        "corrupt1"       
[4493] "corrupt2"        "bribe"           "peocntct"        "malive"         
[4497] "mavisit"         "matime"          "macall"          "palive"         
[4501] "pavisit"         "patime"          "pacall"          "sisnum"         
[4505] "sisvisit"        "sistime"         "siscall"         "bronum"         
[4509] "brovisit"        "brotime"         "brocall"         "daunum"         
[4513] "dauvisit"        "dautime"         "daucall"         "sonnum"         
[4517] "sonvisit"        "sontime"         "soncall"         "posslq"         
[4521] "posslqy"         "marcohab"        "grparnum"        "grkidnum"       
[4525] "unaunum"         "inlawnum"        "relnum"          "relmost"        
[4529] "relvisit"        "reltime"         "relcall"         "frinum"         
[4533] "friwork"         "frineigh"        "frisex"          "frivisit"       
[4537] "fritime"         "fricall"         "chores1"         "chores2"        
[4541] "sick1"           "sick2"           "borrow1"         "borrow2"        
[4545] "upset1"          "upset2"          "down1"           "down2"          
[4549] "change1"         "change2"         "livecom"         "livehome"       
[4553] "matime1"         "sibnum"          "sibmost"         "sibvisit"       
[4557] "sibcall"         "kidnum"          "kidmost"         "kidvisit"       
[4561] "kidcall"         "pavisit1"        "pacall1"         "mavisit1"       
[4565] "macall1"         "uncaunts"        "cousins"         "parslaw"        
[4569] "sibinlaw"        "niecenep"        "godparts"        "cowrkfrd"       
[4573] "neifrd"          "bestfrd"         "bstvisit"        "bstcall"        
[4577] "grppol"          "grpunion"        "grpchurh"        "grpsport"       
[4581] "grpchrty"        "grpnei"          "grpoth"          "sick1a"         
[4585] "sick2a"          "borrow1a"        "borrow2a"        "down1a"         
[4589] "down2a"          "helphwrk"        "lentto"          "talkedto"       
[4593] "helpjob"         "learnjob"        "frdthink"        "frdhelps"       
[4597] "frdknows"        "frdenjoy"        "kidpars"         "firstyou"       
[4601] "helpfrds"        "usefrds"         "aidkids"         "othfrd"         
[4605] "demands"         "trustpeo"        "wantbest"        "advantge"       
[4609] "comyear"         "localgvt"        "knwbus"          "knwexec"        
[4613] "knwclenr"        "knwcuttr"        "knwhrman"        "knwlawyr"       
[4617] "knwmchnc"        "knwnurse"        "knwcop"          "knwtcher"       
[4621] "smallgap"        "govlazy"         "partlsc"         "partpart"       
[4625] "partvol"         "hlphome"         "hlpsick"         "hlpdown"        
[4629] "hlpadvce"        "hlpsococ"        "hlploan"         "hlpjob"         
[4633] "hlppaper"        "hlpresde"        "hlpsickr"        "lonely1"        
[4637] "lonely2"         "lonely3"         "trcourts"        "trbigbus"       
[4641] "fampress"        "upset"           "dinefrds"        "newfrds"        
[4645] "conwkday"        "conf2f"          "cntctpar"        "cntctsib"       
[4649] "cntctkid"        "cntctfam"        "cntctfrd"        "intcntct"       
[4653] "healthissp"      "unhappy"         "pilingup"        "mygoals"        
[4657] "satlife"         "endsmeet"        "numlangs"        "opwlth"         
[4661] "oppared"         "opeduc"          "opambit"         "opable"         
[4665] "ophrdwrk"        "opknow"          "opclout"         "oprace"         
[4669] "oprelig"         "opregion"        "opsex"           "oppol"          
[4673] "goodlife"        "incentiv"        "inequal1"        "inequal2"       
[4677] "inequal3"        "inequal4"        "inequal5"        "inequal6"       
[4681] "inequal7"        "paymason"        "paydoc"          "payclerk"       
[4685] "payowner"        "payexec"         "payskill"        "payfarm"        
[4689] "paysec"          "paybus"          "payunskl"        "paycabnt"       
[4693] "paylaw"          "paysales"        "payfctry"        "payjudge"       
[4697] "payrocc"         "givmason"        "givdoc"          "givclerk"       
[4701] "givowner"        "givexec"         "givskill"        "givfarm"        
[4705] "givsec"          "givbus"          "givunskl"        "givcabnt"       
[4709] "givlaw"          "givsales"        "givfctry"        "givjudge"       
[4713] "givrocc"         "incgap"          "goveqinc"        "govedop"        
[4717] "govjobs"         "govless"         "govunemp"        "govminc"        
[4721] "taxrich"         "taxmid"          "taxpoor"         "taxshare"       
[4725] "conwlth"         "conclass"        "conjobs"         "conunion"       
[4729] "conurban"        "consoc"          "conage"          "occmobil"       
[4733] "pajob"           "paslf"           "firstjob"        "firstslf"       
[4737] "lastjob"         "lastslf"         "rewrdeff"        "rewrdint"       
[4741] "corrupt"         "earndes"         "ldcgap"          "ldctax"         
[4745] "richhlth"        "richeduc"        "payresp"         "payedtrn"       
[4749] "paysup"          "payfam1"         "paychild"        "paydowel"       
[4753] "payhard"         "justpay"         "soctype1"        "soctype2"       
[4757] "famrnk"          "unsklrnk"        "execrnk"         "pasup"          
[4761] "books16"         "mawrkwrm"        "kidsuffr"        "famsuffr"       
[4765] "hapifwrk"        "homekid"         "housewrk"        "fejobind"       
[4769] "twoincs"         "hubbywrk"        "ilikejob"        "wrknokid"       
[4773] "wrkbaby"         "wrksch"          "wrkgrown"        "daycare1"       
[4777] "daycare2"        "daycare3"        "daycare4"        "daycare5"       
[4781] "femarry"         "memarry"         "marhappy"        "marfree"        
[4785] "marfin"          "markids"         "marnomar"        "marlegit"       
[4789] "marmakid"        "marpakid"        "mardiv"          "marsame"        
[4793] "marsame1"        "numkids"         "nokids"          "onekid"         
[4797] "twokids"         "threkids"        "fourkids"        "kidtrble"       
[4801] "kidjoy"          "kidnofre"        "kidless"         "kidfin"         
[4805] "kidempty"        "divnow"          "divnokid"        "divifkid"       
[4809] "divkids"         "divwife"         "divhubby"        "mawork14"       
[4813] "evdiv"           "spevdiv"         "cohabit"         "rwrknokd"       
[4817] "rwrkbaby"        "rwrksch"         "rwrkgrwn"        "earnsmor"       
[4821] "fewrksup"        "hubbywk1"        "mrmom"           "meovrwrk"       
[4825] "singlpar"        "cohabok"         "cohabfst"        "divbest"        
[4829] "divifkd1"        "divnokd1"        "livnowed"        "mapaid"         
[4833] "chldcare"        "abchoose"        "teensex1"        "sexhar"         
[4837] "fambudgt"        "laundry"         "repairs"         "caresick"       
[4841] "shopfood"        "dinner"          "spwknokd"        "spwkbaby"       
[4845] "spwrksch"        "spwkgrwn"        "mehhwork"        "mekdcare"       
[4849] "laundry1"        "repairs1"        "caresik1"        "shop1"          
[4853] "clean1"          "cooking1"        "rhhwork"         "sphhwork"       
[4857] "hhwkfair"        "hhwkdis"         "deckids"         "spborn"         
[4861] "weekend"         "buythngs"        "timehome"        "strsshme"       
[4865] "timework"        "strsswrk"        "tiredhme"        "jobvsfam"       
[4869] "tiredwrk"        "famvswrk"        "happy7"          "satjob7"        
[4873] "satfam7"         "fewknokd"        "twoincs1"        "earnshh"        
[4877] "ssfchild"        "ssmchild"        "kidfinbu"        "kidjob"         
[4881] "kidsocst"        "eldersup"        "paidlv"          "paidlvpy"       
[4885] "paidlvdv"        "famwkbst"        "famwklst"        "careprov"       
[4889] "carecost"        "eldhelp"         "eldcost"         "hhclean1"       
[4893] "wkndact"         "tiredhm1"        "jobvsfa1"        "tiredwk1"       
[4897] "famvswk1"        "wkkidscl"        "wkyngscl"        "wkkidscs"       
[4901] "wkyngscs"        "rfamlook"        "spfalook"        "splive"         
[4905] "timepdwk"        "timehhwk"        "timefam"         "timefrnd"       
[4909] "timeleis"        "timerelx"        "wrkearn"         "wrkenjoy"       
[4913] "wrkimp"          "hwduties"        "yrsfirm"         "dowell"         
[4917] "expernc"         "paysame"         "ageemp"          "sexemp"         
[4921] "famresp"         "educemp"         "dk"              "bosswrks"       
[4925] "strngun"         "secjob"          "hiinc"           "promotn"        
[4929] "leisure"         "intjob"          "wrkindp"         "hlpoths"        
[4933] "hlpsoc"          "flexhrs"         "flexhrs1"        "wkpersnl"       
[4937] "famorjob"        "joborfam"        "discwk5"         "whydisc5"       
[4941] "harass5"         "unionsbd"        "rcontact"        "wkathome"       
[4945] "wkwkends"        "decidwrk"        "wrkshift"        "chngewrk"       
[4949] "nounemp5"        "nounemp6"        "extrawrk"        "extraern"       
[4953] "jbendyr"         "jbendmo"         "exjobsat"        "wornojob"       
[4957] "newskill"        "lowpay"          "tempwork"        "mortravl"       
[4961] "moveinus"        "moveaway"        "econsup1"        "worecsup"       
[4965] "unpeople"        "unmoney"         "unslfcon"        "unrespct"       
[4969] "unfamten"        "unjobexp"        "unbored"         "undk"           
[4973] "empself"         "smallbig"        "indusoth"        "privgovt"       
[4977] "workweek"        "wantjob"         "findjob"         "iwrkhard"       
[4981] "hrsmoney"        "ryrsfirm"        "rdowell"         "rpaysame"       
[4985] "rexpernc"        "rageemp"         "rfamresp"        "reducemp"       
[4989] "rdk"             "rsecjob"         "rhiinc"          "rpromotn"       
[4993] "rleisure"        "rintjob"         "rwrkindp"        "rhlpoths"       
[4997] "rhlpsoc"         "rflexhrs"        "xhaustn"         "physwrk"        
[5001] "stress"          "boredom"         "danger"          "unhlthy"        
[5005] "unpleznt"        "planwrk"         "findwork"        "bossemps"       
[5009] "cowrkers"        "jobsat"          "supervis"        "suprvsjb"       
[5013] "supnum"          "moonlite"        "othhrs"          "numsites"       
[5017] "localnum"        "totalnum"        "employer"        "numemply"       
[5021] "paydojob"        "payfam"          "payeduc"         "paytime"        
[5025] "techjobs"        "techwork"        "wantjob1"        "worknow"        
[5029] "sethours"        "placewrk"        "wktenure"        "useskill"       
[5033] "edcskill"        "jobskill"        "helporg1"        "prideorg"       
[5037] "chngwork"        "stayorg3"        "proudwrk"        "absent"         
[5041] "leavejob"        "worryjob"        "evjob"           "yrjobend"       
[5045] "whyjbend"        "wantjob2"        "getjob"          "lookjob"        
[5049] "pubagncy"        "priagncy"        "wantads"         "adforjob"       
[5053] "appemps"         "askhelp"         "econsup"         "selfemp1"       
[5057] "selfemp2"        "unjobsec"        "unbetter"        "rimpskls"       
[5061] "dailywrk"        "timeoff"         "jbintfam"        "famintjb"       
[5065] "newjob"          "jbtrain"         "jobeasy"         "replaceu"       
[5069] "nounemp1"        "nounemp2"        "nounemp3"        "nounemp4"       
[5073] "otherwrk"        "skltrain"        "spwrkgvt"        "hapunhap"       
[5077] "stiffpun"        "deathpen"        "premars1"        "xmarsex1"       
[5081] "homosex1"        "abdefct1"        "abpoor1"         "abdefctw"       
[5085] "abpoorw"         "taxcheat"        "govcheat"        "concong"        
[5089] "conbiz"          "congovt"         "conchurh"        "concourt"       
[5093] "conschls"        "polsgod"         "clergvte"        "religpub"       
[5097] "clerggov"        "churhpow"        "godchnge"        "afterlif"       
[5101] "devil"           "heaven"          "hell"            "miracles"       
[5105] "bible1"          "theism"          "fatalism"        "godmeans"       
[5109] "nihilism"        "predeter"        "egomeans"        "ownfate"        
[5113] "relexper"        "marelkid"        "madenkid"        "parelkid"       
[5117] "padenkid"        "religkid"        "denkid"          "religsp"        
[5121] "densp"           "attendma"        "attendpa"        "attend12"       
[5125] "prayfreq"        "relactiv"        "relactiv1"       "relscrpt"       
[5129] "feelrel"         "schlpray"        "godright"        "socright"       
[5133] "perright"        "antirel"         "befair"          "cantrust"       
[5137] "trustsci"        "religcon"        "religint"        "religinf"       
[5141] "volwkpol"        "volwkchr"        "volwkrel"        "volwkoth"       
[5145] "reltruth"        "carright"        "cardo"           "geomobil"       
[5149] "relgrpeq"        "rspctrel"        "relmarry"        "relcand"        
[5153] "relext1"         "relext2"         "relext3"         "reincar"        
[5157] "nirvana"         "ancestrs"        "mywaygod"        "relgeneq"       
[5161] "relobjct"        "vistholy"        "relsprt"         "paxhappy"       
[5165] "makefrnd"        "comfort"         "rightpeo"        "relgenbar"      
[5169] "govvsrel"        "difrel"          "relpast"         "relrlvnt"       
[5173] "christns"        "muslims"         "hindus"          "buddhsts"       
[5177] "jews"            "atheists"        "perscrfc"        "obeythnk"       
[5181] "privent"         "postmat1"        "postmat2"        "scifaith"       
[5185] "harmgood"        "sciworse"        "scigrn"          "grnecon"        
[5189] "harmsgrn"        "anrights"        "resnatur"        "grnprog"        
[5193] "naturpax"        "grwthelp"        "antests"         "naturwar"       
[5197] "grwtharm"        "naturgod"        "grnprice"        "grntaxes"       
[5201] "grnsol"          "toodifme"        "ihlpgrn"         "scitest1"       
[5205] "scitest2"        "scitest3"        "scitest4"        "scitest5"       
[5209] "grntest1"        "grntest2"        "grntest3"        "grntest4"       
[5213] "grntest5"        "grntest6"        "grntest7"        "carsgen"        
[5217] "carsfam"         "carsten"         "nukegen"         "nukefam"        
[5221] "indusgen"        "indusfam"        "chemgen"         "chemfam"        
[5225] "watergen"        "waterfam"        "tempgen"         "tempfam"        
[5229] "pubdecid"        "busdecid"        "usdoenuf"        "recycle"        
[5233] "chemfree"        "nomeat"          "drivless"        "grngroup"       
[5237] "grnsign"         "grnmoney"        "grndemo"         "comtype"        
[5241] "popgrwth"        "impgrn"          "othssame"        "grnexagg"       
[5245] "genegen"         "amprogrn"        "bizpeop"         "govtbiz"        
[5249] "peopgovt"        "grnintl"         "ldcgrn"          "econgrn"        
[5253] "nukeacc"         "infobiz"         "infogrn"         "infogovt"       
[5257] "infonews"        "infotv"          "infocol"         "excldimm"       
[5261] "topprob1"        "topprob2"        "trust5"          "fair5"          
[5265] "grncon"          "enprbus"         "enprbfam"        "knwcause"       
[5269] "knowsol"         "futenrgy"        "helpharm"        "grneffme"       
[5273] "tempgen1"        "busgrn"          "peopgrn"         "redcehme"       
[5277] "h2oless"         "nobuygrn"        "clsenei"         "clsetown"       
[5281] "clsestat"        "clseusa"         "clsenoam"        "movenei"        
[5285] "movetown"        "movestat"        "moveusa"         "movenoam"       
[5289] "onenatn"         "ambornin"        "amcit"           "amlived"        
[5293] "amenglsh"        "amchrstn"        "amgovt"          "amfeel"         
[5297] "amcitizn"        "amshamed"        "belikeus"        "ambetter"       
[5301] "ifwrong"         "amsports"        "prouddem"        "proudpol"       
[5305] "proudeco"        "proudsss"        "proudsci"        "proudspt"       
[5309] "proudart"        "proudmil"        "proudhis"        "proudgrp"       
[5313] "imports"         "wrldgovt"        "forlang"         "amownway"       
[5317] "forland"         "amtv"            "amcult"          "mincult"        
[5321] "meltpot1"        "immcrime"        "immameco"        "immjobs"        
[5325] "immideas"        "letin1"          "refugees"        "res161"         
[5329] "livecom1"        "abroad"          "spkhome1"        "spkhome2"       
[5333] "spklang1"        "spklang2"        "spklang3"        "citizen"        
[5337] "parcit"          "ethclose"        "nafta1"          "nafta2"         
[5341] "socid1"          "socid2"          "socid3"          "amancstr"       
[5345] "lessprd"         "intlincs"        "freetrde"        "decsorgs"       
[5349] "powrorgs"        "citworld"        "forcult"         "internet"       
[5353] "immimp"          "immcosts"        "kidshere"        "kidsaway"       
[5357] "immrghts"        "amproud1"        "nafta2a"         "nafta3"         
[5361] "shortcom"        "immcult"         "immeduc"         "letin1a"        
[5365] "immassim"        "patriot1"        "patriot2"        "patriot3"       
[5369] "patriot4"        "voteelec"        "paytaxes"        "obeylaws"       
[5373] "watchgov"        "actassoc"        "othreasn"        "buypol"         
[5377] "helpusa"         "helpwrld"        "milserve"        "relmeet"        
[5381] "revmeet"         "racmeet"         "signdpet"        "avoidbuy"       
[5385] "joindem"         "attrally"        "cntctgov"        "polfunds"       
[5389] "usemedia"        "interpol"        "grpparty"        "grpwork"        
[5393] "grprelig"        "grpsprts"        "grpother"        "solok"          
[5397] "rghtsmin"        "eqtreat"         "citviews"        "polopts"        
[5401] "oppsegov"        "poleff18"        "poleff19"        "poleff20"       
[5405] "actlaw"          "affctlaw"        "polint1"         "govdook"        
[5409] "polgreed"        "discpol"         "chngeoth"        "powerun"        
[5413] "govngos"         "unrghts"         "polactve"        "choices"        
[5417] "refrndms"        "elecvote"        "elecfair"        "servepeo"       
[5421] "fixmistk"        "corruptn"        "demtoday"        "dem10pst"       
[5425] "dem10fut"        "demrghts"        "gvtrghts"        "polinter"       
[5429] "polnews"         "crimlose"        "ntcitvte"        "notvote"        
[5433] "hlthall"         "leftrght"        "creation"        "scitesty"       
[5437] "big5a1"          "big5b1"          "big5c1"          "big5d1"         
[5441] "big5e1"          "big5a2"          "big5b2"          "big5c2"         
[5445] "big5d2"          "big5e2"          "forbdcom"        "forbdrac"       
[5449] "forbdmar"        "allowcom"        "allowrac"        "allowmar"       
[5453] "cideknew"        "cidewho"         "cidesex"         "cideage"        
[5457] "ciderace"        "cidereg"         "cidewho2"        "cidesex2"       
[5461] "cideage2"        "ciderac2"        "cidereg2"        "cidewho3"       
[5465] "cidesex3"        "cideage3"        "ciderac3"        "cidereg3"       
[5469] "aidsknow"        "aidswho"         "aidsdead"        "aidssex"        
[5473] "aidsage"         "aidsrace"        "aidsreg"         "aidswho2"       
[5477] "aidsded2"        "aidssex2"        "aidsage2"        "aidsrac2"       
[5481] "aidsreg2"        "aidswho3"        "aidsded3"        "aidssex3"       
[5485] "aidsage3"        "aidsrac3"        "aidsreg3"        "suiknew"        
[5489] "suiwho"          "suisex"          "suiage"          "suirace"        
[5493] "suireg"          "suiwho2"         "suisex2"         "suiage2"        
[5497] "suirac2"         "suireg2"         "suiwho3"         "suisex3"        
[5501] "suiage3"         "suirac3"         "suireg3"         "aidssch"        
[5505] "aidsads"         "aidsinsr"        "aidshlth"        "aidsmar"        
[5509] "aidssxed"        "aidsids"         "aidsfare"        "partners"       
[5513] "matesex"         "frndsex"         "acqntsex"        "pikupsex"       
[5517] "paidsex"         "othersex"        "sexsex"          "sexfreq"        
[5521] "sexfreq1"        "sexfreq2"        "numwomen"        "nummen"         
[5525] "partopen"        "partopn5"        "partnrs5"        "sexsex5"        
[5529] "evpaidsx"        "evstray"         "condom"          "relatsex"       
[5533] "evidu"           "idu30"           "evcrack"         "crack30"        
[5537] "hivtest"         "hivtest1"        "hivtest2"        "aidslook"       
[5541] "aidscndm"        "hivvac"          "hivkiss"         "sexornt"        
[5545] "sexbirth"        "sexnow"          "siborder"        "genetest"       
[5549] "genetst1"        "genegood"        "genegoo1"        "genegoo2"       
[5553] "geneself"        "geneabrt"        "maleornt"        "geneself2"      
[5557] "geneabrt2"       "genedef1"        "genedef2"        "genedef3"       
[5561] "parhardr"        "parworse"        "parrght"         "parwhere"       
[5565] "parfin"          "pargovt"         "partime"         "parwork"        
[5569] "partaxes"        "rolema"          "rolepa"          "rolegp"         
[5573] "roleccp"         "roletchr"        "roleclrg"        "chldeduc"       
[5577] "chldlove"        "chldsafe"        "chldmorl"        "chldsup"        
[5581] "chldhome"        "chldhlth"        "chldskls"        "chldtime"       
[5585] "inffilms"        "infpubtv"        "infnettv"        "infadstv"       
[5589] "infmusic"        "sppregnt"        "sphlthkd"        "spheadst"       
[5593] "sppoorkd"        "spwrkpar"        "sphomekd"        "spdsabkd"       
[5597] "spdrugs"         "spfoodkd"        "sppill"          "prob1"          
[5601] "prob2"           "prob3"           "prob4"           "hlth1"          
[5605] "hlth2"           "hlth3"           "hlth4"           "hlth5"          
[5609] "hlth6"           "hlth7"           "hlth8"           "hlth9"          
[5613] "hlth10"          "hlth11"          "hlth12"          "hlth13"         
[5617] "hlth14"          "work1"           "work2"           "work3"          
[5621] "work4"           "work5"           "work6"           "work7"          
[5625] "work8"           "work9"           "work10"          "finan1"         
[5629] "finan2"          "finan3"          "finan4"          "finan5"         
[5633] "hrdshp1"         "hrdshp2"         "hrdshp3"         "hrdshp4"        
[5637] "hrdshp5"         "hrdshp6"         "hrdshp7"         "famper1"        
[5641] "famper2"         "famper3"         "famper4"         "famper5"        
[5645] "famper6"         "law1"            "law2"            "law3"           
[5649] "law4"            "law5"            "law6"            "law7"           
[5653] "live1"           "live2"           "live3"           "live4"          
[5657] "oth1"            "oth2"            "oth3"            "oth4"           
[5661] "oth5"            "extra1"          "extra2"          "povline"        
[5665] "incdef"          "realinc"         "realrinc"        "coninc"         
[5669] "conrinc"         "minfour"         "minfood"         "minthree"       
[5673] "sectech"         "secdocs"         "rptcowrk"        "askfinan"       
[5677] "askcrime"        "askdrugs"        "askmentl"        "askforgn"       
[5681] "askdrink"        "asksexor"        "askfrbiz"        "askfrtrv"       
[5685] "askcomp"         "secprvcy"        "secdiplo"        "secmilop"       
[5689] "secterr"         "secbudgt"        "chkfinan"        "chkspfin"       
[5693] "chktaxes"        "knomentl"        "takearms"        "leakinfo"       
[5697] "spyenemy"        "spyfrend"        "taketrck"        "punarms"        
[5701] "punleak"         "punenmy"         "punfrnd"         "puntrck"        
[5705] "comsteal"        "comdata"         "comsys"          "comsnoop"       
[5709] "comemail"        "comporn"         "lietest"         "testdrug"       
[5713] "bugging"         "finanqs"         "chkonjob"        "chkother"       
[5717] "compfin"         "chktravl"        "emailwrk"        "emailhme"       
[5721] "tapwrk"          "taphme"          "srchwrk"         "camwrk"         
[5725] "usspy"           "forspy"          "usterror"        "frterror"       
[5729] "forsteal"        "nuclrwar"        "ethnic"          "eth1"           
[5733] "eth2"            "eth3"            "ethnum"          "spethnic"       
[5737] "speth1"          "speth2"          "speth3"          "spethnum"       
[5741] "racesee"         "racedbtf"        "raceself"        "hispanic"       
[5745] "racecen1"        "racecen2"        "racecen3"        "difrace1"       
[5749] "difrace2"        "difrace3"        "racethwh"        "racethhi"       
[5753] "racethbl"        "racethas"        "racethna"        "racethot"       
[5757] "racethmn"        "uscitzn"         "fucitzn"         "yearsusa"       
[5761] "mnthsusa"        "vetyears"        "vetkind"         "workdy"         
[5765] "workhr"          "spdays"          "sphour"          "dwelling"       
[5769] "dwelngh"         "dwelcity"        "dwelown"         "dwelown16"      
[5773] "worda"           "wordb"           "wordc"           "wordd"          
[5777] "worde"           "wordf"           "wordg"           "wordh"          
[5781] "wordi"           "wordj"           "wordsum"         "godoc"          
[5785] "eatout"          "seefilm"         "attrelig"        "numdays"        
[5789] "sunday"          "monday"          "tuesday"         "wednesdy"       
[5793] "thursday"        "friday"          "saturday"        "attreg"         
[5797] "mediarel"        "othrel"          "othrel1"         "othrel2"        
[5801] "othrel3"         "attweek"         "religid"         "relid1"         
[5805] "relid2"          "relid3"          "relidbst"        "cathid"         
[5809] "charisma"        "relate1"         "gender1"         "old1"           
[5813] "mar1"            "away1"           "where1"          "relate2"        
[5817] "gender2"         "old2"            "mar2"            "away2"          
[5821] "where2"          "relate3"         "gender3"         "old3"           
[5825] "mar3"            "away3"           "where3"          "relate4"        
[5829] "gender4"         "old4"            "mar4"            "away4"          
[5833] "where4"          "relate5"         "gender5"         "old5"           
[5837] "mar5"            "away5"           "where5"          "relate6"        
[5841] "gender6"         "old6"            "mar6"            "away6"          
[5845] "where6"          "relate7"         "gender7"         "old7"           
[5849] "mar7"            "away7"           "where7"          "relate8"        
[5853] "gender8"         "old8"            "mar8"            "away8"          
[5857] "where8"          "relate9"         "gender9"         "old9"           
[5861] "mar9"            "away9"           "where9"          "relate10"       
[5865] "gender10"        "old10"           "mar10"           "away10"         
[5869] "where10"         "relate11"        "gender11"        "old11"          
[5873] "mar11"           "away11"          "where11"         "relate12"       
[5877] "gender12"        "old12"           "mar12"           "away12"         
[5881] "where12"         "relate13"        "gender13"        "old13"          
[5885] "mar13"           "away13"          "where13"         "relate14"       
[5889] "gender14"        "old14"           "mar14"           "away14"         
[5893] "where14"         "relhhd1"         "relhhd2"         "relhhd3"        
[5897] "relhhd4"         "relhhd5"         "relhhd6"         "relhhd7"        
[5901] "relhhd8"         "relhhd9"         "relhhd10"        "relhhd11"       
[5905] "relhhd12"        "relhhd13"        "relhhd14"        "hefinfo"        
[5909] "hhrace"          "respnum"         "hhtype"          "hhtype1"        
[5913] "famgen"          "rplace"          "rvisitor"        "visitors"       
[5917] "relhh1"          "relhh2"          "relhh3"          "relhh4"         
[5921] "relhh5"          "relhh6"          "relhh7"          "relhh8"         
[5925] "relhh9"          "relhh10"         "relhh11"         "relhh12"        
[5929] "relhh13"         "relhh14"         "relsp1"          "relsp2"         
[5933] "relsp3"          "relsp4"          "relsp5"          "relsp6"         
[5937] "relsp7"          "relsp8"          "relsp9"          "relsp10"        
[5941] "relsp11"         "relsp12"         "relsp13"         "relsp14"        
[5945] "dateintv"        "isco68"          "paisco68"        "spisco68"       
[5949] "isco681"         "paisc681"        "maisc681"        "spisc681"       
[5953] "isco88"          "paisco88"        "maisco88"        "spisco88"       
[5957] "isco08"          "paisco08"        "maisco08"        "spisco08"       
[5961] "coisco08"        "sei"             "firstsei"        "pasei"          
[5965] "masei"           "spsei"           "sei10"           "sei10educ"      
[5969] "sei10inc"        "pasei10"         "pasei10educ"     "pasei10inc"     
[5973] "masei10"         "masei10educ"     "masei10inc"      "spsei10"        
[5977] "spsei10educ"     "spsei10inc"      "cosei10"         "cosei10educ"    
[5981] "cosei10inc"      "copres10"        "copres105plus"   "uswar"          
[5985] "uswary"          "usintl"          "usun"            "commun"         
[5989] "commun10"        "russia"          "japan"           "england"        
[5993] "canada"          "brazil"          "china"           "israel"         
[5997] "egypt"           "welfare1"        "welfare2"        "welfare3"       
[6001] "welfare4"        "welfare5"        "welfare6"        "wkcontct"       
[6005] "talkspvs"        "effctsup"        "cohort"          "marcohrt"       
[6009] "zodiac"          "inthisp"         "intrace1"        "intrace2"       
[6013] "intrace3"        "bthgrp1a"        "bthgrp1b"        "bthgrp1c"       
[6017] "bthgrp1d"        "bthgrp1e"        "bthgrp1f"        "bthgrp2a"       
[6021] "bthgrp2b"        "bthgrp2c"        "bthgrp2d"        "bthgrp2e"       
[6025] "bthgrp2f"        "bthgrp3a"        "bthgrp3b"        "bthgrp3c"       
[6029] "bthgrp3d"        "bthgrp3e"        "bthgrp3f"        "bthgrp4a"       
[6033] "bthgrp4b"        "bthgrp4c"        "bthgrp4d"        "bthgrp4e"       
[6037] "bthgrp4f"        "bthgrp5a"        "bthgrp5b"        "bthgrp5c"       
[6041] "bthgrp5d"        "bthgrp5e"        "bthgrp5f"        "frstgrp1"       
[6045] "frstgrp2"        "frstgrp3"        "frstgrp4"        "frstgrp5"       
[6049] "whoelse1"        "whoelse2"        "whoelse3"        "whoelse4"       
[6053] "whoelse5"        "whoelse6"        "saqissp"         "saqsex"         
[6057] "saqgene"         "intid"           "feeused"         "feelevel"       
[6061] "lngthinv"        "intage"          "easyget"         "intethn"        
[6065] "mode"            "intsex"          "intyrs"          "consent"        
[6069] "adminconsent"    "pilloky"         "popespky"        "polhitoy"       
[6073] "letdie1y"        "death"           "ballot"          "version"        
[6077] "issp"            "formwt"          "sampcode"        "sample"         
[6081] "oversamp"        "phase"           "spanself"        "spanint"        
[6085] "spaneng"         "res2006"         "res2008"         "res2010"        
[6089] "res2012"         "cshutyp06"       "cshutyp08"       "cshutyp10"      
[6093] "cshutyp12"       "hlthstrt"        "huadd"           "huaddwhy"       
[6097] "dwellpre"        "kidsinhh"        "respond"         "incuspop"       
[6101] "neisafe"         "rlooks"          "rgroomed"        "rweight"        
[6105] "rhlthend"        "wtss"            "wtssnr"          "wtssall"        
[6109] "vstrat"          "vpsu"            "kish"            "famdif16y"      
[6113] "pawrkslf2"       "pawrkslffam"     "mawrkslf2"       "mawrkslffam"    
[6117] "ethworld1"       "ethworld2"       "ethworld3"       "ethworld4"      
[6121] "ethworld5"       "ethworld6"       "ethworld7"       "ethworld8"      
[6125] "ethworld9"       "ethregion1"      "ethregion2"      "ethregion3"     
[6129] "ethregion4"      "ethregion5"      "ethregion6"      "ethregion7"     
[6133] "ethregion8"      "ethregion9"      "ethregion10"     "ethregion11"    
[6137] "ethregion12"     "ethregion13"     "ethregion14"     "ethregion15"    
[6141] "ethregion16"     "ethregion17"     "ethregion18"     "ethregion19"    
[6145] "ethregion20"     "ethregion21"     "ethregion22"     "ethregion23"    
[6149] "ethregion24"     "ethregion25"     "ethregion26"     "ethregion27"    
[6153] "ethregion28"     "ethregion29"     "ethregion30"     "ethregion31"    
[6157] "ethregion32"     "ethregion33"     "ethregion34"     "ethregion35"    
[6161] "ethregion36"     "ethregion37"     "ethregion38"     "ethregion39"    
[6165] "ethregion40"     "ethregion41"     "ethregion42"     "ethregion43"    
[6169] "ethregion44"     "ethregion45"     "ethregion46"     "ethregion47"    
[6173] "ethregion48"     "ethregion49"     "ethregion50"     "ethregion51"    
[6177] "ethregion52"     "ethregion53"     "ethregion54"     "ethregion55"    
[6181] "ethregion56"     "ethregion57"     "ethregion58"     "ethregion59"    
[6185] "ethregion60"     "ethregion61"     "ethregion62"     "ethregion63"    
[6189] "ethregion64"     "ethregion65"     "ethregion66"     "ethregion67"    
[6193] "ethregion68"     "ethregion69"     "ethregion70"     "ethregion71"    
[6197] "ethregion72"     "ethregion73"     "ethregion74"     "ethregion75"    
[6201] "ethregion76"     "ethregion77"     "ethregion78"     "ethregion79"    
[6205] "ethregion80"     "ethregion81"     "ethregion82"     "ethregion83"    
[6209] "ethregion84"     "ethregion85"     "ethregion86"     "ethregion87"    
[6213] "ethregion88"     "ethregion89"     "ethregion90"     "ethregion91"    
[6217] "ethregion92"     "ethregion93"     "ethregion94"     "ethregion95"    
[6221] "wrkgovt1"        "wrkgovt2"        "spkathy"         "libathy"        
[6225] "spkracy"         "libracy"         "spkcomy"         "colcomy"        
[6229] "libcomy"         "spkmily"         "libmily"         "spkhomoy"       
[6233] "libhomoy"        "spkmslmy"        "libmslmy"        "polhitoky"      
[6237] "polabusey"       "polattaky"       "raceacs1"        "raceacs2"       
[6241] "raceacs3"        "raceacs4"        "raceacs5"        "raceacs6"       
[6245] "raceacs7"        "raceacs8"        "raceacs9"        "raceacs10"      
[6249] "raceacs11"       "raceacs12"       "raceacs13"       "raceacs14"      
[6253] "raceacs15"       "raceacs16"       "abdefectg"       "abnomoreg"      
[6257] "abhlthg"         "abpoorg"         "abrapeg"         "absingleg"      
[6261] "suicide1g"       "suicide2g"       "suicide3g"       "suicide4g"      
[6265] "maborn"          "paborn"          "sexbirth1"       "sexnow1"        
[6269] "goveqinc1"       "immlimit"        "trresrch"        "trmedia"        
[6273] "trbusind"        "trlegis"         "clmtcaus"        "clmtwrld"       
[6277] "clmtusa"         "naturdev"        "indusgen1"       "chemgen1"       
[6281] "watergen1"       "genegen1"        "nukegen1"        "enjoynat"       
[6285] "activnat"        "planetrp"        "carhr"           "eatmeat"        
[6289] "numrooms"        "airpollu"        "wtrpollu"        "exweathr"       
[6293] "opbribes"        "mkt1"            "respineq"        "govineq1"       
[6297] "govineq2"        "ineqmad"         "migrpoor"        "conimm"         
[6301] "rank1"           "rank16"          "rank10fut"       "fairdist"       
[6305] "contpoor"        "contrich"        "endsme12"        "skipmeal"       
[6309] "class1"          "ratepain1"       "norelgsp"        "evangclx"       
[6313] "evangcly"        "religimp"        "relidimp"        "relidesc"       
[6317] "relidwe"         "relidins"        "biblauth"        "evngelze"       
[6321] "sinsacri"        "chrstsav"        "sprtconnct"      "sprtlrgr"       
[6325] "sprtpurp"        "mditate1"        "grtwrks"         "freemind"       
[6329] "decevidc"        "advfmsci"        "prochoic"        "prolife"        
[6333] "godusa"          "govchrst"        "buseqinc"        "trdunio1"       
[6337] "boardrep"        "upwages"         "limitpay"        "govfnanc"       
[6341] "dclindus"        "govfnaid"        "hivafraid"       "hivimmrl"       
[6345] "hivdscrm"        "ptnrornt"        "ptnrsxbrth"      "ptnrsxnow"      
[6349] "poltrtblk"       "poltrthsp"       "defund"          "strvbias"       
[6353] "strvbiasy"       "racesurv17"      "conpharvac"      "conpharvacy"    
[6357] "confedvac"       "confedvacy"      "wtssps"          "wtssnrps"       
[6361] "uswaryv"         "prayerv"         "courtsv"         "discaffwv"      
[6365] "racopenv"        "getaheadv"       "divlawv"         "helpfulv"       
[6369] "fairv"           "trustv"          "agedv"           "grassv"         
[6373] "relitenv"        "biblev"          "postlifev"       "kidssolv"       
[6377] "uscitznv"        "fucitznv"        "fepolv"          "uswarynv"       
[6381] "prayernv"        "courtsnv"        "discaffwnv"      "racopennv"      
[6385] "getaheadnv"      "divlawnv"        "helpfulnv"       "fairnv"         
[6389] "trustnv"         "agednv"          "grassnv"         "relitennv"      
[6393] "biblenv"         "postlifenv"      "kidssolnv"       "uscitznnv"      
[6397] "fucitznnv"       "fepolnv"         "scibnftsv"       "abanyg"         
[6401] "fileversion"     "ballotformwt"    "ballotformwtnr"  "vietdraft"      
[6405] "spwrkslf2"       "spwrkslffam"     "childsinhh"      "adultsinhh"     
[6409] "whatsp2"         "cowrkslf2"       "cowrkslffam"     "cowksup"        
[6413] "whatco2"         "whatpa2"         "whatma2"         "whatslf2"       
[6417] "racerank1"       "racerank2"       "racerank3"       "adoptus"        
[6421] "immfate"         "letinhsp1"       "letinasn1"       "xmoviey"        
[6425] "vote20"          "pres20"          "if20who"         "wordk"          
[6429] "wordl"           "wordn"           "fechld2"         "fepresch2"      
[6433] "rspgndr"         "prntlk"          "prntfnce"        "prntcre"        
[6437] "prntply"         "prntbhav"        "prntadvs"        "prntmdl"        
[6441] "orginc"          "plan1"           "sharehhw"        "clsrltv"        
[6445] "rsprltv1"        "rsprltv2"        "eldfnce"         "rlyrltv"        
[6449] "frndfam"         "cabgndr"         "univgndr"        "execgndr"       
[6453] "yrfnce"          "nmbrkids"        "conhlth"         "hlthbtr"        
[6457] "hlthmore"        "hlthgov"         "hlthinf"         "hlthtax"        
[6461] "hlthctzn"        "hlthdmg"         "hlthacc1"        "hlthacc2"       
[6465] "hlthacc3"        "hlthacc4"        "hlthbeh"         "hlthenv"        
[6469] "hlthgene"        "hlthpoor"        "altmed"          "doctrst"        
[6473] "docskls"         "docearn"         "hlthweb"         "hlthwblif"      
[6477] "hlthwbanx"       "hlthwbvax"       "webhltbeh"       "webdocexp"      
[6481] "websympt"        "webdradv"        "webrely"         "vaxdoharm"      
[6485] "immunbetr"       "hlthprb"         "hlthpain"        "hlthdep"        
[6489] "hlthconf"        "hlthnot"         "docvst"          "docalt"         
[6493] "medpay"          "medcommt"        "medwtlst"        "medbest"        
[6497] "hlthsat"         "docsat1"         "altsat"          "smokeday"       
[6501] "drinkday1"       "physact"         "frtvegs"         "disblty"        
[6505] "weight_issp"     "shutbus"         "stayhome"        "mobilsurv"      
[6509] "reqmasks"        "bangather"       "stockval1"       "stockyr"        
[6513] "stockyrval"      "stockoptyr"      "stoptyramt"      "extr2021"       
[6517] "extraval1"       "yearval1"        "numorg1"         "perfrt"         
[6521] "knowschd1"       "wrkmeangfl"      "strmgtsup"       "psysamephys"    
[6525] "allorglevel"     "feelnerv"        "worry"           "feeldown"       
[6529] "nointerest"      "svyenjoy"        "svyid1"          "svyid2"         
[6533] "yrlvmus"         "yrartxbt"        "yrmovie"         "artsout"        
[6537] "yrcreat"         "yrrdg"           "yrtour"          "yrstmus"        
[6541] "yrarmus"         "yrstpo"          "yrarpo"          "yrclass"        
[6545] "yrpod"           "cvdlvmus"        "cvdart"          "cvdmov"         
[6549] "cvdcreat"        "cvdrdg"          "cvdtour"         "cvdstmus"       
[6553] "cvdarmus"        "cvdstpo"         "cvdarpo"         "cvdclass"       
[6557] "cvdpod"          "neastatus"       "wrkwayup_next"   "blkmblty"       
[6561] "blkdsrv"         "blktry"          "brv5"            "brv5sp"         
[6565] "brv5par"         "brv5grand"       "brv5child"       "brv5sib"        
[6569] "brv5oth"         "brv5spnum"       "brv5partnum"     "brv5dadnum"     
[6573] "brv5momnum"      "brv5filnum"      "brv5milnum"      "brv5gmanum"     
[6577] "brv5gpanum"      "brv5sonnum"      "brv5daunum"      "brv5chinum"     
[6581] "brv5bronum"      "brv5sisnum"      "brv5silnum"      "brv5cuznum"     
[6585] "brv5frndnum"     "brv5cowknum"     "brv5othnum"      "brv16"          
[6589] "brv16sp"         "brv16par"        "brv16sib"        "brv16grand"     
[6593] "brv16oth"        "brv16spnum"      "brv16partnum"    "brv16dadnum"    
[6597] "brv16momnum"     "brv16filnum"     "brv16milnum"     "brv16gmanum"    
[6601] "brv16gpanum"     "brv16bronum"     "brv16sisnum"     "brv16silnum"    
[6605] "brv16cuznum"     "brv16frndnum"    "brv16othnum"     "gestate"        
[6609] "abgender"        "abbelief"        "vaxhstncy"       "vaxkids"        
[6613] "vaxsafe"         "fluvax"          "covid12"         "covemply"       
[6617] "pandinc"         "pandmet"         "biokids"         "malekids"       
[6621] "firstkidsex"     "nonbinkids"      "femself"         "mascself"       
[6625] "relig_next"      "denom_next"      "jew_next"        "nextstatus"     
[6629] "racdif1x"        "racdif2x"        "racdif3x"        "racdif4x"       
[6633] "worksick"        "indus10_next"    "occ10_next"      "other_next"     
[6637] "fund_next"       "hompop_exp"      "modesequence"    "rheight"        
[6641] "instype01"       "instype02"       "instype03"       "instype04"      
[6645] "totalincentive"  "kidsund18"       "babies_exp"      "preteen_exp"    
[6649] "teens_exp"       "adults_exp"      "lngrltnshp"      "rsblng18"       
[6653] "rchild18"        "rprnt18"         "rbioprnt18"      "radptprnt18"    
[6657] "rstpprnt18"      "rgprnt18"        "rfmly18"         "rntrltd18"      
[6661] "rrltu18"         "rnrltu18"        "rgprntu18"       "rbioprnt"       
[6665] "radptprnt"       "rstpprnt"        "prnt"            "childs_exp"     
[6669] "respnumh"        "hefinfo1"        "famgen_exp"      "agehef1"        
[6673] "agehef2"         "agehef3"         "agehef4"         "agehef5"        
[6677] "agehef6"         "agehef7"         "agehef8"         "agehef9"        
[6681] "agehef10"        "agehef11"        "agehef12"        "agehef13"       
[6685] "agehef14"        "hompoph"         "hhtype1_exp"     "batch"          
[6689] "subsamprate"     "wtssps_nea"      "wtssnrps_nea"    "wtssps_next"    
[6693] "wtssnrps_next"   "neaeligible"     "nexteligible"    "pawrkgrw"       
[6697] "conlabory"       "racdif5"         "marsamey"        "mobiledata"     
[6701] "broadband"       "rateincumb24"    "ratechall124"    "ratechall224"   
[6705] "ratechall324"    "ratedemp"        "raterepp"        "ratemaga"       
[6709] "lkelyvot"        "whovote24a"      "econstat"        "polintrst"      
[6713] "intrnetuse"      "nouseint1"       "nouseint2"       "nouseint3"      
[6717] "nouseint4"       "nouseint5"       "nouseint6"       "nouseint7"      
[6721] "nouseint8"       "nouseint9"       "nouseint10"      "nouseint11"     
[6725] "nouseint12"      "intaccprxy"      "prxyuse"         "ftruse"         
[6729] "inthome"         "intprfssnl"      "intpub"          "intbhlf"        
[6733] "unplug"          "unplgrsn"        "intskill"        "intsurf"        
[6737] "intliteracy"     "intapps"         "intcomm"         "intshare"       
[6741] "intsearch"       "intgame"         "intstream"       "intfncl"        
[6745] "intmeet"         "intlnly"         "inttrig"         "intnews"        
[6749] "intcnfrm"        "intrust"         "intpolview"      "intoppo"        
[6753] "intviews"        "techesy"         "harmgood1"       "nextgen1"       
[6757] "intscam"         "inthrss"         "polnewsfrom"     "smnews"         
[6761] "tvnews1"         "papernews"       "radionews"       "webnews"        
[6765] "modepet"         "modeprot"        "modelobby"       "modeorgprot"    
[6769] "modeorg"         "trppl"           "trcong"          "dataprot"       
[6773] "emonitor1"       "infodeal"        "infoprofit"      "gendtech"       
[6777] "agetech"         "urbantech"       "eductech"        "classtech"      
[6781] "aiworry"         "aimed"           "aidrive"         "owndecns"       
[6785] "brneffrt"        "immcrime1"       "immjobs1"        "immideas1"      
[6789] "immwlfare"       "conscrp"         "incgap1"         "leftrght1"      
[6793] "servpub"         "fulldem"         "poltalk"         "conpow"         
[6797] "bizmoney"        "experts"         "biasnews"        "usmca1"         
[6801] "usmca2"          "morextrm"        "bullied"         "smedia"         
[6805] "imprvown1"       "mustdoc1"        "mustmed1"        "musthosp1"      
[6809] "physill1"        "bullpeer"        "rumopeer"        "fighpeer"       
[6813] "schshoot"        "cutself"         "negself"         "foodalc"        
[6817] "risklife"        "takelife"        "sexornt1"        "sexpaid"        
[6821] "nocondom"        "nodocidu"        "femself1"        "mascself1"      
[6825] "femsee1"         "mascsee1"        "family16sex"     "racdif5x"       
[6829] "sexnow2"         "whovote24"       "whovotets"       "voteprob"       
[6833] "rateincumbts"    "ratechall1ts"    "ratechall2ts"    "ratechall3ts"   
[6837] "chldfam_asn"     "chldfam_blk"     "chldfam_hisp"    "chldfam_wht"    
[6841] "chldfam_oth"     "chldadlt_asn"    "chldadlt_blk"    "chldadlt_hisp"  
[6845] "chldadlt_wht"    "chldadlt_oth"    "chldchld_asn"    "chldchld_blk"   
[6849] "chldchld_hisp"   "chldchld_wht"    "chldchld_oth"    "chldshop_asn"   
[6853] "chldshop_blk"    "chldshop_hisp"   "chldshop_wht"    "chldshop_oth"   
[6857] "ptnrsxnow1"      "hispanic_0022"   "numemps_0422"    "uscitzn_0822"   
[6861] "uscitznv_2122"   "uscitznnv_2122"  "sibs_7222"       "racecen1_0022"  
[6865] "racecen2_0022"   "racecen3_0022"   "earnrs_7222"    </code></pre>
</div>
</div>
</section>
<section id="variables" class="level2">
<h2 class="anchored" data-anchor-id="variables">Variables</h2>
<p>For information about a specific GSS variable, type <code>?varname</code> at the console.</p>
<p>In the output pane, the Help tab will show the variable documentation.</p>
<p>Example: <code>?meovrwrk</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>?meovrwrk</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>starting httpd help server ... done</code></pre>
</div>
</div>
<p><strong>Notes:</strong></p>
<p>Variable name: meovrwrk<br>
Variable label: Men hurt family when focus on work too much<br>
1994 was the first year of the survey.<br>
695 respondents agreed with the statement.<br>
iap – missing. Values: the numeric and response category key (1 = strongly agree)</p>
<p>We often want to know which years a question was asked.</p>
<p>We can find this out for one or more variables with <code>gss_which_years()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gss_which_years</span>(gss_all, meovrwrk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 35 × 2
   year      meovrwrk
   &lt;dbl+lbl&gt; &lt;lgl&gt;   
 1 1972      FALSE   
 2 1973      FALSE   
 3 1974      FALSE   
 4 1975      FALSE   
 5 1976      FALSE   
 6 1977      FALSE   
 7 1978      FALSE   
 8 1980      FALSE   
 9 1982      FALSE   
10 1983      FALSE   
# ℹ 25 more rows</code></pre>
</div>
</div>
<p>If run in the console, to see all rows, wrap the code in the <code>print()</code> command:</p>
<p><code>print(gss_which_years(gss_all, fefam), n = 40)</code></p>
<p>You can access the variables (i.e., columns) using the $ operator, as shown using the <code>table()</code> function</p>
<p>(NOTE: The variable names are case sensitive. In this dataset, all variables are lowercase.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(gss_all<span class="sc">$</span>meovrwrk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2     3     4     5 
 2436 10813  4797  5806   927 </code></pre>
</div>
</div>
<p>2436 respondents were coded as <code>1</code> on this variable. What does that mean? (Look at the help page.)</p>
<p>The table command also let’s you create a table with two variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1st variable is the rows, 2nd variable is the columns.</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(gss_all<span class="sc">$</span>year, gss_all<span class="sc">$</span>meovrwrk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      
          1    2    3    4    5
  1972    0    0    0    0    0
  1973    0    0    0    0    0
  1974    0    0    0    0    0
  1975    0    0    0    0    0
  1976    0    0    0    0    0
  1977    0    0    0    0    0
  1978    0    0    0    0    0
  1980    0    0    0    0    0
  1982    0    0    0    0    0
  1983    0    0    0    0    0
  1984    0    0    0    0    0
  1985    0    0    0    0    0
  1986    0    0    0    0    0
  1987    0    0    0    0    0
  1988    0    0    0    0    0
  1989    0    0    0    0    0
  1990    0    0    0    0    0
  1991    0    0    0    0    0
  1993    0    0    0    0    0
  1994  122  695  286  243   41
  1996  230  825  169  198   21
  1998    0    0    0    0    0
  2000  209  877  331  361   34
  2002   99  415  108  264   16
  2004   94  460  135  188   25
  2006  208  945  304  477   43
  2008  143  653  161  310   50
  2010  122  662  192  388   57
  2012  130  558  170  382   51
  2014  176  702  234  479   76
  2016  171  819  257  536   96
  2018  134  644  220  475   73
  2021  202  886 1001  487  138
  2022  201  885  618  537  117
  2024  195  787  611  481   89</code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>