---
title: "Lab 01"
format:
  revealjs:
    multiplex: true
    controls: true
    theme: [default, custom.scss]
    include-in-header:
    - file: mathjax-color.html
    slide-number: c
    math: mathjax
revealjs-plugins:
  - quiz
embed-resources: true
filters:
    - openlinksinnewpage
editor: 
  markdown: 
    wrap: 72

---

```{r setup, include = FALSE}
## Load packages, custom functions, and styles
source("custom-setup-styles.R")

# Color in math equations
# https://egallic.fr/Recherche/aide-memoire/quarto_equation_colors.html#colors-in-equations-with-revealjs
```


# Agenda {data-menu-title="Agenda" background-image="images/calendar.png" background-size="100px" background-repeat="repeat"}

-    How R Works
-    R Workflow
-    Learning to Code


## Filepaths

Adopt a project-based workflow to avoid changing file paths

here:here() # set the file path to the root of the project

## file names should be

-   machine-readable
-   humand-readable
-   play well with default-ordering

## reproducibility 

session_info() # software documentation

Quarto: The tool you'll use to create reproducible computational documents. 
Every piece of assignment you hand in will be a Quarto document.

::: callout-note
You are likely familiar with word processors like MS Word or Google Docs.
We will not be using these in this class.
Instead, the words you would write in such a document, as well as your R code, 
will go into a Quarto document. 
You will *render* the document (more on what this means later) 
to get a document out that has your words, code, and the output of that code.
Everything in one place, beautifully formatted!
:::

