---
title: "Lab 00"
format:
  html:
    multiplex: true
    controls: true
    theme: [default, custom.scss]
    include-in-header:
    - file: mathjax-color.html
    slide-number: c
    math: mathjax
embed-resources: true
filters:
    - openlinksinnewpage
editor: 
  markdown: 
    wrap: 72
---

```{r setup, include = FALSE}
## Load packages, custom functions, and styles
source("custom-setup-styles.R")

# Color in math equations
# https://egallic.fr/Recherche/aide-memoire/quarto_equation_colors.html#colors-in-equations-with-revealjs
```

# Agenda {data-menu-title="Agenda" background-image="images/calendar.png" background-size="100px" background-repeat="repeat"}

-   Install R
-   Install R-studio
-   Quarto

This lab will set you up for the computing workflow.

# `Hello, World!`

You may have heard/seen this phrase, `Hello, World!`, elsewhere before.
Learning to write a computer program to print this sentence to your
screen is often the first thing you learn in programming.

To make sure you are ready *use* a computer program (R) to **work with
data**, this lab will set you up to use R to print this sentence to your
screen.

# Computational toolkit:

1.  R: The programming language you'll learn in this course.

2.  RStudio: The software you'll use to write R code in.

::: callout-note
R is the name of the programming language itself and RStudio is a
convenient interface.
:::

# Download and Install R

R is available through the web page of [The Comprehensive R Archive
Network](http://cran.r-project.org/) (CRAN).

The top of the web page provides three links for downloading R. Follow
the link that describes your operating system: Windows, Mac, or Linux.
Complete instructions area available from
[rstudio-education](https://rstudio-education.github.io/hopr/starting.html),
with key steps listed below.

### R: Windows

To install R on Windows, click the “Download R for Windows” link.

Then click the “base” link.

Next, click the first link at the top of the new page. This link should
say something like “Download R 4.5.1 for Windows.” (Note: 4.5.1 will be
replaced by the most current version of R.)

The link downloads an installer program, which installs the most
up-to-date version of R for Windows.

Run this program and step through the installation wizard that appears.
The wizard will install R into your program files folders and place a
shortcut in your Start menu. You’ll need to have all of the appropriate
administration privileges to install new software on your machine.



### R: Mac

To install R on a Mac, click the “Download R for Mac” link. Next, click
on the `R-4.5.1` package link (or the package link for the most current
release of R). An installer will download to guide you through the
installation process. The installer lets you customize your
installation, but the defaults will be suitable for most users. If your
computer requires a password before installing new progams, you’ll need
it here.

::: callout-note
## Help Videos

If you prefer to watch a video, 
I recommend Windows users 
[watch this video](https://www.youtube.com/watch?v=4AjFbJsNNb8) and 
Mac users [watch this video](https://www.youtube.com/watch?v=8NvvydRwxEI). 
Of course, you can search out a video yourself if you prefer.

[This video](https://www.youtube.com/watch?v=4AjFbJsNNb8) shows you step
by step how to install R and RStudio on Apple Mac OS computers.
:::
