```{r data type, echo = FALSE, results = "hide"}

pacman::p_load(
  tidyverse,
  gssr, # load U.S. gss data
  gssrdoc, # load the gss codebook
  haven, # work with labeled data
  labelled, # use labels as values
  summarytools, # easy descriptive statistics
  conflicted # declare primary packages
)

## Address important conflicts
conflict_prefer("is.labelled", "haven")
conflict_prefer("filter", "dplyr")
conflict_scout() # Identify the conflicts

## Load the gss datasets

data(gss_all) # Load all gss
gss24 <- gss_get_yr(2024) # 2024 survey respondents
gss22 <- gss_get_yr(2022) # 2022 survey respondents

# Load the codebook
data(gss_dict)

gss24$hapmar <- zap_missing(gss24$hapmar)
gss24$hapmar <- as_factor(gss24$hapmar)
gss24$hapmar <- droplevels(gss24$hapmar)

```

Question
========
The level of measurement for the `hapmar` variable is \_\_\_\_\_\_\_\_\_

```{r output, echo = FALSE, results = "asis"}
#| message: false

# Variable label
var_label(gss_all$hapmar)

# Response options
freq(gss24$hapmar, report.nas = FALSE)
```

Answerlist
----------

* dichotomous

* nominal

* ordinal

* interval

Meta-information
================
exname: type
extype: schoice
exsolution: 0010
exshuffle: 4
