---
title: "Welcome"
format:
  html:
    theme: [default, custom.scss]
---

# **Stats for Sociologists (SOC6302H)!**

Allow me to introduce myself. My name is Joanna Pepin and I will be your
professor for this course. I am looking forward to teaching you this
semester.

A draft of the [**course**
**syllabus**](https://jrpepin.github.io/Stats-for-Sociologists/) is
available, but subject to changes until the semester begins.

# Schedule:

**Lecture:** Tuesdays, 10:00 AM - 12:00 PM;

**Lab**: Tuesdays, 12:00 PM - 1:00 PM

The course begins on **Tuesday, September 2nd at 10:10am** (EST) and
will run through November 25th.

# Get Prepared:

**You can get prepared for class with two actions, available in the
first module**:

1.  Complete the assigned reading.

2.  Complete the first tutorial, making sure to [**complete the
    `R  environment` section**]{style="color: #E74C3C;"}.

You do [NOT need to purchase a textbook]{.underline} for this course.

::: {.callout-tip icon="false"}
## {{< fa hat-wizard >}} Heads up!

To effectively participate in this course during class and outside of
lectures and labs, you should have access to a Windows or Mac computer
with broadband internet connection. Your best opportunity for success
will require these minimum technology capabilities listed on this
[**UofT
website**](https://www.viceprovoststudents.utoronto.ca/student-policies-guidelines/tech-requirements-online-learning/).
:::
