---
title: "Tutorial 01"
output:
  learnr::tutorial:
    progressive: true
    allow_skip: false
    theme: flatly
    css: css/mystyle.css
    df_print: "paged"
runtime: shiny_prerendered
tutorial:
  id: "01.1"
---

```{r setup, include=FALSE}
library(learnr)
library(fontawesome)
library(learnrhash)
library(fontawesome)
library(gfonts)

knitr::opts_chunk$set(echo = TRUE)
```

# Introduction to Data Analysis

`r fa("fas fa-lightbulb", fill = "#18BC9C")` [**LEARNING OBJECTIVES**]{.shadows-text style="color: #18BC9C;"}

1.  Be familiar with basic terms of quantitative data analysis
2.  Describe effective methods of learning to code

`r fa("fas fa-book", fill = "#18BC9C")` [**READINGS**]{.shadows-text style="color: #18BC9C;"}

Readings are available on Quercus.

1.  What's the point?
2.  Descriptive Statistics: Who Was the Best Baseball Player of All Time?

`r fa("fas fa-language", fill = "#18BC9C")` [**TERMS**]{.shadows-text style="color: #18BC9C;"}

-   UNIT OF ANALYSIS\
-   POPULATION\
-   SAMPLE\
-   N & n
-   DESCRIPTIVE STATISTICS\
-   INFERENTIAL STATISTICS\
-   TIDY DATA\
-   VARIABLES\
-   DICHOTOMOUS\
-   NOMINAL\
-   ORDINAL\
-   INTERVAL-RATIO\

## Introduction to Tutorials

This is a different section.

### Heading A

text A

### Heading B

text B

## Data Analysis Basics

Some text goes here.

### Unit of Analysis

::: {style="color: #e74c3c; font-size: 150%; font-family: 'Shadows Into Light'"}
Who or what is being studied?
:::

<br>

::: {.my-callout}
### Heads Up!
This is a custom callout block styled with CSS.
:::

<br>
